Repository kubeflow/trainer, pull requests merged in 2018-07, with the labels that each got.

#711 [v1alpha2] Add more validation of TFJobSpec
  pkg/apis/tensorflow/validation/validation.go
  pkg/apis/tensorflow/validation/validation_test.go
Labels: approved, lgtm, size/M

#714 OWNERS: Add yph152 and codeflitting as reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#715 [v1alpha2]Remove redundant code about status and fix bug of invalid job status
  pkg/controller.v2/controller_status.go
  pkg/controller.v2/controller_status_test.go
Labels: approved, lgtm, size/L

#717 [v1alpha2] Add PDB of TFReplicaSet for gang scheduling by kube-arbitrator
  cmd/tf-operator.v2/app/options/options.go
  cmd/tf-operator.v2/app/server.go
  pkg/controller.v2/controller.go
  pkg/controller.v2/controller_pod_test.go
  pkg/controller.v2/controller_service_test.go
  pkg/controller.v2/controller_test.go
  pkg/controller.v2/controller_tfjob_test.go
Labels: approved, lgtm, size/L

#721 delete pdb when tfjob is terminated
  pkg/controller.v2/controller.go
  pkg/controller.v2/controller_tfjob.go
Labels: approved, lgtm, size/M

#724 Fix a log function issue
  pkg/trainer/training.go
Labels: approved, lgtm, size/XS

#728 Add retrying to log_status function
  py/tf_job_client.py
Labels: approved, lgtm, size/XS

#726 Update developer_guide.md for v1alpha2
  developer_guide.md
Labels: approved, lgtm, size/XS

#732 Add err msg for TFJob from Unstructured
  pkg/controller.v2/informer.go
Labels: approved, lgtm, size/S

#733 Generate api information in OpenAPI model and register types to scheme
  hack/update-codegen.sh
  pkg/apis/tensorflow/v1alpha2/install.go
  pkg/apis/tensorflow/v1alpha2/openapi_generated.go
Labels: approved, lgtm, size/XXL

#735 test fix: None type check
  py/tf_job_client.py
Labels: approved, lgtm, size/XS

#734 fix not proper log message
  pkg/controller.v2/controller.go
Labels: approved, lgtm, size/XS

#725 cleanup jobs after finished
  pkg/apis/tensorflow/v1alpha2/types.go
  pkg/apis/tensorflow/v1alpha2/zz_generated.deepcopy.go
  pkg/controller.v2/controller.go
  pkg/controller.v2/controller_status.go
Labels: approved, lgtm, size/M

#738 fix list all the pods of tfjob
  dashboard/backend/handler/api_handler.go
Labels: approved, lgtm, size/XS

#741 OWNER: Add cheyang, Remove mitake
  OWNERS
Labels: approved, lgtm, size/XS

#740 build: Remove the useless script
  build/images/tf_operator/build_and_push.py
Labels: approved, lgtm, size/L

#688 setup cors for redirects under iap
  dashboard/backend/handler/api_handler.go
  dashboard/frontend/src/services.js
Labels: approved, lgtm, size/M

#745 Fix a test flake caused by conditions being None
  py/tf_job_client.py
Labels: approved, lgtm, size/XS

#746 Revert "cleanup jobs after finished (#725)"
  pkg/apis/tensorflow/v1alpha2/types.go
  pkg/apis/tensorflow/v1alpha2/zz_generated.deepcopy.go
  pkg/controller.v2/controller.go
  pkg/controller.v2/controller_status.go
Labels: approved, lgtm, size/M

#752 Name Error: mv tj_job_mnist.yaml to tf_job_mnist.yaml
  examples/v1alpha2/dist-mnist/tf_job_mnist.yaml
Labels: approved, lgtm, size/XS

#749 Prevent multiple versions of an E2E test from clobbering each other.
  examples/tf_sample/Dockerfile
  examples/tf_sample/Dockerfile.template
  examples/tf_sample/Makefile
  examples/tf_sample/build_and_push.py
  examples/tf_sample/tf_sample/__init__.py
  examples/tf_sample/tf_smoke.py
  py/release.py
  py/test_runner.py
  py/tf_job_client.py
  test/workflows/app.yaml
  test/workflows/components/gpu_tfjob_v1alpha1.jsonnet
  test/workflows/components/gpu_tfjob_v1alpha2.jsonnet
  test/workflows/components/params.libsonnet
  test/workflows/components/simple_tfjob_v1alpha1.jsonnet
  test/workflows/components/simple_tfjob_v1alpha2.jsonnet
  test/workflows/components/workflows.libsonnet
  test/workflows/environments/kubeflow-dev/globals.libsonnet
  test/workflows/environments/kubeflow-dev/main.jsonnet
  test/workflows/environments/kubeflow-dev/params.libsonnet
Labels: approved, lgtm, size/XL

#758 linter: Rename gas to gosec and fix linting errors
  cmd/tf-operator/app/server.go
  linter_config.json
  pkg/controller.v2/controller_pod.go
  pkg/controller.v2/controller_service.go
  pkg/controller.v2/controller_tensorflow.go
Labels: approved, lgtm, size/M

#753 Cleanup tf-job after a configured TTL
  pkg/apis/tensorflow/v1alpha2/types.go
  pkg/apis/tensorflow/v1alpha2/zz_generated.deepcopy.go
  pkg/controller.v2/controller.go
  pkg/controller.v2/controller_tfjob.go
  pkg/controller.v2/controller_tfjob_test.go
  pkg/util/testutil/tfjob.go
Labels: approved, lgtm, size/L
