Repository kubeflow/trainer, pull requests merged in 2018-10, with the labels that each got.

#834 fix ERROR: logging before flag.Parse issue
  dashboard/backend/main.go
Labels: approved, lgtm, size/XS

#835 travis: Fix a typo
  .travis.yml
Labels: approved, lgtm, size/XS

#839 Update changelog to include changes in v0.3.
  CHANGELOG.md
  hack/scripts/update-changelog.sh
Labels: approved, lgtm, size/M

#841 add frontend-dir & port flag to backend program
  dashboard/backend/main.go
Labels: approved, lgtm, size/S

#820 feat: ensure that tfjob crd exists.
  Gopkg.lock
  cmd/tf-operator.v2/app/server.go
  pkg/apis/tensorflow/v1alpha2/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/helpers.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/generated_expansion.go
Labels: approved, lgtm, size/XXL

#845 Refactor E2E tests (part 1)
  py/k8s_util.py
  py/ks_util.py
  py/test_invalid_job.py
  py/test_runner.py
  py/tf_job_client.py
Labels: approved, lgtm, size/XL

#847 Add richardsliu to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#846 Remove v1alpha1 E2E tests
  prow_config.yaml
  test/workflows/components/gpu_tfjob_v1alpha1.jsonnet
  test/workflows/components/master_is_chief_v1alpha1.jsonnet
  test/workflows/components/params.libsonnet
  test/workflows/components/simple_tfjob_v1alpha1.jsonnet
  test/workflows/components/worker0_is_chief_v1alpha1.jsonnet
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#849 Refactor tf-operator E2E tests (part 2)
  py/cleanpod_policy_tests.py
  py/estimator_runconfig_tests.py
  py/invalid_tfjob_tests.py
  py/ks_util.py
  py/shutdown_policy_tests.py
  py/simple_tfjob_tests.py
  py/test_invalid_job.py
  py/test_runner.py
  py/tf_job_client.py
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XXL

#853 Add the ability to skip a E2E test
  py/test_runner.py
Labels: approved, lgtm, size/S

#852 Add documentation for writing E2E tests
  e2e_testing.md
Labels: approved, lgtm, size/M
