Repository kubeflow/trainer, pull requests merged in 2018-04, with the labels that each got.

#520 Reenable cluster teardown.
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XS

#527 tests: Fix
  pkg/controller/controller_test.go
  version/version.go
Labels: size/S

#525 v1alpha2: update flag kubeconfig
  cmd/tf-operator/app/options/options.go
Labels: approved, lgtm, needs-ok-to-test, size/XS, status/blocked

#528 developer_guide: Add instructions for v1alpha2
  developer_guide.md
Labels: approved, lgtm, size/M

#531 signals: Add
  pkg/util/signals/signal.go
  pkg/util/signals/signal_posix.go
  pkg/util/signals/signal_windows.go
Labels: approved, lgtm, size/M

#529 OWNERS: Add @ddysher and @willb as reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#539 fix the bug of keeping creating new pdb
  pkg/trainer/training.go
Labels: approved, lgtm, size/XS

#542 copy labels and anotations to pod from pod template
  pkg/trainer/replicas.go
  pkg/trainer/replicas_test.go
Labels: approved, lgtm, size/M

#526 v1alpha2: Add implementation
  .travis.yml
  cmd/tf-operator.v2/app/options/options.go
  cmd/tf-operator.v2/app/server.go
  cmd/tf-operator.v2/main.go
  cmd/tf-operator/app/server.go
  linter_config.json
  pkg/controller.v2/controller.go
  pkg/controller.v2/controller_logger.go
  pkg/controller.v2/controller_pod.go
  pkg/controller.v2/controller_pod_test.go
  pkg/controller.v2/controller_ref_manager.go
  pkg/controller.v2/controller_service.go
  pkg/controller.v2/controller_service_test.go
  pkg/controller.v2/controller_tensorflow.go
  pkg/controller.v2/controller_test.go
  pkg/controller.v2/controller_utils.go
  version/version.go
Labels: approved, lgtm, size/XXL

#518 Only identify specific exit codes as retryable error
  README.md
  pkg/trainer/replicas.go
  pkg/trainer/training.go
  pkg/trainer/training_test.go
  pkg/util/train/train_util.go
Labels: approved, lgtm, size/L

#469 Use a CentOS 7 base image for the tf-operator image
  build/images/tf_operator/Dockerfile
Labels: approved, lgtm, size/XS

#553 README: Add tf-operator v1alpha2 design doc
  README.md
Labels: approved, lgtm, size/XS

#554 set completion time on success
  pkg/controller.v2/controller_pod.go
Labels: approved, lgtm, size/XS

#559 Correct typos in README
  README.md
Labels: approved, lgtm, size/XS

#548 controller: Refactor controller_pod
  pkg/controller.v2/controller.go
  pkg/controller.v2/controller_logger.go
  pkg/controller.v2/controller_pod.go
  pkg/controller.v2/controller_status.go
  pkg/controller.v2/controller_test.go
Labels: approved, lgtm, size/L
