Repository kubeflow/trainer, pull requests merged in 2018-06, with the labels that each got.

#614 controller: Refactor and add test cases for helper
  cmd/tf-operator.v2/app/server.go
  cmd/tf-operator/app/server.go
  pkg/apis/tensorflow/v1alpha2/register.go
  pkg/controller.v2/controller.go
  pkg/controller.v2/controller_helper.go
  pkg/controller.v2/controller_helper_test.go
  pkg/controller.v2/service_control.go
  pkg/controller.v2/service_ref_manager.go
  pkg/version/version.go
  py/release.py
Labels: approved, lgtm, size/L

#613 [dashboard] Upgrade to v1alpha2
  dashboard/backend/handler/api_handler.go
  dashboard/frontend/src/components/CreateJob.js
  dashboard/frontend/src/components/CreateReplicaSpec.js
  dashboard/frontend/src/components/Job.js
  dashboard/frontend/src/components/JobDetail.js
  dashboard/frontend/src/components/JobSummary.js
  dashboard/frontend/src/components/PodList.js
  dashboard/frontend/src/components/ReplicaSpec.js
  dashboard/frontend/src/components/VolumeCreator.js
Labels: approved, lgtm, size/XL

#619 Add apiVersion parameter to simple_tfjob component
  test/workflows/components/params.libsonnet
  test/workflows/components/simple_tfjob.jsonnet
Labels: approved, lgtm, size/XS

#618 api_handler: Fix import order
  .travis.yml
  dashboard/backend/handler/api_handler.go
  linter_config.json
Labels: approved, lgtm, size/S

#576 controller_service: Headless service
  pkg/controller.v2/controller_helper.go
  pkg/controller.v2/controller_service.go
  pkg/controller.v2/controller_tensorflow.go
Labels: approved, lgtm, priority/p1, size/S

#623 pkg: Send events when reveive invalid spec
  pkg/controller.v2/controller.go
  pkg/controller.v2/controller_helper.go
  pkg/controller.v2/controller_tfjob.go
  pkg/controller.v2/informer.go
Labels: approved, lgtm, size/S

#621 pkg: Support customized port
  pkg/apis/tensorflow/v1alpha2/constants.go
  pkg/apis/tensorflow/v1alpha2/defaults.go
  pkg/apis/tensorflow/v1alpha2/defaults_test.go
  pkg/controller.v2/controller.go
  pkg/controller.v2/controller_helper.go
  pkg/controller.v2/controller_pod.go
  pkg/controller.v2/controller_service.go
  pkg/controller.v2/controller_tensorflow.go
  pkg/controller.v2/controller_tfjob_test.go
  test/e2e/dist-mnist/tj_job_mnist.yaml
Labels: approved, lgtm, size/L

#626 Pass TFJob API version instead of hardcoding it
  py/test_runner.py
  py/tf_job_client.py
Labels: approved, lgtm, size/S

#627 Use logging.exception to capture stack traces in logs
  py/test_runner.py
Labels: approved, lgtm, size/S

#629 Updates to enable e2e test for v1alpha2
  py/test_runner.py
  py/tf_job_client.py
  test/workflows/components/simple_tfjob.jsonnet
Labels: approved, lgtm, size/M

#642 Add proper error handling for deploying the tests.
  py/deploy.py
  py/test_runner.py
Labels: approved, lgtm, size/S

#638 pods: Add restart policy
  pkg/apis/tensorflow/v1alpha2/types.go
  pkg/controller.v2/controller_pod.go
Labels: approved, lgtm, size/M

#649 pods: Add cluster spec test
  pkg/controller.v2/controller_pod.go
  pkg/controller.v2/controller_pod_test.go
  pkg/controller.v2/controller_tfjob_test.go
Labels: approved, lgtm, size/M

#650 [v1alpha2] Estimator support - Do not include `evaluator` in cluster spec
  developer_guide.md
  examples/crd/crd-v1alpha2.yaml
  pkg/apis/tensorflow/v1alpha2/types.go
  pkg/controller.v2/controller_tensorflow.go
Labels: approved, lgtm, size/S

#643 status: Add test cases for failure
  pkg/controller.v2/controller_pod.go
  pkg/controller.v2/controller_status.go
  pkg/controller.v2/controller_status_test.go
  pkg/controller.v2/controller_tfjob.go
  pkg/controller.v2/controller_tfjob_test.go
Labels: approved, lgtm, size/L

#648 pod: Submit an event when the user specifies the restartpolicy for pod template
  pkg/controller.v2/controller_pod.go
  pkg/controller.v2/controller_pod_test.go
Labels: approved, lgtm, size/M

#656 *: Remove namespace from service name
  pkg/controller.v2/controller_helper.go
  pkg/controller.v2/controller_pod_test.go
  pkg/controller.v2/controller_service.go
  pkg/controller.v2/controller_tensorflow.go
Labels: approved, lgtm, size/S

#652 pod: Add test for exit code
  pkg/controller.v2/controller_pod_test.go
  pkg/controller.v2/pod_control.go
Labels: approved, lgtm, size/L

#658 tfjob: Add test for copy labels and annotations
  pkg/controller.v2/controller_tfjob_test.go
Labels: approved, lgtm, size/M

#646 v1alpha2 E2E tests for termination policy
  py/test_runner.py
  py/tf_job_client.py
  test/test-server/Dockerfile
  test/test-server/Makefile
  test/test-server/README.md
  test/test-server/test_app.py
  test/workflows/app.yaml
  test/workflows/components/master_is_chief_v1alpha1.jsonnet
  test/workflows/components/master_is_chief_v1alpha2.jsonnet
  test/workflows/components/params.libsonnet
  test/workflows/components/worker0_is_chief_v1alpha1.jsonnet
  test/workflows/components/worker0_is_chief_v1alpha2.jsonnet
  test/workflows/components/workflows.libsonnet
  test/workflows/environments/kubeflow-dev/globals.libsonnet
  test/workflows/environments/kubeflow-dev/main.jsonnet
  test/workflows/environments/kubeflow-dev/params.libsonnet
  test/workflows/environments/test/params.libsonnet
  test/workflows/lib/v1.9.6/k.libsonnet
  test/workflows/lib/v1.9.6/k8s.libsonnet
  test/workflows/lib/v1.9.6/swagger.json
Labels: approved, lgtm, size/XXL

#662 server: Make threadiness configurable
  cmd/tf-operator.v2/app/options/options.go
  cmd/tf-operator.v2/app/server.go
Labels: approved, lgtm, size/XS

#669 defaults: Rename the type
  pkg/apis/tensorflow/v1alpha2/defaults.go
  pkg/apis/tensorflow/v1alpha2/defaults_test.go
Labels: approved, lgtm, release/0.2.0, size/M

#666 *: Move test util to separate package
  .travis.yml
  pkg/controller.v2/controller_pod.go
  pkg/controller.v2/controller_pod_test.go
  pkg/controller.v2/controller_service.go
  pkg/controller.v2/controller_service_test.go
  pkg/controller.v2/controller_status.go
  pkg/controller.v2/controller_status_test.go
  pkg/controller.v2/controller_tensorflow.go
  pkg/controller.v2/controller_test.go
  pkg/controller.v2/controller_tfjob.go
  pkg/controller.v2/controller_tfjob_test.go
  pkg/controller.v2/pod_control_test.go
  pkg/controller.v2/service_control_test.go
  pkg/controller.v2/service_ref_manager_test.go
  pkg/generator/generator.go
  pkg/generator/generator_test.go
  pkg/util/testutil/const.go
  pkg/util/testutil/pod.go
  pkg/util/testutil/service.go
  pkg/util/testutil/tfjob.go
  pkg/util/testutil/util.go
Labels: approved, lgtm, size/XL

#670 controller: Move control interface to control package
  pkg/control/pod_control.go
  pkg/control/pod_control_test.go
  pkg/control/service_control.go
  pkg/control/service_control_test.go
  pkg/control/service_ref_manager.go
  pkg/control/service_ref_manager_test.go
  pkg/controller.v2/controller.go
  pkg/controller.v2/controller_pod.go
  pkg/controller.v2/controller_service.go
  pkg/controller.v2/controller_test.go
Labels: approved, lgtm, size/M

#679 change comment with more related link
  pkg/controller.v2/controller_tensorflow.go
Labels: approved, lgtm, size/XS

#677 fix typo
  pkg/controller.v2/controller_pod.go
  pkg/controller.v2/controller_service.go
Labels: approved, lgtm, size/XS

#660 dist-mnist: Move to examples
  docs/quick-start-v1alpha2.md
  examples/v1alpha2/dist-mnist/Dockerfile
  examples/v1alpha2/dist-mnist/README.md
  examples/v1alpha2/dist-mnist/dist_mnist.py
  examples/v1alpha2/dist-mnist/tj_job_mnist.yaml
Labels: approved, lgtm, release/0.3.0, size/M

#667 Enable the E2E tests for v1alpha2.
  prow_config.yaml
  py/deploy.py
  py/test_runner.py
  py/tf_job_client.py
  test/workflows/app.lock
  test/workflows/app.yaml
  test/workflows/components/master_is_chief_v1alpha2.jsonnet
  test/workflows/components/worker0_is_chief_v1alpha2.jsonnet
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#676 fix restart policy with comment
  pkg/apis/tensorflow/v1alpha2/constants.go
  pkg/apis/tensorflow/v1alpha2/defaults.go
  pkg/apis/tensorflow/v1alpha2/defaults_test.go
  pkg/apis/tensorflow/v1alpha2/types.go
  pkg/controller.v2/controller_pod.go
  pkg/controller.v2/controller_pod_test.go
Labels: approved, lgtm, size/L

#678 return err if the spec area is nil after unmashal for tfjob v1alpha2
  pkg/controller.v2/informer.go
Labels: approved, lgtm, size/XS

#681 Remove code that is no longer used.
  examples/gke/notebook_image/Dockerfile
  examples/gke/notebook_image/Makefile
  examples/gke/test_notebook.py
  examples/tensorflow-models/Dockerfile.template
  examples/tensorflow-models/README.md
  examples/tf_job/.helmignore
  examples/tf_job/Chart.yaml
  examples/tf_job/templates/_helpers.tpl
  examples/tf_job/templates/tf_job.yaml
  examples/tf_job/values.yaml
Labels: approved, lgtm, size/L

#625 [v1alpha2] Add distributed state management
  pkg/controller.v2/controller.go
  pkg/controller.v2/controller_pod.go
  pkg/controller.v2/controller_status.go
  pkg/controller.v2/controller_status_test.go
Labels: approved, lgtm, size/XL

#684 informer: Add comments and TODO
  pkg/controller.v2/informer.go
Labels: approved, lgtm, size/XS

#683 and some safety check
  pkg/controller.v2/controller.go
  pkg/controller.v2/controller_status.go
Labels: approved, lgtm, size/S

#686 pkg: Delete pods and services after finished
  pkg/control/service_control.go
  pkg/controller.v2/controller.go
  pkg/controller.v2/controller_pod.go
  pkg/controller.v2/controller_status.go
  pkg/controller.v2/controller_status_test.go
  pkg/controller.v2/controller_tfjob.go
  py/test_runner.py
Labels: approved, lgtm, size/L

#690 status: Fail the TFJob if PS is failed
  pkg/controller.v2/controller_status.go
  pkg/controller.v2/controller_status_test.go
Labels: approved, lgtm, size/L

#689 Use tf_job_name not tf_job_key as the label name.
  pkg/generator/generator.go
  pkg/generator/generator_test.go
  py/test_runner.py
Labels: approved, lgtm, size/S

#685 define cleanup policy
  examples/tf_job_clean_policy.yaml
  pkg/apis/tensorflow/v1alpha1/types.go
  pkg/trainer/replicas.go
  pkg/trainer/training.go
Labels: approved, lgtm, size/L

#694 [v1alpha2]update tfjob condition for Created
  pkg/controller.v2/controller_tfjob.go
  pkg/controller.v2/informer.go
Labels: approved, lgtm, size/S

#695 Use logrus instead of glog in service_control
  pkg/control/service_control.go
Labels: approved, lgtm, size/XS

#699 Wrong comment when setting default CleanPodPolicy
  pkg/apis/tensorflow/v1alpha2/defaults.go
  pkg/apis/tensorflow/v1alpha2/types.go
Labels: approved, lgtm, size/XS

#700 [v1alpha2] controller_pod_test: Add test cases for evaluator
  pkg/controller.v2/controller_pod_test.go
  pkg/util/testutil/tfjob.go
Labels: approved, lgtm, size/S

#704 Fix sub domain issue
  pkg/controller.v2/controller_pod_test.go
  pkg/controller.v2/controller_tensorflow.go
  pkg/generator/generator.go
Labels: approved, lgtm, size/S
