Repository kubeflow/trainer, pull requests merged in 2018-09, with the labels that each got.

#819 pod: Fix eventf
  pkg/controller.v2/tensorflow/pod.go
Labels: approved, lgtm, size/XS

#821 Adding corev1 scheme to Events
  cmd/tf-operator.v2/app/server.go
  pkg/controller.v2/jobcontroller/pod.go
Labels: approved, lgtm, size/XS

#817 Set artifacts dir so that the output of invalid-job test will be picked up.
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XS

#823 remove schedulerName from tfjob spec
  pkg/apis/tensorflow/v1alpha2/types.go
  pkg/controller.v2/tensorflow/pod.go
Labels: approved, lgtm, size/XS

#814 Estimator e2etest
  py/test_runner.py
  py/util.py
  test/test-server/Dockerfile
  test/test-server/test_app.py
  test/workflows/components/estimator_runconfig.jsonnet
  test/workflows/components/params.libsonnet
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#827 Cleanup unused functions
  pkg/util/k8sutil/k8sutil.go
Labels: approved, lgtm, size/S

#828 Fix typos
  examples/crd/crd-v1alpha2.yaml
  pkg/controller.v2/jobcontroller/jobcontroller.go
  pkg/controller.v2/tensorflow/job.go
  pkg/controller.v2/tensorflow/pod.go
  pkg/controller/controller.go
  pkg/trainer/replicas.go
  pkg/trainer/training.go
Labels: approved, lgtm, size/S

#832 Fix postusbmit builds; registry is incorrect.
  prow_config.yaml
Labels: approved, lgtm, size/XS

#833 Ankush Signing Out
  OWNERS
Labels: approved, lgtm, size/XS
