Repository kubeflow/trainer, pull requests merged in 2018-03, with the labels that each got.

#425 Delete Dockerfile to build a docker image to use for prow.
  test/test-infra/Dockerfile
  test/test-infra/Makefile
  test/test-infra/README.md
  test/test-infra/run.sh
Labels: approved, lgtm, size/M

#416 Use logrus for structured logging
  cmd/tf-operator/app/options/options.go
  cmd/tf-operator/app/server.go
  cmd/tf-operator/main.go
  glide.lock
  glide.yaml
  pkg/client/clientset/versioned/clientset.go
  pkg/controller/controller.go
  pkg/trainer/replicas.go
  pkg/trainer/training.go
  pkg/util/k8sutil/k8sutil.go
  pkg/util/util.go
  vendor/github.com/golang/glog/README
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/onrik/logrus/.gitignore
  vendor/github.com/onrik/logrus/LICENSE
  vendor/github.com/onrik/logrus/README.md
  vendor/github.com/onrik/logrus/filename/filename.go
  vendor/github.com/onrik/logrus/formatter/text_formatter.go
  vendor/github.com/onrik/logrus/sentry/sentry.go
  vendor/github.com/sirupsen/logrus/.gitignore
  vendor/github.com/sirupsen/logrus/.travis.yml
  vendor/github.com/sirupsen/logrus/CHANGELOG.md
  vendor/github.com/sirupsen/logrus/LICENSE
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/alt_exit_test.go
  vendor/github.com/sirupsen/logrus/appveyor.yml
  vendor/github.com/sirupsen/logrus/doc.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/entry_test.go
  vendor/github.com/sirupsen/logrus/example_basic_test.go
  vendor/github.com/sirupsen/logrus/example_hook_test.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/formatter_bench_test.go
  vendor/github.com/sirupsen/logrus/hook_test.go
  vendor/github.com/sirupsen/logrus/hooks.go
  vendor/github.com/sirupsen/logrus/hooks/syslog/README.md
  vendor/github.com/sirupsen/logrus/hooks/syslog/syslog.go
  vendor/github.com/sirupsen/logrus/hooks/syslog/syslog_test.go
  vendor/github.com/sirupsen/logrus/hooks/test/test.go
  vendor/github.com/sirupsen/logrus/hooks/test/test_test.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/json_formatter_test.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logger_bench_test.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/logrus_test.go
  vendor/github.com/sirupsen/logrus/terminal_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_check_appengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/sirupsen/logrus/terminal_linux.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/text_formatter_test.go
  vendor/github.com/sirupsen/logrus/writer.go
Labels: approved, do-not-merge/hold, lgtm, size/XXL

#428 clientset: Fix code which is changed manually
  pkg/client/clientset/versioned/clientset.go
  pkg/trainer/training.go
  pkg/util/k8sutil/k8sutil.go
Labels: approved, lgtm, size/S

#429 format the python files with yapf
  py/deploy.py
  py/release_test.py
  py/util.py
Labels: approved, lgtm, size/M

#344 Create Pod instead of Job
  pkg/trainer/replicas.go
  pkg/trainer/replicas_test.go
  pkg/trainer/training.go
Labels: approved, area/operator, kind/feature, lgtm, size/L

#434 Remove unreachable code
  pkg/trainer/training.go
Labels: approved, lgtm, size/XS

#432 *: Remove type ContainerName
  pkg/apis/tensorflow/helper/helpers.go
  pkg/apis/tensorflow/v1alpha1/types.go
  pkg/apis/tensorflow/validation/validation.go
  pkg/trainer/replicas.go
  pkg/trainer/replicas_test.go
Labels: approved, lgtm, size/S

#408 Add a field SchedulerName to TFJob for specifying a scheduler
  pkg/apis/tensorflow/v1alpha1/types.go
  pkg/trainer/replicas.go
  pkg/trainer/replicas_test.go
  pkg/trainer/training.go
Labels: approved, do-not-merge/hold, lgtm, size/S

#440 change kubeflow.io to kubeflow.org
  README.md
  py/README.md
Labels: approved, lgtm, size/XS

#445 Make local release cross-platform + fix
  py/release.py
  py/util.py
Labels: approved, lgtm, size/S

#446 Add OWNERS file for dashboard
  OWNERS
  dashboard/OWNERS
Labels: approved, lgtm, size/S

#418 Create resources (Services/Jobs) only once
  pkg/trainer/replicas.go
  pkg/trainer/replicas_test.go
  pkg/trainer/training.go
Labels: approved, lgtm, size/M

#454 *: Remove APIExtension clientset
  cmd/tf-operator/app/server.go
  cmd/tf-operator/main.go
  pkg/controller/controller.go
  pkg/util/k8sutil/k8sutil.go
Labels: approved, lgtm, size/M

#457 Update API to v1alpha2
  hack/update-codegen.sh
  pkg/apis/tensorflow/v1alpha2/doc.go
  pkg/apis/tensorflow/v1alpha2/register.go
  pkg/apis/tensorflow/v1alpha2/types.go
  pkg/apis/tensorflow/v1alpha2/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/doc.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/fake/doc.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/fake/fake_kubeflow_client.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/fake/fake_tfjob.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/generated_expansion.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/kubeflow_client.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha2/tfjob.go
  pkg/client/clientset/versioned/typed/tensorflow/v1alpha2/doc.go
  pkg/client/clientset/versioned/typed/tensorflow/v1alpha2/fake/doc.go
  pkg/client/clientset/versioned/typed/tensorflow/v1alpha2/fake/fake_tensorflow_client.go
  pkg/client/clientset/versioned/typed/tensorflow/v1alpha2/fake/fake_tfjob.go
  pkg/client/clientset/versioned/typed/tensorflow/v1alpha2/generated_expansion.go
  pkg/client/clientset/versioned/typed/tensorflow/v1alpha2/tensorflow_client.go
  pkg/client/clientset/versioned/typed/tensorflow/v1alpha2/tfjob.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/kubeflow/interface.go
  pkg/client/informers/externalversions/kubeflow/v1alpha2/interface.go
  pkg/client/informers/externalversions/kubeflow/v1alpha2/tfjob.go
  pkg/client/informers/externalversions/tensorflow/interface.go
  pkg/client/informers/externalversions/tensorflow/v1alpha2/interface.go
  pkg/client/informers/externalversions/tensorflow/v1alpha2/tfjob.go
  pkg/client/listers/kubeflow/v1alpha2/expansion_generated.go
  pkg/client/listers/kubeflow/v1alpha2/tfjob.go
  pkg/client/listers/tensorflow/v1alpha2/expansion_generated.go
  pkg/client/listers/tensorflow/v1alpha2/tfjob.go
Labels: approved, size/XXL

#453 travis: Ignore generated code
  .travis.yml
Labels: approved, lgtm, size/XS

#460 Remove deprecated package retryutil
  pkg/util/retryutil/retry_util.go
Labels: approved, lgtm, size/M

#459 Change test cluster to kubeflow-ci
  test/workflows/components/params.libsonnet
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XS

#462 Fix owners file id
  OWNERS
Labels: approved, lgtm, size/XS

#464 Run ks upgrade
  test/test-app/app.yaml
  test/test-app/environments/default/spec.json
  test/test-app/lib/v1.7.0/k.libsonnet
  test/test-app/lib/v1.7.0/k8s.libsonnet
  test/test-app/lib/v1.7.0/swagger.json
  test/workflows/app.yaml
  test/workflows/environments/releasing/spec.json
  test/workflows/environments/test/spec.json
  test/workflows/lib/v1.7.0/k.libsonnet
  test/workflows/lib/v1.7.0/k8s.libsonnet
  test/workflows/lib/v1.7.0/swagger.json
Labels: approved, lgtm, size/XXL

#468 Append labels instead of rewriting
  pkg/controller/controller_pod.go
Labels: size/XS

#466 linter: Fix linter ignore file
  linter_config.json
  pkg/client/clientset/versioned/typed/tensorflow/v1alpha2/doc.go
  pkg/client/clientset/versioned/typed/tensorflow/v1alpha2/fake/doc.go
  pkg/client/clientset/versioned/typed/tensorflow/v1alpha2/fake/fake_tensorflow_client.go
  pkg/client/clientset/versioned/typed/tensorflow/v1alpha2/fake/fake_tfjob.go
  pkg/client/clientset/versioned/typed/tensorflow/v1alpha2/generated_expansion.go
  pkg/client/clientset/versioned/typed/tensorflow/v1alpha2/tensorflow_client.go
  pkg/client/clientset/versioned/typed/tensorflow/v1alpha2/tfjob.go
  pkg/client/informers/externalversions/tensorflow/interface.go
  pkg/client/informers/externalversions/tensorflow/v1alpha2/interface.go
  pkg/client/informers/externalversions/tensorflow/v1alpha2/tfjob.go
  pkg/client/listers/tensorflow/v1alpha2/expansion_generated.go
  pkg/client/listers/tensorflow/v1alpha2/tfjob.go
Labels: approved, lgtm, size/XL

#474 add LabelsByIndex method to eliminate code duplication
  pkg/trainer/replicas.go
Labels: approved, lgtm, size/S

#452 Create PDB of TFReplicaSet for gang scheduling by kube-arbitrator
  cmd/tf-operator/app/options/options.go
  cmd/tf-operator/app/server.go
  pkg/controller/controller.go
  pkg/trainer/training.go
  pkg/trainer/training_test.go
Labels: approved, lgtm, size/L

#476 controller: Update status in time
  pkg/controller/controller.go
  pkg/controller/controller_pod.go
  pkg/controller/controller_test.go
Labels: approved, lgtm, size/L

#477 *: Fix some errors in Travis CI
  linter_config.json
  pkg/apis/tensorflow/v1alpha2/types.go
  pkg/controller/controller.go
  pkg/controller/controller_pod.go
  pkg/controller/controller_service.go
  pkg/controller/controller_test.go
Labels: approved, lgtm, size/S

#480 controller: Add internal state test
  pkg/controller/controller_pod.go
  pkg/controller/controller_test.go
Labels: approved, lgtm, size/L

#441 Fix dashboard + proxy incompatibility
  dashboard/backend/handler/api_handler.go
  dashboard/backend/main.go
  dashboard/frontend/package.json
  dashboard/frontend/src/components/App.js
  dashboard/frontend/src/services.js
  dashboard/frontend/src/utils.js
Labels: approved, lgtm, size/M

#481 controller: Separate ps and worker pods
  pkg/controller/controller_pod.go
  pkg/controller/controller_service.go
  pkg/controller/controller_test.go
Labels: approved, lgtm, size/M

#465 Fix field selectors in controller
  cmd/tf-operator/app/server.go
  pkg/trainer/replicas.go
Labels: approved, lgtm, size/S

#482 controller: Add check for service and fix service
  pkg/controller/controller_test.go
Labels: approved, lgtm, size/M

#487 Add sleep and random exit image for e2e test
  test/e2e/sleep-and-random-exit/Dockerfile
  test/e2e/sleep-and-random-exit/sleep-and-random-exit.sh
Labels: approved, lgtm, size/S

#471 Use headless services for Training jobs
  pkg/trainer/replicas.go
Labels: approved, lgtm, size/XS

#488 test: Add test cases
  pkg/controller/controller_pod.go
  pkg/controller/controller_pod_test.go
  pkg/controller/controller_service_test.go
  pkg/controller/controller_test.go
Labels: approved, lgtm, size/L

#491 Set restart policy
  pkg/controller/controller_pod.go
Labels: approved, lgtm, needs-rebased, size/XS

#494 Fix env append issue
  pkg/controller/controller_pod.go
Labels: approved, lgtm, needs-rebased, size/XS

#495 Set JSONLogFormat to false by default
  cmd/tf-operator/app/options/options.go
Labels: approved, lgtm, needs-rebased, size/XS

#486 fixed some golint warning
  cmd/tf-operator/app/server.go
  dashboard/backend/client/manager.go
  linter_config.json
  pkg/apis/tensorflow/helper/helpers.go
  pkg/apis/tensorflow/v1alpha1/defaults.go
  pkg/apis/tensorflow/v1alpha1/register.go
  pkg/apis/tensorflow/v1alpha1/types.go
  pkg/apis/tensorflow/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/tensorflow/v1alpha1/zz_generated.defaults.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/fake/fake_kubeflow_client.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/kubeflow_client.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/controller/controller.go
  pkg/trainer/replicas.go
  pkg/trainer/training.go
  pkg/util/k8sutil/k8sutil.go
  pkg/util/util.go
  version/version.go
Labels: approved, lgtm, size/L

#498 release: Fix style
  py/release.py
  py/release_test.py
Labels: approved, lgtm, size/XS

#497 pkg: Fix the code changed in #486
  pkg/apis/tensorflow/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/tensorflow/v1alpha1/zz_generated.defaults.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/fake/fake_kubeflow_client.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/kubeflow_client.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
Labels: approved, size/M

#501 Fix bug with jobs not being marked as completed.
  pkg/controller/controller.go
  pkg/trainer/replicas.go
  pkg/trainer/training.go
  py/test_runner.py
  py/tf_job_client.py
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#504 Add condition logic code
  pkg/apis/tensorflow/v1alpha2/types.go
  pkg/controller/controller.go
  pkg/controller/controller_pod.go
  pkg/controller/controller_test.go
Labels: size/L

#505 test: Fix failed case because of update status
  pkg/controller/controller_pod.go
  pkg/controller/controller_test.go
Labels: approved, lgtm, size/XS

#485 Support testing on minikube.
  py/test_runner.py
  py/util.py
Labels: approved, lgtm, size/S

#506 test: Add test cases for condition
  pkg/controller/controller.go
  pkg/controller/controller_pod.go
  pkg/controller/controller_test.go
Labels: approved, lgtm, size/M

#507 Check running status more gracefully
  pkg/controller/controller_pod.go
  pkg/controller/controller_utils.go
Labels: size/S

#442 Add proxying to front-end development server.
  dashboard/README.md
  dashboard/frontend/package.json
  dashboard/frontend/src/utils.js
Labels: approved, lgtm, size/S

#513 Fix outdated information about GPUs in README
  README.md
Labels: approved, lgtm, size/S

#512 Don't leave pods running when a job completes.
  pkg/trainer/replicas.go
  pkg/trainer/training.go
  py/test_runner.py
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#509 RFC: Add a new command for generating example TFjobs
  hack/genjob/genjob.go
Labels: approved, lgtm, size/L

#511 Fix output on test failure
  pkg/trainer/replicas_test.go
Labels: approved, lgtm, size/XS

#510 Adds gcloudignore
  .gcloudignore
Labels: approved, lgtm, size/XS

#516 update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS
