Repository kubeflow/trainer, pull requests merged in 2018-05, with the labels that each got.

#568 Update test worker image to kubeflow-ci
  examples/gke/test_notebook.py
  py/prow.py
  py/release.py
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/S

#565 add OwnerReferences to pdb
  pkg/trainer/training.go
Labels: approved, lgtm, size/M

#566 chart: Remove
  examples/gke/TF on GKE.ipynb
  py/release.py
  py/release_test.py
  tf-job-operator-chart/Chart.yaml
  tf-job-operator-chart/templates/config.yaml
  tf-job-operator-chart/templates/crd.yaml
  tf-job-operator-chart/templates/dashboard.yaml
  tf-job-operator-chart/templates/deployment.yaml
  tf-job-operator-chart/templates/rbac.yaml
  tf-job-operator-chart/templates/service-account.yaml
  tf-job-operator-chart/templates/tests/basic-test.yaml
  tf-job-operator-chart/values.yaml
Labels: approved, lgtm, size/XXL

#570 Fix missing string for logging placeholder
  py/release.py
Labels: approved, lgtm, size/XS

#571 [v1alpha2]fix bug int to string for index
  pkg/controller.v2/controller_pod.go
Labels: approved, lgtm, size/XS

#572 replace glide with dep in the developer guide
  developer_guide.md
Labels: approved, lgtm, size/XS

#579 .travis.yml: Add failure notification in GitHub
  .travis.yml
Labels: approved, lgtm, size/XS

#549 Add dist mnist model for e2e test
  test/e2e/dist-mnist/Dockerfile
  test/e2e/dist-mnist/README.md
  test/e2e/dist-mnist/dist_mnist.py
Labels: approved, size/L

#581 .pylinrc: Add dist_mnist
  .pylintrc
Labels: approved, lgtm, priority/p0, size/XS

#585 Format go code and fix spelling errors
  dashboard/backend/handler/api_handler.go
  test/e2e/main.go
Labels: approved, lgtm, size/S

#587 Fix the gometalinter support
  .travis.yml
Labels: approved, size/XS

#578 controller_status: Remove pending pods from active pods
  pkg/controller.v2/controller_pod.go
  pkg/controller.v2/controller_status.go
  pkg/controller.v2/controller_test.go
Labels: approved, lgtm, size/S, status/blocked

#583 mnist: Add correponding yaml config
  examples/crd/crd-v1alpha2.yaml
  test/e2e/dist-mnist/README.md
  test/e2e/dist-mnist/tj_job_mnist.yaml
Labels: approved, lgtm, size/M

#592 .travis.yml: Fix cmd errors
  .travis.yml
  cmd/tf-operator.v2/app/server.go
  cmd/tf-operator/app/server.go
  dashboard/backend/handler/api_handler.go
  dashboard/backend/main.go
  test/e2e/main.go
Labels: approved, lgtm, priority/p0, size/M

#595 Add a new command-line argument for release.py
  py/release.py
Labels: approved, lgtm, size/S

#602 Delete the old releaser code which is no longer used.
  build/release/Dockerfile.release
  build/release/Makefile
  build/release/README.md
  build/release/launch_build.sh
  build/release/releaser.yaml
Labels: approved, lgtm, size/L

#601 Add tf-operator.v2 to release.py so that we build a Docker image containing the v1alph2 controller
  build/images/tf_operator/Dockerfile
  py/release.py
Labels: approved, lgtm, size/XS

#604 dist_mnist: Add unused_argv
  test/e2e/dist-mnist/dist_mnist.py
Labels: approved, lgtm, size/XS

#607 TFJob client should not block forever trying to get the namespace object
  py/tf_job_client.py
Labels: approved, lgtm, size/M

#605 crd: Add validation using OpenAPI 3.0
  examples/crd/crd-v1alpha2.yaml
Labels: approved, lgtm, size/S

#603 service: Refactor to the slice structure
  pkg/controller.v2/controller.go
  pkg/controller.v2/controller_pod.go
  pkg/controller.v2/controller_service.go
Labels: approved, lgtm, priority/p1, size/L

#577 api: OpenAPI support
  .travis.yml
  Gopkg.lock
  Gopkg.toml
  hack/update-codegen.sh
  linter_config.json
  pkg/apis/tensorflow/v1alpha2/doc.go
  pkg/apis/tensorflow/v1alpha2/openapi_generated.go
  vendor/k8s.io/code-generator/cmd/openapi-gen/BUILD
  vendor/k8s.io/code-generator/cmd/openapi-gen/README
  vendor/k8s.io/code-generator/cmd/openapi-gen/main.go
  vendor/k8s.io/kube-openapi/OWNERS
  vendor/k8s.io/kube-openapi/code-of-conduct.md
  vendor/k8s.io/kube-openapi/pkg/common/common.go
  vendor/k8s.io/kube-openapi/pkg/generators/README
  vendor/k8s.io/kube-openapi/pkg/generators/openapi.go
  vendor/k8s.io/kube-openapi/pkg/generators/openapi_test.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/document.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/openapi.go
  vendor/k8s.io/kube-openapi/pkg/util/util_test.go
Labels: approved, lgtm, priority/p3, size/XXL
