Repository kubeflow/trainer, pull requests merged in 2018-11, with the labels that each got.

#855 Rename kube-arbitrator to kube-batch.
  cmd/tf-operator.v2/app/options/options.go
  cmd/tf-operator/app/options/options.go
  pkg/controller.v2/jobcontroller/jobcontroller.go
  pkg/trainer/training.go
Labels: approved, lgtm, size/S

#860 Add an example for TF distributed training
  examples/distribution_strategy/Dockerfile
  examples/distribution_strategy/Makefile
  examples/distribution_strategy/README.md
  examples/distribution_strategy/distributed_tfjob.yaml
  examples/distribution_strategy/keras_model_to_estimator.py
Labels: approved, lgtm, size/L

#862 Add an e2etest for running distributed training TFJob
  py/distributed_training_tests.py
  test/workflows/components/distributed_training_v1alpha2.jsonnet
  test/workflows/components/params.libsonnet
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#863 TF operator v1beta1 e2etests
  .travis.yml
  build/images/tf_operator/Dockerfile
  prow_config.yaml
  py/cleanpod_policy_tests.py
  py/deploy.py
  py/distributed_training_tests.py
  py/estimator_runconfig_tests.py
  py/invalid_tfjob_tests.py
  py/release.py
  py/shutdown_policy_tests.py
  py/simple_tfjob_tests.py
  py/test_runner.py
  py/tf_job_client.py
  test/test-app/components/params.libsonnet
  test/test-app/vendor/kubeflow/core/prototypes/all.jsonnet
  test/test-app/vendor/kubeflow/core/prototypes/tf-job-operator.jsonnet
  test/test-app/vendor/kubeflow/core/tf-job-operator.libsonnet
  test/workflows/components/clean_pod_all_v1alpha2.jsonnet
  test/workflows/components/clean_pod_all_v1beta1.jsonnet
  test/workflows/components/clean_pod_none_v1alpha2.jsonnet
  test/workflows/components/clean_pod_none_v1beta1.jsonnet
  test/workflows/components/clean_pod_running_v1alpha2.jsonnet
  test/workflows/components/clean_pod_running_v1beta1.jsonnet
  test/workflows/components/distributed_training_v1beta1.jsonnet
  test/workflows/components/estimator_runconfig_v1alpha2.jsonnet
  test/workflows/components/estimator_runconfig_v1beta1.jsonnet
  test/workflows/components/gpu_tfjob_v1beta1.jsonnet
  test/workflows/components/invalid_tfjob_v1alpha2.jsonnet
  test/workflows/components/invalid_tfjob_v1beta1.jsonnet
  test/workflows/components/master_is_chief_v1beta1.jsonnet
  test/workflows/components/params.libsonnet
  test/workflows/components/simple_tfjob_v1beta1.jsonnet
  test/workflows/components/worker0_is_chief_v1beta1.jsonnet
  test/workflows/components/workflows.libsonnet
  test/workflows/environments/releasing/params.libsonnet
Labels: approved, lgtm, size/XXL

#867 Import jobcontroller from common package
  pkg/controller.v1beta1/tensorflow/controller.go
  pkg/controller.v1beta1/tensorflow/pod.go
  pkg/controller.v1beta1/tensorflow/service.go
  pkg/controller.v1beta1/tensorflow/tensorflow.go
Labels: approved, lgtm, size/XS

#868 Delete v1alpha1 API and controller
  .travis.yml
  build/images/tf_operator/Dockerfile
  cmd/tf-operator/app/options/options.go
  cmd/tf-operator/app/server.go
  cmd/tf-operator/main.go
  hack/genjob/genjob.go
  hack/update-codegen.sh
  linter_config.json
  pkg/apis/tensorflow/helper/helpers.go
  pkg/apis/tensorflow/helper/helpers_test.go
  pkg/apis/tensorflow/v1alpha1/defaults.go
  pkg/apis/tensorflow/v1alpha1/defaults_test.go
  pkg/apis/tensorflow/v1alpha1/doc.go
  pkg/apis/tensorflow/v1alpha1/register.go
  pkg/apis/tensorflow/v1alpha1/types.go
  pkg/apis/tensorflow/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/tensorflow/v1alpha1/zz_generated.defaults.go
  pkg/apis/tensorflow/validation/validation.go
  pkg/apis/tensorflow/validation/validation_test.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/fake/fake_kubeflow_client.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/fake/fake_tfjob.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/kubeflow_client.go
  pkg/client/clientset/versioned/typed/kubeflow/v1alpha1/tfjob.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/kubeflow/interface.go
  pkg/client/informers/externalversions/kubeflow/v1alpha1/interface.go
  pkg/client/informers/externalversions/kubeflow/v1alpha1/tfjob.go
  pkg/client/listers/kubeflow/v1alpha1/expansion_generated.go
  pkg/client/listers/kubeflow/v1alpha1/tfjob.go
  pkg/controller/controller.go
  pkg/trainer/labels.go
  pkg/trainer/replicas.go
  pkg/trainer/replicas_test.go
  pkg/trainer/training.go
  pkg/trainer/training_test.go
  py/release.py
  test/e2e/main.go
Labels: approved, size/XXL

#870 Update tf-operator v1beta1 documentation and examples
  developer_guide.md
  examples/crd/crd-v1beta1.yaml
  examples/crd/crd.yaml
  examples/distribution_strategy/distributed_tfjob.yaml
  examples/tf_job.yaml
  examples/tf_job_clean_policy.yaml
  examples/tf_job_defaults.yaml
  examples/tf_job_gpu.yaml
  examples/v1beta1/dist-mnist/Dockerfile
  examples/v1beta1/dist-mnist/README.md
  examples/v1beta1/dist-mnist/dist_mnist.py
  examples/v1beta1/dist-mnist/tf_job_mnist.yaml
Labels: approved, lgtm, size/XL

#874 Upgrade k8s dependency to 1.10.1
  Gopkg.lock
  Gopkg.toml
Labels: approved, lgtm, size/L

#878 Fix typo in developer_guide.md
  developer_guide.md
Labels: approved, lgtm, ok-to-test, size/XS

#873 Add an e2etest for testing restart policy
  py/build_and_push_image.py
  py/cleanpod_policy_tests.py
  py/deploy.py
  py/distributed_training_tests.py
  py/estimator_runconfig_tests.py
  py/invalid_tfjob_tests.py
  py/k8s_util.py
  py/ks_util.py
  py/py_checks.py
  py/release.py
  py/release_test.py
  py/replica_restart_policy_tests.py
  py/shutdown_policy_tests.py
  py/simple_tfjob_tests.py
  py/test_runner.py
  py/tf_job_client.py
  py/util.py
  test/workflows/components/params.libsonnet
  test/workflows/components/replica_restart_policy_always_v1alpha2.jsonnet
  test/workflows/components/replica_restart_policy_always_v1beta1.jsonnet
  test/workflows/components/replica_restart_policy_exitcode_v1alpha2.jsonnet
  test/workflows/components/replica_restart_policy_exitcode_v1beta1.jsonnet
  test/workflows/components/replica_restart_policy_never_v1alpha2.jsonnet
  test/workflows/components/replica_restart_policy_never_v1beta1.jsonnet
  test/workflows/components/replica_restart_policy_onfailure_v1alpha2.jsonnet
  test/workflows/components/replica_restart_policy_onfailure_v1beta1.jsonnet
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XXL
