Repository kubeflow/trainer, pull requests merged in 2019-12, with the labels that each got.

#1103 Generate TFJob Python SDK
  .gitignore
  .pylintrc
  examples/sdk/tfjob-sdk.ipynb
  hack/python-sdk/gen-sdk.sh
  hack/python-sdk/main.go
  hack/python-sdk/swagger_config.json
  pkg/apis/tensorflow/v1/swagger.json
  py/kubeflow/tf_operator/deploy.py
  sdk/python/.gitignore
  sdk/python/OWNERS
  sdk/python/README.md
  sdk/python/docs/TFJobClient.md
  sdk/python/docs/V1JobCondition.md
  sdk/python/docs/V1JobStatus.md
  sdk/python/docs/V1ReplicaSpec.md
  sdk/python/docs/V1ReplicaStatus.md
  sdk/python/docs/V1TFJob.md
  sdk/python/docs/V1TFJobList.md
  sdk/python/docs/V1TFJobSpec.md
  sdk/python/docs/V1Time.md
  sdk/python/kubeflow/__init__.py
  sdk/python/kubeflow/tfjob/__init__.py
  sdk/python/kubeflow/tfjob/api/__init__.py
  sdk/python/kubeflow/tfjob/api/tf_job_client.py
  sdk/python/kubeflow/tfjob/api_client.py
  sdk/python/kubeflow/tfjob/configuration.py
  sdk/python/kubeflow/tfjob/constants/__init__.py
  sdk/python/kubeflow/tfjob/constants/constants.py
  sdk/python/kubeflow/tfjob/models/__init__.py
  sdk/python/kubeflow/tfjob/models/v1_job_condition.py
  sdk/python/kubeflow/tfjob/models/v1_job_status.py
  sdk/python/kubeflow/tfjob/models/v1_replica_spec.py
  sdk/python/kubeflow/tfjob/models/v1_replica_status.py
  sdk/python/kubeflow/tfjob/models/v1_tf_job.py
  sdk/python/kubeflow/tfjob/models/v1_tf_job_list.py
  sdk/python/kubeflow/tfjob/models/v1_tf_job_spec.py
  sdk/python/kubeflow/tfjob/models/v1_time.py
  sdk/python/kubeflow/tfjob/rest.py
  sdk/python/kubeflow/tfjob/utils/__init__.py
  sdk/python/kubeflow/tfjob/utils/utils.py
  sdk/python/requirements.txt
  sdk/python/setup.py
  sdk/python/test/__init__.py
  sdk/python/test/test_e2e.py
  sdk/python/test/test_v1_job_condition.py
  sdk/python/test/test_v1_job_status.py
  sdk/python/test/test_v1_replica_spec.py
  sdk/python/test/test_v1_replica_status.py
  sdk/python/test/test_v1_tf_job.py
  sdk/python/test/test_v1_tf_job_list.py
  sdk/python/test/test_v1_tf_job_spec.py
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XXL

#1114 Enhance tfjobs sdk docs
  hack/python-sdk/gen-sdk.sh
  sdk/python/README.md
  sdk/python/examples/kubeflow-tfjob-sdk.ipynb
Labels: approved, lgtm, size/XS

#1111 fix the reconcile flow
  pkg/controller.v1/tensorflow/controller.go
Labels: approved, lgtm, size/L

#1116 Add more APIs for TFJob done
  prow_config.yaml
  sdk/python/README.md
  sdk/python/docs/TFJobClient.md
  sdk/python/examples/kubeflow-tfjob-sdk.ipynb
  sdk/python/kubeflow/tfjob/api/tf_job_client.py
  sdk/python/kubeflow/tfjob/constants/constants.py
  sdk/python/setup.py
  sdk/python/test/test_e2e.py
Labels: approved, lgtm, size/XL

#1117 Update checking status API name
  sdk/python/README.md
  sdk/python/docs/TFJobClient.md
  sdk/python/examples/kubeflow-tfjob-sdk.ipynb
  sdk/python/kubeflow/tfjob/api/tf_job_client.py
  sdk/python/test/test_e2e.py
Labels: approved, lgtm, size/S

#1118 fix(ConvertTFJobToUnstructured): ConvertTFJobToUnstructured uses function ToUnstructured to convert TFJob to Unstructured
  pkg/common/util/v1/testutil/util.go
Labels: approved, lgtm, ok-to-test, size/S

#1119 remove tfjob dashboard
  .gitignore
  .travis.yml
  build/images/tf_operator/Dockerfile
  dashboard/OWNERS
  dashboard/README.md
  dashboard/backend/client/manager.go
  dashboard/backend/handler/api_handler.go
  dashboard/backend/main.go
  dashboard/frontend/.eslintrc.json
  dashboard/frontend/README.md
  dashboard/frontend/package.json
  dashboard/frontend/public/favicon.ico
  dashboard/frontend/public/index.html
  dashboard/frontend/src/components/App.css
  dashboard/frontend/src/components/App.js
  dashboard/frontend/src/components/App.test.js
  dashboard/frontend/src/components/AppBar.js
  dashboard/frontend/src/components/CreateJob.js
  dashboard/frontend/src/components/CreateReplicaSpec.js
  dashboard/frontend/src/components/EnvVar.js
  dashboard/frontend/src/components/EnvVarCreator.js
  dashboard/frontend/src/components/Home.js
  dashboard/frontend/src/components/InfoEntry.js
  dashboard/frontend/src/components/Job.js
  dashboard/frontend/src/components/JobDetail.js
  dashboard/frontend/src/components/JobList.js
  dashboard/frontend/src/components/JobSummary.js
  dashboard/frontend/src/components/PodList.js
  dashboard/frontend/src/components/ReplicaSpec.js
  dashboard/frontend/src/components/RequiredTextField.js
  dashboard/frontend/src/components/Volume.js
  dashboard/frontend/src/components/VolumeCreator.js
  dashboard/frontend/src/index.js
  dashboard/frontend/src/registerServiceWorker.js
  dashboard/frontend/src/services.js
  dashboard/frontend/src/utils.js
  dashboard/frontend/yarn.lock
  prow_config.yaml
  py/kubeflow/tf_operator/py_checks.py
  py/kubeflow/tf_operator/release.py
  test/test-app/vendor/kubeflow/core@f7a68336ad7a65c2cbba8462e89d24a10626687e/tf-job-operator.libsonnet
Labels: approved, lgtm, size/XXL
