Repository kubeflow/trainer, pull requests merged in 2019-04, with the labels that each got.

#973 Issue Label Bot Alias Yaml
  .github/issue_label_bot.yaml
Labels: approved, lgtm, size/XS

#977 enhance tfjob validation error message
  pkg/apis/tensorflow/validation/validation.go
Labels: approved, lgtm, size/M

#978 Fix incorrect event message for PodGroup deletion
  pkg/controller.v1beta2/tensorflow/controller.go
Labels: approved, lgtm, size/XS

#974 Fix ineffassign error in masterRole assignment
  pkg/controller.v1beta2/tensorflow/pod.go
Labels: approved, lgtm, size/XS

#981 modify dockerfile for ppc64le
  build/images/tf_operator/Dockerfile
Labels: approved, lgtm, needs-ok-to-test, size/XS

#979 Update func name to pastBackoffLimit in comment
  pkg/controller.v1beta2/tensorflow/controller.go
Labels: approved, lgtm, size/XS
