Repository kubeflow/trainer, pull requests merged in 2019-01, with the labels that each got.

#897 Don't reinitialize replica statuses after TFJob completes
  pkg/controller.v1beta1/tensorflow/controller.go
Labels: approved, lgtm, size/S

#909 Add evaluator to E2E test.
  py/estimator_runconfig_tests.py
  test/workflows/components/estimator_runconfig_v1alpha2.jsonnet
  test/workflows/components/estimator_runconfig_v1beta1.jsonnet
Labels: approved, lgtm, size/M

#912 Add .swp to gitignore.
  .gitignore
Labels: approved, lgtm, size/XS

#911 Verify pod names.
  py/pod_names_validation_tests.py
  py/tf_job_client.py
  test/workflows/components/params.libsonnet
  test/workflows/components/pod_names_validation_v1alpha2.jsonnet
  test/workflows/components/pod_names_validation_v1beta1.jsonnet
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#919 Remove gosimple, go 1.8 and add gotype
  .travis.yml
  cmd/tf-operator.v1beta1/app/server.go
  cmd/tf-operator.v2/app/server.go
  linter_config.json
  pkg/apis/tensorflow/v1alpha2/defaults.go
  pkg/apis/tensorflow/v1beta1/defaults.go
  pkg/apis/tensorflow/validation/validation.go
  pkg/control/service_control.go
  pkg/control/service_ref_manager_test.go
  pkg/controller.v1beta1/tensorflow/controller.go
  pkg/controller.v1beta1/tensorflow/informer.go
  pkg/controller.v1beta1/tensorflow/pod.go
  pkg/controller.v1beta1/tensorflow/service.go
  pkg/controller.v1beta1/tensorflow/util.go
  pkg/controller.v2/tensorflow/controller.go
  pkg/controller.v2/tensorflow/informer.go
  pkg/controller.v2/tensorflow/pod.go
  pkg/controller.v2/tensorflow/service.go
  pkg/controller.v2/tensorflow/util.go
  pkg/util/k8sutil/k8sutil.go
Labels: approved, lgtm, size/M

#917 Update backend apiVersion to v1beta1 to fix tfjob list.
  dashboard/backend/handler/api_handler.go
Labels: approved, lgtm, size/S

#918 fix wrong var used of wait_for_condition method
  py/tf_job_client.py
Labels: approved, lgtm, size/XS
