Repository kubeflow/trainer, pull requests merged in 2019-09, with the labels that each got.

#1074 Updating issue bot configs
  .github/issue_label_bot.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#1081 feat: Replace gometalinter with golangci-lint
  .travis.yml
  linter_config.json
  pkg/controller.v1/tensorflow/job_test.go
  pkg/controller.v1/tensorflow/pod_test.go
  pkg/controller.v1/tensorflow/service_test.go
Labels: approved, lgtm, size/M

#1080 feat: Do not set TF_CONFIG for local training
  pkg/controller.v1/tensorflow/pod.go
  pkg/controller.v1/tensorflow/pod_test.go
Labels: approved, lgtm, size/L

#1084 add ppc64le support for the example dist-mnist
  examples/v1/dist-mnist/Dockerfile.ppc64le
  examples/v1/dist-mnist/README.md
Labels: approved, lgtm, ok-to-test, size/S

#1072 use multi-stage build to build tf-operator image
  .gcloudignore
  build/images/tf_operator/Dockerfile
  py/kubeflow/tf_operator/release.py
Labels: approved, lgtm, ok-to-test, size/S

#1082 Support for ppc64le
  py/kubeflow/tf_operator/util.py
Labels: approved, lgtm, ok-to-test, size/XS
