Repository kubeflow/trainer, pull requests merged in 2019-08, with the labels that each got.

#1055 add total suffix in counter metrics
  docs/monitoring/README.md
  pkg/controller.v1/tensorflow/controller.go
  pkg/controller.v1/tensorflow/job.go
  pkg/controller.v1/tensorflow/status.go
  pkg/controller.v1beta2/tensorflow/job.go
Labels: approved, lgtm, ok-to-test, size/S

#1051 Avoid unnecessary update when tfjob is complete
  pkg/controller.v1/tensorflow/controller.go
  pkg/controller.v1/tensorflow/status.go
  pkg/controller.v1beta2/tensorflow/controller.go
  pkg/controller.v1beta2/tensorflow/status.go
Labels: approved, lgtm, size/M

#1063 Add qps and burst options
  cmd/tf-operator.v1/app/options/options.go
  cmd/tf-operator.v1/app/server.go
  cmd/tf-operator.v1beta2/app/options/options.go
  cmd/tf-operator.v1beta2/app/server.go
Labels: approved, lgtm, size/M

#1064 Renaming labels to common types
  dashboard/backend/handler/api_handler.go
  pkg/common/jobcontroller/jobcontroller.go
  pkg/common/util/v1/testutil/util.go
  pkg/common/util/v1beta2/testutil/util.go
  pkg/controller.v1/tensorflow/controller.go
  pkg/controller.v1/tensorflow/controller_test.go
  pkg/controller.v1/tensorflow/pod.go
  pkg/controller.v1/tensorflow/util_test.go
  pkg/controller.v1beta2/tensorflow/controller.go
  pkg/controller.v1beta2/tensorflow/controller_test.go
  pkg/controller.v1beta2/tensorflow/pod.go
  pkg/controller.v1beta2/tensorflow/util_test.go
  py/kubeflow/tf_operator/tf_job_client.py
Labels: approved, lgtm, size/M

#1062 rewrite dockerfile
  build/images/tf_operator/Dockerfile
Labels: approved, lgtm, ok-to-test, size/S

#1067 Add controller-name label for Pod and service
  cmd/tf-operator.v1/app/options/options.go
  cmd/tf-operator.v1/app/server.go
  cmd/tf-operator.v1beta2/app/options/options.go
  cmd/tf-operator.v1beta2/app/server.go
  dashboard/backend/handler/api_handler.go
  pkg/apis/common/v1/types.go
  pkg/apis/common/v1beta2/types.go
  pkg/apis/tensorflow/v1/defaults.go
  pkg/apis/tensorflow/v1/defaults_test.go
  pkg/apis/tensorflow/v1beta2/defaults.go
  pkg/apis/tensorflow/v1beta2/defaults_test.go
  pkg/apis/tensorflow/validation/validation_test.go
  pkg/common/jobcontroller/jobcontroller.go
  pkg/common/jobcontroller/pod.go
  pkg/common/jobcontroller/service.go
  pkg/common/util/v1/testutil/pod.go
  pkg/common/util/v1/testutil/service.go
  pkg/common/util/v1/testutil/tfjob.go
  pkg/common/util/v1/testutil/util.go
  pkg/common/util/v1beta2/testutil/pod.go
  pkg/common/util/v1beta2/testutil/service.go
  pkg/common/util/v1beta2/testutil/tfjob.go
  pkg/common/util/v1beta2/testutil/util.go
  pkg/control/pod_control.go
  pkg/control/pod_control_test.go
  pkg/control/service_control.go
  pkg/control/service_control_test.go
  pkg/control/service_ref_manager.go
  pkg/control/service_ref_manager_test.go
  pkg/controller.v1/tensorflow/controller.go
  pkg/controller.v1/tensorflow/controller_test.go
  pkg/controller.v1/tensorflow/job.go
  pkg/controller.v1/tensorflow/pod_test.go
  pkg/controller.v1/tensorflow/service.go
  pkg/controller.v1/tensorflow/service_test.go
  pkg/controller.v1/tensorflow/status_test.go
  pkg/controller.v1/tensorflow/util_test.go
  pkg/controller.v1beta2/tensorflow/controller.go
  pkg/controller.v1beta2/tensorflow/controller_test.go
  pkg/controller.v1beta2/tensorflow/job.go
  pkg/controller.v1beta2/tensorflow/pod_test.go
  pkg/controller.v1beta2/tensorflow/service.go
  pkg/controller.v1beta2/tensorflow/service_test.go
  pkg/controller.v1beta2/tensorflow/status_test.go
  pkg/controller.v1beta2/tensorflow/util_test.go
  pkg/logger/logger.go
  pkg/util/k8sutil/k8sutil.go
Labels: approved, lgtm, size/L

#1069 Update codegen
  pkg/apis/common/v1/openapi_generated.go
  pkg/apis/common/v1beta2/openapi_generated.go
  pkg/apis/tensorflow/v1/openapi_generated.go
  pkg/apis/tensorflow/v1beta2/openapi_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/controller.v1/tensorflow/controller.go
  pkg/controller.v1beta2/tensorflow/controller.go
Labels: approved, lgtm, ok-to-test, size/XL

#1071 Set tfjob defaults in test utils
  pkg/common/util/v1/testutil/tfjob.go
  pkg/common/util/v1beta2/testutil/tfjob.go
Labels: approved, lgtm, ok-to-test, size/XS

#1070 Add verify-codegen in travis CI
  .travis.yml
Labels: approved, lgtm, ok-to-test, size/XS

#1050 feat(pod): Support custom gang scheduler via CLI argument
  cmd/tf-operator.v1/app/options/options.go
  cmd/tf-operator.v1beta2/app/options/options.go
  pkg/common/jobcontroller/jobcontroller.go
  pkg/controller.v1/tensorflow/controller.go
  pkg/controller.v1/tensorflow/controller_test.go
  pkg/controller.v1/tensorflow/pod.go
  pkg/controller.v1beta2/tensorflow/controller.go
  pkg/controller.v1beta2/tensorflow/controller_test.go
  pkg/controller.v1beta2/tensorflow/pod.go
Labels: approved, lgtm, size/L

#1073 Fix example Mnist With Summaries
  examples/v1/mnist_with_summaries/tf_job_mnist.yaml
  examples/v1beta2/mnist_with_summaries/tf_job_mnist.yaml
Labels: approved, lgtm, size/XS

#1052 add ldflag verion
  py/kubeflow/tf_operator/release.py
Labels: approved, lgtm, ok-to-test, size/XS
