Repository kubeflow/trainer, pull requests merged in 2019-05, with the labels that each got.

#983 Remove trailing spaces in distributed_tfjob.yaml
  examples/distribution_strategy/distributed_tfjob.yaml
Labels: approved, lgtm, size/XS

#986 Prune tf-operator OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#992 Revert "Fix ineffassign error in masterRole assignment"
  pkg/controller.v1beta2/tensorflow/pod.go
Labels: approved, lgtm, size/XS

#995 set CompletionTime first when tfjob exceeds limit
  pkg/controller.v1beta2/tensorflow/controller.go
Labels: approved, lgtm, size/S

#998 fix repeat delete service and pod
  pkg/control/pod_control.go
  pkg/control/service_control.go
Labels: approved, lgtm, size/S

#1007 Remove deprecated field
  examples/crd/crd-v1.yaml
Labels: approved, lgtm, size/S

#1008 Scope presubmits by version
  prow_config.yaml
Labels: approved, lgtm, size/M

#1005 Corrects Dev Guide with up to date paths
  developer_guide.md
  py/kubeflow/tf_operator/Pipfile
  py/kubeflow/tf_operator/Pipfile.lock
  py/kubeflow/tf_operator/release.py
Labels: approved, lgtm, ok-to-test, size/L

#1009 Polish documentation for TFJob V1
  docs/quick-start-v1.md
  pkg/apis/common/v1/openapi_generated.go
  pkg/apis/common/v1/types.go
  pkg/apis/tensorflow/v1/openapi_generated.go
  pkg/apis/tensorflow/v1/types.go
Labels: approved, lgtm, size/L

#982 status: Avoid setting last transition time
  pkg/controller.v1/tensorflow/status.go
  pkg/controller.v1beta2/tensorflow/status.go
Labels: approved, lgtm, size/S

#1006 Fix panic as pod is nil
  pkg/common/jobcontroller/pod.go
Labels: approved, lgtm, size/XS

#1001 fix set startTime logic
  pkg/controller.v1/tensorflow/status.go
  pkg/controller.v1beta2/tensorflow/status.go
Labels: approved, lgtm, size/XS

#1015 do not ignore DeletedFinalStateUnknown event when delete pod
  pkg/common/jobcontroller/pod.go
Labels: approved, lgtm, size/XS

#1012 fix sync PodGroup logic
  pkg/common/jobcontroller/jobcontroller.go
  pkg/controller.v1/tensorflow/controller.go
  pkg/controller.v1beta2/tensorflow/controller.go
Labels: approved, lgtm, size/M

#1014 Add pending status for pastBackoffLimitOnFailure
  pkg/controller.v1/tensorflow/controller.go
  pkg/controller.v1beta2/tensorflow/controller.go
Labels: approved, lgtm, size/M

#1017 Add wackxu as reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#1013 make resyncPeriod configurable
  cmd/tf-operator.v1/app/options/options.go
  cmd/tf-operator.v1/app/server.go
Labels: approved, lgtm, size/S

#1020 Add uuid to id for leader election
  Gopkg.lock
  cmd/tf-operator.v1/app/server.go
  vendor/github.com/google/uuid/CONTRIBUTORS
  vendor/github.com/google/uuid/LICENSE
  vendor/github.com/google/uuid/dce.go
  vendor/github.com/google/uuid/doc.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/util.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version1.go
  vendor/github.com/google/uuid/version4.go
  vendor/github.com/pborman/uuid/CONTRIBUTORS
  vendor/github.com/pborman/uuid/LICENSE
  vendor/github.com/pborman/uuid/dce.go
  vendor/github.com/pborman/uuid/doc.go
  vendor/github.com/pborman/uuid/hash.go
  vendor/github.com/pborman/uuid/marshal.go
  vendor/github.com/pborman/uuid/node.go
  vendor/github.com/pborman/uuid/sql.go
  vendor/github.com/pborman/uuid/time.go
  vendor/github.com/pborman/uuid/util.go
  vendor/github.com/pborman/uuid/uuid.go
  vendor/github.com/pborman/uuid/version1.go
  vendor/github.com/pborman/uuid/version4.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/helpers.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/generated_expansion.go
  vendor/k8s.io/apimachinery/pkg/util/uuid/uuid.go
Labels: approved, lgtm, ok-to-test, size/XXL
