Repository kubeflow/trainer, pull requests merged in 2019-02, with the labels that each got.

#930 Removing PDB check for Min available replicas
  pkg/common/jobcontroller/jobcontroller.go
  pkg/controller.v1beta1/tensorflow/controller_test.go
Labels: approved, lgtm, size/S

#939 Add status subresource to CRD; use UpdateStatus
  pkg/apis/tensorflow/v1beta2/types.go
  pkg/client/clientset/versioned/typed/kubeflow/v1beta2/fake/fake_tfjob.go
  pkg/client/clientset/versioned/typed/kubeflow/v1beta2/tfjob.go
  pkg/controller.v1beta2/tensorflow/controller_test.go
  pkg/controller.v1beta2/tensorflow/job.go
  pkg/controller.v1beta2/tensorflow/status.go
  pkg/util/k8sutil/client.go
  test/test-app/components/core.jsonnet
  test/test-app/vendor/kubeflow/core/prototypes/tf-job-operator.jsonnet
  test/test-app/vendor/kubeflow/core/tf-job-operator.libsonnet
Labels: approved, lgtm, size/M

#943 Support multiple CRD versions for TFJob
  py/deploy.py
  test/test-app/components/params.libsonnet
  test/test-app/vendor/kubeflow/core/prototypes/all.jsonnet
  test/test-app/vendor/kubeflow/core/prototypes/tf-job-operator.jsonnet
  test/test-app/vendor/kubeflow/core/tf-job-operator.libsonnet
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#936 Replace kube-arbitrator with kube-batch
  cmd/tf-operator.v1beta2/app/options/options.go
Labels: approved, lgtm, size/XS

#945 renaming top level python package (issue #914)
  py/kubeflow/__init__.py
  py/kubeflow/tf_operator/Pipfile
  py/kubeflow/tf_operator/Pipfile.lock
  py/kubeflow/tf_operator/README.md
  py/kubeflow/tf_operator/__init__.py
  py/kubeflow/tf_operator/build_and_push_image.py
  py/kubeflow/tf_operator/cleanpod_policy_tests.py
  py/kubeflow/tf_operator/deploy.py
  py/kubeflow/tf_operator/distributed_training_tests.py
  py/kubeflow/tf_operator/estimator_runconfig_tests.py
  py/kubeflow/tf_operator/invalid_tfjob_tests.py
  py/kubeflow/tf_operator/k8s_util.py
  py/kubeflow/tf_operator/pod_names_validation_tests.py
  py/kubeflow/tf_operator/prow.py
  py/kubeflow/tf_operator/prow_test.py
  py/kubeflow/tf_operator/py_checks.py
  py/kubeflow/tf_operator/release.py
  py/kubeflow/tf_operator/release_test.py
  py/kubeflow/tf_operator/replica_restart_policy_tests.py
  py/kubeflow/tf_operator/shutdown_policy_tests.py
  py/kubeflow/tf_operator/simple_tfjob_tests.py
  py/kubeflow/tf_operator/test_runner.py
  py/kubeflow/tf_operator/test_util.py
  py/kubeflow/tf_operator/test_util_test.py
  py/kubeflow/tf_operator/tf_job_client.py
  py/kubeflow/tf_operator/util.py
  py/kubeflow/tf_operator/util_test.py
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L
