Repository kubeflow/trainer, pull requests merged in 2019-07, with the labels that each got.

#1040 update release script
  submit_release_job.sh
  test/workflows/app.yaml
  test/workflows/environments/releasing/params.libsonnet
  test/workflows/environments/test/globals.libsonnet
  test/workflows/environments/test/main.jsonnet
  test/workflows/environments/test/params.libsonnet
  test/workflows/lib/ksonnet-lib/v1.11.10/k.libsonnet
  test/workflows/lib/ksonnet-lib/v1.11.10/k8s.libsonnet
  test/workflows/lib/ksonnet-lib/v1.11.10/swagger.json
Labels: approved, lgtm, size/XXL

#1034 refactor: add GenPodGroupName method to extract podGroupName in diffe…
  pkg/common/jobcontroller/jobcontroller.go
  pkg/common/jobcontroller/util.go
  pkg/controller.v1/tensorflow/pod.go
Labels: approved, lgtm, ok-to-test, size/S

#1036 Removing unnecessary Rbac authorization
  test/test-app/vendor/kubeflow/core@f7a68336ad7a65c2cbba8462e89d24a10626687e/tf-job-operator.libsonnet
Labels: approved, lgtm, size/L

#1038 fix(docs): Fix link for simple_TFJob_test
  e2e_testing.md
Labels: approved, lgtm, size/XS

#1042 Set worker 0 completed if pod's phase goto succeeded
  pkg/controller.v1/tensorflow/pod.go
  pkg/controller.v1beta2/tensorflow/pod.go
Labels: approved, lgtm, size/XS

#1037 Minor fix to add CoreV1 to scheme
  cmd/tf-operator.v1/app/server.go
Labels: approved, lgtm, size/XS

#1044 fix(UI): show correct namespace and name when deleting job through dashboard
  dashboard/frontend/src/components/AppBar.js
Labels: approved, lgtm, ok-to-test, size/XS

#1047 Easily detect the GOPATH in current development environment.
  developer_guide.md
Labels: approved, lgtm, ok-to-test, size/XS

#1046 fix bug: When executing `tf-operator.v1 -version`, GitSHA is always 'not provided'
  py/kubeflow/tf_operator/release.py
Labels: approved, lgtm, ok-to-test, size/XS

#1049 add flag kubeconfig
  cmd/tf-operator.v1/app/options/options.go
  cmd/tf-operator.v1beta2/app/options/options.go
Labels: approved, lgtm, ok-to-test, size/XS
