Repository kubeflow/trainer, pull requests merged in 2020-12, with the labels that each got.

#1198 bugfix for multi_worker_strategy-with-keras.py
  examples/v1/distribution_strategy/keras-API/multi_worker_strategy-with-keras.py
Labels: approved, lgtm, size/XS

#1199 chore: Refactor cmd
  cmd/tf-operator.v1/app/server.go
  cmd/tf-operator.v1/main.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1196 feat: Add CD using GitHub Actions
  .github/workflows/publish.yaml
Labels: approved, lgtm, size/M

#1201 chore: Remove the kanban update workflow
  .github/workflows/triage_issues.yaml
Labels: approved, lgtm, size/S

#1203 fix: Fix the log message
  pkg/controller.v1/tensorflow/status.go
  py/kubeflow/tf_operator/tf_job_client.py
  vendor/github.com/kubeflow/common/pkg/util/logger.go
Labels: approved, lgtm, size/M

#1207 checkCRDExists func return true when k8s cluster is not connected
  cmd/tf-operator.v1/app/server.go
Labels: approved, lgtm, size/XS
