Repository kubeflow/trainer, pull requests merged in 2020-03, with the labels that each got.

#1137 fix comment, add +optional flag to comment.
  Gopkg.lock
  pkg/apis/tensorflow/v1/openapi_generated.go
  pkg/apis/tensorflow/v1/types.go
Labels: approved, lgtm, ok-to-test, size/L

#1120 fix(controller): calculate satisfied with && instead of ||
  pkg/controller.v1/tensorflow/controller.go
Labels: approved, lgtm, ok-to-test, size/XS

#1140 docs: Add roadmap
  docs/roadmap.md
Labels: approved, lgtm, size/S

#1143 Fix sdk test issue that's caused by kubenertes Client bug.
  sdk/python/requirements.txt
  sdk/python/setup.py
Labels: approved, lgtm, size/XS

#1145 Remove unused function arg
  pkg/common/util/v1/testutil/pod.go
  pkg/controller.v1/tensorflow/pod_test.go
  pkg/controller.v1/tensorflow/status_test.go
Labels: approved, lgtm, ok-to-test, size/M

#1147 OWNERS: Add ChanYiLin as approver
  OWNERS
Labels: approved, lgtm, size/XS

#1148 Disable istio sidecar injection in simple tfjob test
  test/workflows/components/simple_tfjob_v1.jsonnet
Labels: approved, lgtm, size/S

#1146 Fix evaluator runconfig
  pkg/controller.v1/tensorflow/pod_test.go
  pkg/controller.v1/tensorflow/tensorflow.go
  py/kubeflow/tf_operator/estimator_runconfig_tests.py
Labels: approved, lgtm, size/M
