Repository kubeflow/trainer, pull requests merged in 2020-01, with the labels that each got.

#1122 Add watch function for TFJob python Client API
  pkg/apis/tensorflow/v1/openapi_generated.go
  pkg/apis/tensorflow/v1/types.go
  pkg/apis/tensorflow/v1/zz_generated.deepcopy.go
  pkg/apis/tensorflow/v1/zz_generated.defaults.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/tensorflow/v1/doc.go
  pkg/client/clientset/versioned/typed/tensorflow/v1/fake/doc.go
  pkg/client/clientset/versioned/typed/tensorflow/v1/fake/fake_tensorflow_client.go
  pkg/client/clientset/versioned/typed/tensorflow/v1/fake/fake_tfjob.go
  pkg/client/clientset/versioned/typed/tensorflow/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/tensorflow/v1/tensorflow_client.go
  pkg/client/clientset/versioned/typed/tensorflow/v1/tfjob.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/tensorflow/interface.go
  pkg/client/informers/externalversions/tensorflow/v1/interface.go
  pkg/client/informers/externalversions/tensorflow/v1/tfjob.go
  pkg/client/listers/tensorflow/v1/expansion_generated.go
  pkg/client/listers/tensorflow/v1/tfjob.go
  sdk/python/docs/TFJobClient.md
  sdk/python/examples/kubeflow-tfjob-sdk.ipynb
  sdk/python/kubeflow/tfjob/api/tf_job_client.py
  sdk/python/kubeflow/tfjob/api/tf_job_watch.py
  sdk/python/requirements.txt
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#1127 Add third party licenses
  build/images/tf_operator/Dockerfile
  py/kubeflow/tf_operator/release.py
  third_party/library/license.txt
  third_party_licenses/additional_license_info.csv
  third_party_licenses/dep.txt
  third_party_licenses/dep_repo.manual.csv
  third_party_licenses/license_info.csv
  third_party_licenses/repo.txt
Labels: approved, lgtm, size/XXL

#1128 Copy third party vendor source code to Docker image
  build/images/tf_operator/Dockerfile
  py/kubeflow/tf_operator/deploy.py
Labels: approved, lgtm, size/XS

#1130 SDK support getting the TFJob training logs
  sdk/python/README.md
  sdk/python/docs/TFJobClient.md
  sdk/python/examples/kubeflow-tfjob-sdk.ipynb
  sdk/python/kubeflow/tfjob/api/tf_job_client.py
  sdk/python/kubeflow/tfjob/constants/constants.py
  sdk/python/kubeflow/tfjob/utils/utils.py
  sdk/python/setup.py
  sdk/python/test/test_e2e.py
Labels: approved, lgtm, size/L

#1124 Distroless image for TF operator
  build/images/tf_operator/Dockerfile
  test/test-app/vendor/kubeflow/core@f7a68336ad7a65c2cbba8462e89d24a10626687e/tf-job-operator.libsonnet
Labels: approved, lgtm, size/S
