Repository kubeflow/trainer, pull requests merged in 2021-05, with the labels that each got.

#1272 add podgroups rule in cluster-role.yaml
  manifests/base/cluster-role.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1274 fix: Remove the dup comment tag
  pkg/apis/tensorflow/v1/openapi_generated.go
  pkg/apis/tensorflow/v1/types.go
Labels: approved, size/XS

#1266 Use remote Kustomize build option in standalone installation instructions
  README.md
Labels: lgtm, ok-to-test, size/S
