Repository kubeflow/trainer, pull requests merged in 2021-03, with the labels that each got.

#1252 Update vendor as kubeflow/common is updated.
  go.mod
  go.sum
  vendor/github.com/kubeflow/common/pkg/controller.v1/common/job_controller.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, size/XS

#1247 TFJob Operator: Move manifests development upstream
  manifests/tf-job-crds/base/crd.yaml
  manifests/tf-job-crds/base/kustomization.yaml
  manifests/tf-job-crds/overlays/application/application.yaml
  manifests/tf-job-crds/overlays/application/kustomization.yaml
  manifests/tf-job-operator/base/cluster-role-binding.yaml
  manifests/tf-job-operator/base/cluster-role.yaml
  manifests/tf-job-operator/base/deployment.yaml
  manifests/tf-job-operator/base/kustomization.yaml
  manifests/tf-job-operator/base/params.env
  manifests/tf-job-operator/base/service-account.yaml
  manifests/tf-job-operator/base/service.yaml
  manifests/tf-job-operator/overlays/application/application.yaml
  manifests/tf-job-operator/overlays/application/kustomization.yaml
Labels: approved, lgtm, size/L

#1255 tf-operator: Consolidate manifests
  README.md
  deploy/v1/tf-operator.yaml
  manifests/base/cluster-role-binding.yaml
  manifests/base/cluster-role.yaml
  manifests/base/crd.yaml
  manifests/base/deployment.yaml
  manifests/base/kustomization.yaml
  manifests/base/service-account.yaml
  manifests/base/service.yaml
  manifests/deployment.yaml
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
  manifests/overlays/standalone/namespace.yaml
  manifests/podgroup.yaml
  manifests/rbac.yaml
  manifests/service.yaml
  manifests/tf-job-crds/base/crd.yaml
  manifests/tf-job-crds/base/kustomization.yaml
  manifests/tf-job-crds/overlays/application/application.yaml
  manifests/tf-job-crds/overlays/application/kustomization.yaml
  manifests/tf-job-operator/base/params.env
  manifests/tf-job-operator/base/service-account.yaml
  manifests/tf-job-operator/overlays/application/application.yaml
  manifests/tf-job-operator/overlays/application/kustomization.yaml
  scripts/setup-tf-operator.sh
Labels: approved, lgtm, size/XL

#1256 Migrate to public ECR
  manifests/base/deployment.yaml
  manifests/base/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
  prow_config.yaml
  scripts/setup-tf-operator.sh
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/M

#1260 Fix kubeflow overlay
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
  prow_config.yaml
Labels: approved, lgtm, size/S

#1263 Fix: Remove Github CD workflow
  .github/workflows/publish.yaml
Labels: approved, lgtm, size/M
