Repository kubeflow/trainer, pull requests merged in 2021-10, with the labels that each got.

#1428 Cherry pick #1415 #1418 to v1.3-branch
  README.md
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
Labels: size/S, lgtm, approved

#1430 Update training-operator image tag
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
Labels: size/XS

#1432 chore: update CHANGELOG.md
  CHANGELOG.md
  README.md
Labels: size/M, lgtm, approved

#1440 Add CI to run the tests for Go
  .github/workflows/test-go.yaml
  .gitignore
  .travis.yml
  Makefile
  README.md
  docs/development/developer_guide.md
  go.mod
  go.sum
  pkg/apis/mxnet/v1/openapi_generated.go
  pkg/apis/mxnet/v1/zz_generated.deepcopy.go
  pkg/apis/mxnet/v1/zz_generated.defaults.go
  pkg/apis/pytorch/v1/openapi_generated.go
  pkg/apis/pytorch/v1/zz_generated.deepcopy.go
  pkg/apis/pytorch/v1/zz_generated.defaults.go
  pkg/apis/tensorflow/v1/openapi_generated.go
  pkg/apis/tensorflow/v1/zz_generated.deepcopy.go
  pkg/apis/tensorflow/v1/zz_generated.defaults.go
  pkg/apis/xgboost/v1/openapi_generated.go
  pkg/apis/xgboost/v1/zz_generated.deepcopy.go
  pkg/apis/xgboost/v1/zz_generated.defaults.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/mxnet/mxnet.go
  pkg/controller.v1/mxnet/suite_test.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/pytorch/suite_test.go
  pkg/controller.v1/register_controller.go
  pkg/controller.v1/tensorflow/suite_test.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/suite_test.go
  pkg/controller.v1/xgboost/xgboost.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
  prow_config.yaml
  test/workflows/components/workflows.libsonnet
Labels: size/L, lgtm, approved

#1437 Generate a single `swagger.json` file for all frameworks
  hack/python-sdk/gen-sdk.sh
  hack/python-sdk/main.go
  pkg/apis/mxnet/v1/swagger.json
  pkg/apis/pytorch/v1/swagger.json
  pkg/apis/tensorflow/v1/swagger.json
  pkg/apis/xgboost/v1/swagger.json
  sdk/python/kubeflow/training/__init__.py
  sdk/python/kubeflow/training/api_client.py
  sdk/python/kubeflow/training/configuration.py
  sdk/python/kubeflow/training/exceptions.py
  sdk/python/kubeflow/training/models/__init__.py
  sdk/python/kubeflow/training/models/v1_job_condition.py
  sdk/python/kubeflow/training/models/v1_job_status.py
  sdk/python/kubeflow/training/models/v1_mx_job.py
  sdk/python/kubeflow/training/models/v1_mx_job_list.py
  sdk/python/kubeflow/training/models/v1_mx_job_spec.py
  sdk/python/kubeflow/training/models/v1_py_torch_job.py
  sdk/python/kubeflow/training/models/v1_py_torch_job_list.py
  sdk/python/kubeflow/training/models/v1_py_torch_job_spec.py
  sdk/python/kubeflow/training/models/v1_replica_spec.py
  sdk/python/kubeflow/training/models/v1_replica_status.py
  sdk/python/kubeflow/training/models/v1_run_policy.py
  sdk/python/kubeflow/training/models/v1_scheduling_policy.py
  sdk/python/kubeflow/training/models/v1_tf_job.py
  sdk/python/kubeflow/training/models/v1_tf_job_list.py
  sdk/python/kubeflow/training/models/v1_tf_job_spec.py
  sdk/python/kubeflow/training/models/v1_xg_boost_job.py
  sdk/python/kubeflow/training/models/v1_xg_boost_job_list.py
  sdk/python/kubeflow/training/models/v1_xg_boost_job_spec.py
  sdk/python/kubeflow/training/rest.py
  sdk/python/test/test_v1_job_condition.py
  sdk/python/test/test_v1_job_status.py
  sdk/python/test/test_v1_mx_job.py
  sdk/python/test/test_v1_mx_job_list.py
  sdk/python/test/test_v1_mx_job_spec.py
  sdk/python/test/test_v1_py_torch_job.py
  sdk/python/test/test_v1_py_torch_job_list.py
  sdk/python/test/test_v1_py_torch_job_spec.py
  sdk/python/test/test_v1_replica_spec.py
  sdk/python/test/test_v1_replica_status.py
  sdk/python/test/test_v1_run_policy.py
  sdk/python/test/test_v1_scheduling_policy.py
  sdk/python/test/test_v1_tf_job.py
  sdk/python/test/test_v1_tf_job_list.py
  sdk/python/test/test_v1_tf_job_spec.py
  sdk/python/test/test_v1_xg_boost_job.py
  sdk/python/test/test_v1_xg_boost_job_list.py
  sdk/python/test/test_v1_xg_boost_job_spec.py
Labels: size/XXL, lgtm, approved, ok-to-test

#1450 Fix README typo
  README.md
Labels: needs-ok-to-test, size/XS, lgtm, approved
