Repository kubeflow/trainer, pull requests merged in 2021-12, with the labels that each got.

#1489 chore: Update OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#1495 Fix a typo in mpi controller log
  pkg/controller.v1/mpi/mpijob_controller.go
Labels: size/XS, lgtm, approved, ok-to-test

#1493 feat(pytorch): Add init container config to avoid DNS lookup failure
  cmd/training-operator.v1/main.go
  go.mod
  pkg/config/config.go
  pkg/controller.v1/pytorch/elastic.go
  pkg/controller.v1/pytorch/envvar.go
  pkg/controller.v1/pytorch/initcontainer.go
  pkg/controller.v1/pytorch/initcontainer_test.go
  pkg/controller.v1/pytorch/master.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller_suite_test.go
Labels: size/L, lgtm, approved

#1500 Added 2022 roadmap and migrated previous roadmap from kubeflow/common
  docs/roadmap.md
Labels: size/M, lgtm, approved

#1508 add the example of MPIJob
  examples/mpi/tensorflow-mnist.yaml
Labels: size/M, lgtm, approved

#1484 add expectation-related functions for other resources used in mpi-controller
  pkg/common/util/reconciler.go
  pkg/common/util/reconciler_generic.go
  pkg/controller.v1/mpi/mpijob_controller.go
Labels: size/L, lgtm, approved

#1512 add StacktraceLevel for zapr
  cmd/training-operator.v1/main.go
  go.mod
Labels: size/XS, lgtm, approved, ok-to-test
