Repository kubeflow/trainer, pull requests merged in 2021-11, with the labels that each got.

#1449 consistent naming for better readability
  README.md
  pkg/apis/mxnet/v1/types.go
  pkg/apis/pytorch/v1/types.go
  pkg/apis/xgboost/v1/types.go
Labels: needs-ok-to-test, size/XS, lgtm, approved

#1448 Fix set scheduler error
  pkg/common/util/util.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
Labels: size/S, lgtm, approved, ok-to-test

#1460 Minor edits to README.md
  README.md
Labels: size/S, lgtm, approved

#1461 Migrate additional examples from xgboost-operator
  examples/xgboost/lightgbm-dist/Dockerfile
  examples/xgboost/lightgbm-dist/README.md
  examples/xgboost/lightgbm-dist/main.py
  examples/xgboost/lightgbm-dist/train.py
  examples/xgboost/lightgbm-dist/utils.py
  examples/xgboost/lightgbm-dist/xgboostjob_v1_lightgbm_dist_training.yaml
  examples/xgboost/smoke-dist/Dockerfile
  examples/xgboost/smoke-dist/README.md
  examples/xgboost/smoke-dist/requirements.txt
  examples/xgboost/smoke-dist/tracker.py
  examples/xgboost/smoke-dist/xgboost_smoke_test.py
  examples/xgboost/smoke-dist/xgboostjob_v1_rabit_test.yaml
  examples/xgboost/smoke-dist/xgboostjob_v1alpha1_rabit_test.yaml
  examples/xgboost/xgboost-dist/Dockerfile
  examples/xgboost/xgboost-dist/README.md
  examples/xgboost/xgboost-dist/build.sh
  examples/xgboost/xgboost-dist/local_test.py
  examples/xgboost/xgboost-dist/main.py
  examples/xgboost/xgboost-dist/predict.py
  examples/xgboost/xgboost-dist/requirements.txt
  examples/xgboost/xgboost-dist/tracker.py
  examples/xgboost/xgboost-dist/train.py
  examples/xgboost/xgboost-dist/utils.py
  examples/xgboost/xgboost-dist/xgboostjob_v1_iris_predict.yaml
  examples/xgboost/xgboost-dist/xgboostjob_v1_iris_train.yaml
  examples/xgboost/xgboost-dist/xgboostjob_v1alpha1_iris_predict.yaml
  examples/xgboost/xgboost-dist/xgboostjob_v1alpha1_iris_predict_local.yaml
  examples/xgboost/xgboost-dist/xgboostjob_v1alpha1_iris_train.yaml
  examples/xgboost/xgboost-dist/xgboostjob_v1alpha1_iris_train_local.yaml
Labels: size/XXL, lgtm, approved

#1463 chore: Add .gitattributes to ignore Jsonnet test code for linguist
  .gitattributes
Labels: size/XS, lgtm, approved

#1470 Add PR template with doc checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/S, lgtm, approved

#1457 add mpi-operator(v1) to the unified operator
  cmd/training-operator.v1/main.go
  manifests/base/cluster-role.yaml
  manifests/base/crds/kubeflow.org_mpijobs.yaml
  manifests/base/crds/kustomization.yaml
  pkg/apis/mpi/v1/constants.go
  pkg/apis/mpi/v1/default.go
  pkg/apis/mpi/v1/doc.go
  pkg/apis/mpi/v1/groupversion_info.go
  pkg/apis/mpi/v1/openapi_generated.go
  pkg/apis/mpi/v1/register.go
  pkg/apis/mpi/v1/swagger.json
  pkg/apis/mpi/v1/types.go
  pkg/apis/mpi/v1/zz_generated.deepcopy.go
  pkg/apis/mpi/v1/zz_generated.defaults.go
  pkg/apis/mpi/validation/validation.go
  pkg/controller.v1/mpi/mpijob.go
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/mpi/mpijob_controller_test.go
  pkg/controller.v1/mpi/suite_test.go
  pkg/controller.v1/register_controller.go
Labels: size/XXL, lgtm, approved, ok-to-test

#1473 Add Akuity to the list of adopters
  docs/adopters.md
Labels: size/XS, lgtm, approved

#1474 update label for tf-controller
  pkg/controller.v1/tensorflow/tfjob_controller.go
Labels: size/XS, lgtm, approved

#1476 Set Go version of base image to 1.17
  build/images/training-operator/Dockerfile
Labels: size/XS, lgtm, approved

#1477 add mpi doc
  README.md
  docs/api/mpi_generated.asciidoc
  hack/generate-apidoc.sh
Labels: size/M, lgtm, approved

#1480 Add MPI job to README now that it's supported
  README.md
Labels: size/XS, lgtm, approved

#1490 chore: Fix missspell in tfjob
  pkg/common/util/v1/testutil/tfjob.go
Labels: size/S, lgtm, approved

#1491 chore: Fix GitHub Actions script
  .github/workflows/test-go.yaml
Labels: size/S, lgtm, approved

#1485 fix comments for mpi-controller
  manifests/base/cluster-role.yaml
  pkg/apis/mpi/v1/constants.go
  pkg/apis/mpi/validation/validation.go
  pkg/apis/mpi/validation/validation_test.go
  pkg/controller.v1/mpi/mpijob_controller.go
Labels: size/L, lgtm, approved, ok-to-test
