Repository kubeflow/trainer, pull requests merged in 2021-08, with the labels that each got.

#1315 Use low-level controller and handlers in SetupWithManager
  cmd/tf-operator.v1/app/options/options.go
  pkg/apis/xgboost/validation/validation.go
  pkg/apis/xgboost/validation/validation_test.go
  pkg/common/util/reconciler.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/tensorflow/job.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: approved, lgtm, size/XL

#1328 Update container image for v1.1.1
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
Labels: size/XS

#1330 Don't use inline for runPolicy and register defaulter function
  config/crd/bases/kubeflow.org_mxjobs.yaml
  config/crd/bases/kubeflow.org_pytorchjobs.yaml
  config/crd/bases/kubeflow.org_tfjobs.yaml
  config/crd/bases/kubeflow.org_xgboostjobs.yaml
  pkg/apis/mxnet/v1/mxjob_types.go
  pkg/apis/pytorch/v1/defaults.go
  pkg/apis/pytorch/v1/pytorchjob_types.go
  pkg/apis/pytorch/v1/zz_generated.deepcopy.go
  pkg/apis/tensorflow/v1/defaults.go
  pkg/apis/tensorflow/v1/types.go
  pkg/apis/tensorflow/v1/zz_generated.deepcopy.go
  pkg/apis/xgboost/v1/xgboostjob_types.go
  pkg/apis/xgboost/v1/zz_generated.deepcopy.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: size/L, approved

#1334 Use PULL_PULL_SHA for image
  scripts/setup-tf-operator.sh
Labels: size/XS, lgtm, approved

#1338 Move root level docs to docs folder
  README.md
  docs/design/tf_job_design_doc.md
  docs/development/developer_guide.md
  docs/release/releasing.md
  docs/testing/e2e_testing.md
Labels: size/XS, lgtm, approved

#1339 chore: Update changelog.md
  CHANGELOG.md
Labels: size/L, lgtm, approved

#1336 Enable e2e test against universal operator
  Makefile
  build/images/training-operator/Dockerfile
  cmd/training-operator.v1/main.go
  config/crd/bases/kubeflow.org_pytorchjobs.yaml
  config/crd/bases/kubeflow.org_tfjobs.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_mxjobs.yaml
  config/crd/patches/cainjection_in_pytorchjobs.yaml
  config/crd/patches/cainjection_in_tfjobs.yaml
  config/crd/patches/cainjection_in_xgboostjobs.yaml
  config/crd/patches/webhook_in_mxjobs.yaml
  config/crd/patches/webhook_in_pytorchjobs.yaml
  config/crd/patches/webhook_in_tfjobs.yaml
  config/crd/patches/webhook_in_xgboostjobs.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  manifests/overlays/standalone_v2/kustomization.yaml
  manifests/overlays/standalone_v2/namespace.yaml
  pkg/apis/mxnet/v1/mxjob_types.go
  pkg/apis/pytorch/v1/pytorchjob_types.go
  pkg/apis/tensorflow/v1/types.go
  pkg/apis/xgboost/v1/xgboostjob_types.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/mxnet/suite_test.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/pytorch/suite_test.go
  pkg/controller.v1/tensorflow/suite_test.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/tensorflow/util_test.go
  pkg/controller.v1/xgboost/suite_test.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
  prow_config.yaml
  py/kubeflow/tf_operator/invalid_tfjob_tests.py
  scripts/setup-training-operator.sh
  test/workflows/components/workflows.libsonnet
Labels: size/XL, lgtm, approved

#1342 add option to enable schemes
  cmd/training-operator.v1/main.go
  pkg/controller.v1/register_controller.go
Labels: size/L, lgtm, approved

#1344 Fix postsubmit job using PULL_BASE_SHA
  prow_config.yaml
  scripts/setup-tf-operator.sh
  scripts/setup-training-operator.sh
  test/workflows/components/workflows.libsonnet
Labels: size/XS, lgtm, approved

#1347 Update training operator release process
  CHANGELOG.md
  docs/release/release.py
  docs/release/releasing.md
Labels: size/L, lgtm, approved

#1346 1322: Modified manifests to use all-in-one training-operator
  Makefile
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/manager/manager.yaml
  manifests/base/cluster-role-binding.yaml
  manifests/base/cluster-role.yaml
  manifests/base/crd.yaml
  manifests/base/deployment.yaml
  manifests/base/kubeflow.org_mxjobs.yaml
  manifests/base/kubeflow.org_pytorchjobs.yaml
  manifests/base/kubeflow.org_tfjobs.yaml
  manifests/base/kubeflow.org_xgboostjobs.yaml
  manifests/base/kustomization.yaml
  manifests/base/service-account.yaml
  manifests/base/service.yaml
  manifests/default/kustomization.yaml
  manifests/default/manager_config_patch.yaml
  manifests/manager/controller_manager_config.yaml
  manifests/manager/kustomization.yaml
  manifests/manager/manager.yaml
  manifests/overlays/kubeflow/kubeflow-training-roles.yaml
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
  manifests/overlays/standalone_v2/kustomization.yaml
  manifests/overlays/standalone_v2/namespace.yaml
  manifests/prometheus/kustomization.yaml
  manifests/prometheus/monitor.yaml
  manifests/rbac/auth_proxy_client_clusterrole.yaml
  manifests/rbac/auth_proxy_role.yaml
  manifests/rbac/auth_proxy_role_binding.yaml
  manifests/rbac/auth_proxy_service.yaml
  manifests/rbac/kustomization.yaml
  manifests/rbac/leader_election_role.yaml
  manifests/rbac/leader_election_role_binding.yaml
  manifests/rbac/mxjob_editor_role.yaml
  manifests/rbac/mxjob_viewer_role.yaml
  manifests/rbac/pytorchjob_editor_role.yaml
  manifests/rbac/pytorchjob_viewer_role.yaml
  manifests/rbac/role.yaml
  manifests/rbac/role_binding.yaml
  manifests/rbac/service_account.yaml
  manifests/rbac/tfjob_editor_role.yaml
  manifests/rbac/tfjob_viewer_role.yaml
  manifests/rbac/xgboostjob_editor_role.yaml
  manifests/rbac/xgboostjob_viewer_role.yaml
  scripts/setup-training-operator.sh
Labels: size/XL, lgtm, approved, ok-to-test

#1349 Clean up manifests and remove unused files
  manifests/base/cluster-role-binding.yaml
  manifests/base/cluster-role.yaml
  manifests/base/deployment.yaml
  manifests/base/kustomization.yaml
  manifests/default/kustomization.yaml
  manifests/default/manager_config_patch.yaml
  manifests/manager/controller_manager_config.yaml
  manifests/manager/kustomization.yaml
  manifests/overlays/kubeflow/kubeflow-training-roles.yaml
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
  manifests/prometheus/kustomization.yaml
  manifests/prometheus/monitor.yaml
  manifests/rbac/auth_proxy_client_clusterrole.yaml
  manifests/rbac/auth_proxy_role.yaml
  manifests/rbac/auth_proxy_role_binding.yaml
  manifests/rbac/auth_proxy_service.yaml
  manifests/rbac/kustomization.yaml
  manifests/rbac/leader_election_role.yaml
  manifests/rbac/leader_election_role_binding.yaml
  manifests/rbac/mxjob_editor_role.yaml
  manifests/rbac/mxjob_viewer_role.yaml
  manifests/rbac/pytorchjob_editor_role.yaml
  manifests/rbac/pytorchjob_viewer_role.yaml
  manifests/rbac/role.yaml
  manifests/rbac/role_binding.yaml
  manifests/rbac/service_account.yaml
  manifests/rbac/tfjob_editor_role.yaml
  manifests/rbac/tfjob_viewer_role.yaml
  manifests/rbac/xgboostjob_editor_role.yaml
  manifests/rbac/xgboostjob_viewer_role.yaml
Labels: size/XL, lgtm, approved

#1351 Trigger post-submit job
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: size/XS

#1356 docs: Update to use kubectl kustomize in instructions
  README.md
Labels: size/XS, lgtm

#1362 Fix XGBoost container name in log message
  pkg/apis/xgboost/validation/validation.go
Labels: size/XS, lgtm, approved

#1360 fix: Resolve scheme registration issue for defaulters
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: size/M, lgtm, approved

#1361 fix incorrect torch env population
  pkg/controller.v1/pytorch/pytorch.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
Labels: size/S, lgtm, approved

#1364 chore: Update manifest image tag
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
Labels: size/XS, lgtm, approved

#1370 add api-doc for all frameworks
  docs/api/autogen/config.yaml
  docs/api/generated.asciidoc
  docs/api/mxnet_generated.asciidoc
  docs/api/pytorch_generated.asciidoc
  docs/api/tensorflow_generated.asciidoc
  docs/api/xgboost_generated.asciidoc
  hack/generate-apidoc.sh
Labels: size/XL, lgtm, approved, ok-to-test

#1371 Fix copyright header for some files
  pkg/apis/mxnet/v1/constants.go
  pkg/apis/mxnet/v1/groupversion_info.go
  pkg/apis/mxnet/v1/mxjob_types.go
  pkg/apis/mxnet/validation/validation_test.go
  pkg/apis/pytorch/v1/groupversion_info.go
  pkg/apis/tensorflow/v1/groupversion_info.go
  pkg/apis/xgboost/v1/constants.go
  pkg/apis/xgboost/v1/groupversion_info.go
  pkg/apis/xgboost/v1/register.go
  pkg/apis/xgboost/v1/xgboostjob_types.go
  pkg/common/constants.go
  pkg/common/util/client.go
  pkg/common/util/fake_workqueue.go
  pkg/common/util/reconciler.go
  pkg/common/util/scheduler.go
  pkg/common/util/util.go
  pkg/common/util/v1/unstructured/informer.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/mxnet/mxnet.go
  pkg/controller.v1/mxnet/suite_test.go
  pkg/controller.v1/pytorch/pytorch.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/pytorch/suite_test.go
  pkg/controller.v1/tensorflow/informer.go
  pkg/controller.v1/tensorflow/job.go
  pkg/controller.v1/tensorflow/suite_test.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/suite_test.go
  pkg/controller.v1/xgboost/xgboost.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
  pkg/version/version.go
Labels: size/L, lgtm, approved, ok-to-test

#1374 Update include dirs in prow config
  prow_config.yaml
Labels: size/M, lgtm, approved

#1368 fix makefile to store crds in a separate folder
  Makefile
  manifests/base/crds/kubeflow.org_mxjobs.yaml
  manifests/base/crds/kubeflow.org_pytorchjobs.yaml
  manifests/base/crds/kubeflow.org_tfjobs.yaml
  manifests/base/crds/kubeflow.org_xgboostjobs.yaml
  manifests/base/crds/kustomization.yaml
  manifests/base/kustomization.yaml
Labels: size/S, lgtm, approved, ok-to-test

#1373 add example for mxnet and pytorch
  examples/crd/crd-podgroup.yaml
  examples/crd/crd-v1.yaml
  examples/mxnet/train/Dockerfile
  examples/mxnet/train/byteps_dist_gpu_v1.yaml
  examples/mxnet/train/mx_job_dist_gpu_v1.yaml
  examples/mxnet/tune/Dockerfile
  examples/mxnet/tune/README.md
  examples/mxnet/tune/auto-tuning.py
  examples/mxnet/tune/mx_job_tune_gpu_v1.yaml
  examples/mxnet/tune/start-job.py
  examples/pytorch/README.md
  examples/pytorch/mnist/Dockerfile
  examples/pytorch/mnist/Dockerfile-mpi
  examples/pytorch/mnist/Dockerfile.ppc64le
  examples/pytorch/mnist/Makefile
  examples/pytorch/mnist/README.md
  examples/pytorch/mnist/mnist.py
  examples/pytorch/mnist/v1/pytorch_job_mnist_gloo.yaml
  examples/pytorch/mnist/v1/pytorch_job_mnist_mpi.yaml
  examples/pytorch/mnist/v1/pytorch_job_mnist_nccl.yaml
  examples/pytorch/pytorch_cuda_docker/Dockerfile
  examples/pytorch/smoke-dist/Dockerfile
  examples/pytorch/smoke-dist/README.md
  examples/pytorch/smoke-dist/dist_sendrecv.py
  examples/pytorch/smoke-dist/pytorch_job_sendrecv.yaml
  examples/tensorflow/dist-mnist/Dockerfile
  examples/tensorflow/dist-mnist/Dockerfile.ppc64le
  examples/tensorflow/dist-mnist/README.md
  examples/tensorflow/dist-mnist/dist_mnist.py
  examples/tensorflow/dist-mnist/tf_job_mnist.yaml
  examples/tensorflow/distribution_strategy/estimator-API/Dockerfile
  examples/tensorflow/distribution_strategy/estimator-API/Makefile
  examples/tensorflow/distribution_strategy/estimator-API/README.md
  examples/tensorflow/distribution_strategy/estimator-API/distributed_tfjob.yaml
  examples/tensorflow/distribution_strategy/estimator-API/keras_model_to_estimator.py
  examples/tensorflow/distribution_strategy/keras-API/Dockerfile
  examples/tensorflow/distribution_strategy/keras-API/README.md
  examples/tensorflow/distribution_strategy/keras-API/multi_worker_strategy-with-keras.py
  examples/tensorflow/distribution_strategy/keras-API/multi_worker_tfjob.yaml
  examples/tensorflow/distribution_strategy/keras-API/pvc.yaml
  examples/tensorflow/mnist_with_summaries/Dockerfile
  examples/tensorflow/mnist_with_summaries/Dockerfile.ppc64le
  examples/tensorflow/mnist_with_summaries/README.md
  examples/tensorflow/mnist_with_summaries/mnist_with_summaries.py
  examples/tensorflow/mnist_with_summaries/tf_job_mnist.yaml
  examples/tensorflow/mnist_with_summaries/tfevent-volume/tfevent-pv.yaml
  examples/tensorflow/mnist_with_summaries/tfevent-volume/tfevent-pvc.yaml
  examples/tensorflow/tf_sample/Dockerfile
  examples/tensorflow/tf_sample/Makefile
  examples/tensorflow/tf_sample/setup.py
  examples/tensorflow/tf_sample/tf_smoke.py
Labels: size/XXL, lgtm, approved, ok-to-test

#1375 Fix 1340 prometheus counters
  pkg/apis/mxnet/v1/constants.go
  pkg/apis/pytorch/v1/constants.go
  pkg/apis/tensorflow/v1/constants.go
  pkg/apis/xgboost/v1/constants.go
  pkg/common/metrics.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/tensorflow/controller.go
  pkg/controller.v1/tensorflow/job.go
  pkg/controller.v1/tensorflow/pod.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: size/L, lgtm, approved, ok-to-test

#1387 chore(doc): Update README.md
  README.md
Labels: size/M, lgtm, approved

#1390 fix: volcano pod group creation issue
  cmd/training-operator.v1/main.go
  go.mod
  go.sum
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/register_controller.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: size/L, lgtm, approved

#1391 Add simple verification jobs
  examples/pytorch/simple.yaml
  examples/tensorflow/simple.yaml
Labels: size/M, lgtm, approved

#1388 chore: Bump kubeflow/common version to 0.3.7
  go.mod
  go.sum
  prow_config.yaml
Labels: size/XS, lgtm, approved

#1396 chore: Update training-operator tag
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
Labels: size/XS, lgtm, approved
