Repository kubeflow/trainer, pull requests merged in 2021-07, with the labels that each got.

#1286 add XGBoostJob api
  Makefile
  PROJECT
  config/crd/bases/kubeflow.org_xgboostjobs.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_xgboostjobs.yaml
  config/crd/patches/webhook_in_xgboostjobs.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/manager/controller_manager_config.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/rbac/xgboostjob_editor_role.yaml
  config/rbac/xgboostjob_viewer_role.yaml
  config/samples/kubeflow.org_v1_xgboostjob.yaml
  go.mod
  go.sum
  hack/boilerplate.go.txt
  main.go
  pkg/apis/xgboost/v1/constants.go
  pkg/apis/xgboost/v1/groupversion_info.go
  pkg/apis/xgboost/v1/xgboostjob_types.go
  pkg/apis/xgboost/v1/zz_generated.deepcopy.go
  pkg/controller.v1/xgboost/suite_test.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: lgtm, size/XXL

#1285 Fix invalid pointer when tfjob is deleted
  pkg/controller.v1/tensorflow/controller.go
  py/kubeflow/tf_operator/test_runner.py
  py/kubeflow/tf_operator/util.py
Labels: approved, lgtm, size/S

#1290 Generate tfjob 1.19.x compatible clientset
  go.mod
  go.sum
  hack/update-codegen.sh
  hack/violation_exception.list
  pkg/apis/tensorflow/v1/openapi_generated.go
  pkg/apis/xgboost/v1/constants.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/typed/tensorflow/v1/fake/fake_tfjob.go
  pkg/client/clientset/versioned/typed/tensorflow/v1/tfjob.go
  pkg/client/informers/externalversions/tensorflow/v1/tfjob.go
  pkg/client/listers/tensorflow/v1/tfjob.go
Labels: approved, lgtm, size/XL

#1292 Fix all client request that needs contexts
  cmd/tf-operator.v1/app/server.go
  pkg/common/util/v1/unstructured/informer.go
  pkg/controller.v1/tensorflow/controller.go
  pkg/controller.v1/tensorflow/job.go
  pkg/controller.v1/tensorflow/status.go
Labels: approved, lgtm, size/S

#1294 add pytorch API and controller
  PROJECT
  config/crd/bases/kubeflow.org_pytorchjobs.yaml
  config/crd/bases/kubeflow.org_tfjobs.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_pytorchjobs.yaml
  config/crd/patches/webhook_in_pytorchjobs.yaml
  config/rbac/pytorchjob_editor_role.yaml
  config/rbac/pytorchjob_viewer_role.yaml
  config/samples/kubeflow.org_v1_pytorchjob.yaml
  main.go
  pkg/apis/pytorch/v1/constants.go
  pkg/apis/pytorch/v1/defaults.go
  pkg/apis/pytorch/v1/doc.go
  pkg/apis/pytorch/v1/groupversion_info.go
  pkg/apis/pytorch/v1/pytorchjob_types.go
  pkg/apis/pytorch/v1/register.go
  pkg/apis/pytorch/v1/zz_generated.deepcopy.go
  pkg/apis/pytorch/v1/zz_generated.defaults.go
  pkg/apis/pytorch/validation/validation.go
  pkg/apis/pytorch/validation/validation_test.go
  pkg/controller.v1/pytorch/expectation.go
  pkg/controller.v1/pytorch/fake_workqueue.go
  pkg/controller.v1/pytorch/job.go
  pkg/controller.v1/pytorch/pod.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/pytorch/service.go
  pkg/controller.v1/pytorch/suite_test.go
  pkg/controller.v1/pytorch/utils.go
Labels: approved, lgtm, size/XXL

#1293 Add XGBoost controller
  config/samples/kubeflow.org_v1_pytorchjob.yaml
  config/samples/kubeflow.org_v1_xgboostjob.yaml
  examples/xgboost/xgboostjob.yaml
  main.go
  pkg/controller.v1/xgboost/expectation.go
  pkg/controller.v1/xgboost/job.go
  pkg/controller.v1/xgboost/pod.go
  pkg/controller.v1/xgboost/service.go
  pkg/controller.v1/xgboost/suite_test.go
  pkg/controller.v1/xgboost/util.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: approved, lgtm, size/XL

#1295 add tf reconciler to the unified operator
  PROJECT
  config/crd/bases/kubeflow.org_tfjobs.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_tfjobs.yaml
  config/crd/patches/webhook_in_tfjobs.yaml
  config/rbac/tfjob_editor_role.yaml
  config/rbac/tfjob_viewer_role.yaml
  hack/boilerplate/boilerplate.go.txt
  main.go
  pkg/apis/pytorch/v1/zz_generated.deepcopy.go
  pkg/apis/tensorflow/v1/defaults.go
  pkg/apis/tensorflow/v1/groupversion_info.go
  pkg/apis/tensorflow/v1/register.go
  pkg/apis/tensorflow/v1/types.go
  pkg/apis/tensorflow/v1/zz_generated.deepcopy.go
  pkg/apis/xgboost/v1/zz_generated.deepcopy.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/tensorflow/fake_workqueue.go
  pkg/controller.v1/tensorflow/informer.go
  pkg/controller.v1/tensorflow/pod.go
  pkg/controller.v1/tensorflow/suite_test.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/tensorflow/util.go
Labels: approved, lgtm, size/XL

#1296 Add MXJob v1 api and controller
  .gitignore
  PROJECT
  config/crd/bases/kubeflow.org_mxjobs.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_mxjobs.yaml
  config/crd/patches/webhook_in_mxjobs.yaml
  config/rbac/mxjob_editor_role.yaml
  config/rbac/mxjob_viewer_role.yaml
  examples/mxnet/mxjob_dist_v1.yaml
  main.go
  pkg/apis/mxnet/v1/constants.go
  pkg/apis/mxnet/v1/groupversion_info.go
  pkg/apis/mxnet/v1/mxjob_types.go
  pkg/apis/mxnet/v1/register.go
  pkg/apis/mxnet/v1/zz_generated.deepcopy.go
  pkg/apis/mxnet/validation/validation.go
  pkg/apis/mxnet/validation/validation_test.go
  pkg/controller.v1/mxnet/expectation.go
  pkg/controller.v1/mxnet/fake_workqueue.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/mxnet/mxnet.go
  pkg/controller.v1/mxnet/pod.go
  pkg/controller.v1/mxnet/service.go
  pkg/controller.v1/mxnet/status.go
  pkg/controller.v1/mxnet/suite_test.go
  pkg/controller.v1/mxnet/utils.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
Labels: approved, lgtm, size/XXL

#1297 Extract reusable codes to common utility
  pkg/apis/pytorch/v1/defaults.go
  pkg/apis/pytorch/v1/pytorchjob_types.go
  pkg/apis/pytorch/v1/zz_generated.deepcopy.go
  pkg/apis/pytorch/validation/validation.go
  pkg/apis/pytorch/validation/validation_test.go
  pkg/common/util/client.go
  pkg/common/util/fake_workqueue.go
  pkg/common/util/reconciler.go
  pkg/common/util/scheduler.go
  pkg/common/util/util.go
  pkg/controller.v1/mxnet/expectation.go
  pkg/controller.v1/mxnet/fake_workqueue.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/mxnet/pod.go
  pkg/controller.v1/mxnet/service.go
  pkg/controller.v1/pytorch/expectation.go
  pkg/controller.v1/pytorch/job.go
  pkg/controller.v1/pytorch/pod.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/pytorch/service.go
  pkg/controller.v1/tensorflow/controller.go
  pkg/controller.v1/tensorflow/fake_workqueue.go
  pkg/controller.v1/tensorflow/pod.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/expectation.go
  pkg/controller.v1/xgboost/pod.go
  pkg/controller.v1/xgboost/service.go
  pkg/controller.v1/xgboost/util.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: approved, lgtm, size/XL

#1305 add a specific version of tensorflow_datasets
  examples/v1/distribution_strategy/keras-API/Dockerfile
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1302 Reorganize controllers code structure
  config/crd/bases/kubeflow.org_pytorchjobs.yaml
  config/crd/bases/kubeflow.org_tfjobs.yaml
  examples/xgboost/xgboostjob.yaml
  pkg/common/util/client.go
  pkg/common/util/reconciler.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/mxnet/mxnet.go
  pkg/controller.v1/mxnet/pod.go
  pkg/controller.v1/mxnet/service.go
  pkg/controller.v1/mxnet/status.go
  pkg/controller.v1/mxnet/suite_test.go
  pkg/controller.v1/mxnet/utils.go
  pkg/controller.v1/pytorch/job.go
  pkg/controller.v1/pytorch/pytorch.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/pytorch/service.go
  pkg/controller.v1/pytorch/utils.go
  pkg/controller.v1/tensorflow/pod.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/job.go
  pkg/controller.v1/xgboost/service.go
  pkg/controller.v1/xgboost/util.go
  pkg/controller.v1/xgboost/xgboost.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: approved, lgtm, size/XXL
