Repository kubeflow/trainer, pull requests merged in 2021-01, with the labels that each got.

#1210 add err log for create client set failed and code minor optimization
  cmd/tf-operator.v1/app/server.go
Labels: approved, size/XS

#1209 add Evaluator type for CRD example
  examples/crd/crd-v1.yaml
Labels: approved, size/XS

#1211 chore: Update codegen
  pkg/apis/tensorflow/v1/openapi_generated.go
  pkg/apis/tensorflow/v1/zz_generated.deepcopy.go
  pkg/apis/tensorflow/v1/zz_generated.defaults.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/tensorflow/v1/doc.go
  pkg/client/clientset/versioned/typed/tensorflow/v1/fake/doc.go
  pkg/client/clientset/versioned/typed/tensorflow/v1/fake/fake_tensorflow_client.go
  pkg/client/clientset/versioned/typed/tensorflow/v1/fake/fake_tfjob.go
  pkg/client/clientset/versioned/typed/tensorflow/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/tensorflow/v1/tensorflow_client.go
  pkg/client/clientset/versioned/typed/tensorflow/v1/tfjob.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/tensorflow/interface.go
  pkg/client/informers/externalversions/tensorflow/v1/interface.go
  pkg/client/informers/externalversions/tensorflow/v1/tfjob.go
  pkg/client/listers/tensorflow/v1/expansion_generated.go
  pkg/client/listers/tensorflow/v1/tfjob.go
  vendor/github.com/kubeflow/common/pkg/util/logger.go
Labels: approved, lgtm, size/M

#1215 Fix updateStatus no worker Crashoff
  pkg/common/util/v1/testutil/tfjob.go
  pkg/controller.v1/tensorflow/pod.go
  pkg/controller.v1/tensorflow/pod_test.go
Labels: approved, lgtm, size/L

#1217 chore: Remove useless expectation
  pkg/controller.v1/tensorflow/controller.go
  pkg/controller.v1/tensorflow/job.go
Labels: approved, lgtm, size/XS

#1218 feat(deploy): Add standalone deployment yaml
  README.md
  deploy/v1/tf-operator.yaml
Labels: approved, lgtm, size/L

#1225 Update kubeflow common to 0.3.2
  go.mod
  go.sum
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1226 Fix completion time setting bug
  pkg/controller.v1/tensorflow/status.go
Labels: approved, lgtm, ok-to-test, size/XS

#1228 feat(server): Use apiextension client to check if crd exists
  cmd/tf-operator.v1/app/server.go
  go.mod
  go.sum
  vendor/github.com/kubeflow/common/pkg/apis/common/v1/openapi_generated.go
  vendor/github.com/kubeflow/common/pkg/apis/common/v1/zz_generated.deepcopy.go
  vendor/github.com/kubeflow/common/pkg/apis/common/v1/zz_generated.defaults.go
  vendor/github.com/kubeflow/common/pkg/controller.v1/common/job.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/helpers.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/generated_expansion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/generated_expansion.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#1227 chore: Update changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XL

#1230 feat: Change the message for running condition
  pkg/controller.v1/tensorflow/status.go
Labels: approved, lgtm, size/XS
