Repository kubeflow/trainer, pull requests merged in 2021-09, with the labels that each got.

#1383 chore: Update k8s related package to 0.19.9, kubeflow/common to 0.3.7 in v1.2 branch
  cmd/tf-operator.v1/app/server.go
  go.mod
  go.sum
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/typed/tensorflow/v1/fake/fake_tfjob.go
  pkg/client/clientset/versioned/typed/tensorflow/v1/tfjob.go
  pkg/client/informers/externalversions/tensorflow/v1/tfjob.go
  pkg/client/listers/tensorflow/v1/tfjob.go
  pkg/common/util/v1/unstructured/informer.go
  pkg/controller.v1/tensorflow/controller.go
  pkg/controller.v1/tensorflow/job.go
  pkg/controller.v1/tensorflow/status.go
Labels: size/XL, lgtm, approved

#1401 fix: runPolicy validation error in the examples
  examples/tensorflow/distribution_strategy/estimator-API/distributed_tfjob.yaml
  examples/tensorflow/distribution_strategy/keras-API/multi_worker_tfjob.yaml
  examples/tensorflow/mnist_with_summaries/tf_job_mnist.yaml
Labels: size/XS, lgtm, approved

#1405 2010: fix to expose correct monitoring port
  manifests/base/deployment.yaml
  manifests/base/service.yaml
Labels: size/XS, lgtm, approved

#1404 Fix 1399: added pod matching label in service selector
  manifests/base/service.yaml
Labels: size/XS, lgtm, approved

#1406 Update manifests with latest image tag
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
Labels: size/XS, lgtm, approved

#1409 Bump controller-tools to 0.6.0 and enable GenerateEmbeddedObjectMeta
  Makefile
  manifests/base/crds/kubeflow.org_mxjobs.yaml
  manifests/base/crds/kubeflow.org_pytorchjobs.yaml
  manifests/base/crds/kubeflow.org_tfjobs.yaml
  manifests/base/crds/kubeflow.org_xgboostjobs.yaml
Labels: size/L, lgtm, approved

#1410 Cherry pick of #1409: Bump controller-tools to 0.6.0 and enable GenerateEmbeddedObjectMeta
  Makefile
  manifests/base/crds/kubeflow.org_mxjobs.yaml
  manifests/base/crds/kubeflow.org_pytorchjobs.yaml
  manifests/base/crds/kubeflow.org_tfjobs.yaml
  manifests/base/crds/kubeflow.org_xgboostjobs.yaml
Labels: size/L, lgtm, approved

#1412 chore: Update image tags in manifests
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
Labels: size/XS, lgtm, approved

#1417 docs: Migrate adopters of all operators to this repo
  docs/adopters.md
Labels: size/M, lgtm, approved

#1419 docs: Move myself to approvers
  OWNERS
Labels: size/XS, lgtm, approved

#1421 Add Cisco to Adopters List
  docs/adopters.md
Labels: size/XS, lgtm, approved

#1422 Add acknowledgement section in README to credit all contributors
  README.md
Labels: size/S, lgtm, approved

#1415 Feature/support pytorchjob set queue of volcano
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
Labels: size/S, lgtm, approved, ok-to-test

#1418 fix hyperlinks in the 'overview' section
  README.md
Labels: size/XS, lgtm, approved, ok-to-test
