Repository kubeflow/trainer, pull requests merged in 2022-06, with the labels that each got.

#1603 Migrate test framework to GHA
  .github/workflows/integration-tests.yaml
  scripts/gha/build-image.sh
  scripts/gha/setup-training-operator.sh
  sdk/python/test/e2e/test_e2e_tfjob.py
Labels: size/L, lgtm, approved

#1588 Look for fully-qualified job role label in Python sdk
  sdk/python/kubeflow/training/constants/constants.py
Labels: size/XS, lgtm, approved, ok-to-test

#1604 Update k8s dependencies to v0.24.1
  .github/workflows/integration-tests.yaml
  .github/workflows/test-go.yaml
  .github/workflows/unittests.yaml
  Makefile
  go.mod
  go.sum
  hack/python-sdk/main.go
  hack/python-sdk/swagger.json
  hack/update-codegen.sh
  manifests/base/crds/kubeflow.org_mpijobs.yaml
  manifests/base/crds/kubeflow.org_mxjobs.yaml
  manifests/base/crds/kubeflow.org_pytorchjobs.yaml
  manifests/base/crds/kubeflow.org_tfjobs.yaml
  manifests/base/crds/kubeflow.org_xgboostjobs.yaml
  pkg/apis/mpi/v1/openapi_generated.go
  pkg/apis/mpi/v1/zz_generated.defaults.go
  pkg/apis/mxnet/v1/openapi_generated.go
  pkg/apis/pytorch/v1/openapi_generated.go
  pkg/apis/tensorflow/v1/openapi_generated.go
  pkg/apis/xgboost/v1/openapi_generated.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/typed/tensorflow/v1/fake/fake_tfjob.go
  pkg/client/clientset/versioned/typed/tensorflow/v1/tensorflow_client.go
  pkg/common/update.go
  pkg/common/util/fake_workqueue.go
  scripts/gha/setup-training-operator.sh
  sdk/python/docs/V1ElasticPolicy.md
  sdk/python/docs/V1JobCondition.md
  sdk/python/docs/V1MXJobSpec.md
  sdk/python/kubeflow/training/models/v1_elastic_policy.py
  sdk/python/kubeflow/training/models/v1_job_condition.py
  sdk/python/kubeflow/training/models/v1_mx_job_spec.py
Labels: size/XXL, lgtm, approved

#1572 Restart job on failure for Always,OnFailure Policy
  pkg/controller.v1/pytorch/pytorchjob_controller.go
Labels: size/XS, lgtm, approved, ok-to-test

#1606 Generating MPI python sdk
  hack/python-sdk/main.go
  hack/python-sdk/swagger.json
  pkg/apis/mpi/v1/openapi_generated.go
  pkg/apis/mpi/v1/types.go
  sdk/python/docs/GithubComKubeflowTrainingOperatorPkgApisMpiV1MPIJob.md
  sdk/python/docs/GithubComKubeflowTrainingOperatorPkgApisMpiV1MPIJobList.md
  sdk/python/docs/GithubComKubeflowTrainingOperatorPkgApisMpiV1MPIJobSpec.md
  sdk/python/docs/V1MPIJob.md
  sdk/python/docs/V1MPIJobList.md
  sdk/python/docs/V1MPIJobSpec.md
  sdk/python/kubeflow/training/__init__.py
  sdk/python/kubeflow/training/models/__init__.py
  sdk/python/kubeflow/training/models/v1_mpi_job.py
  sdk/python/kubeflow/training/models/v1_mpi_job_list.py
  sdk/python/kubeflow/training/models/v1_mpi_job_spec.py
  sdk/python/test/test_v1_mpi_job.py
  sdk/python/test/test_v1_mpi_job_list.py
  sdk/python/test/test_v1_mpi_job_spec.py
Labels: size/XXL, lgtm, approved

#1607 Adding XGboost Python sdk
  hack/python-sdk/post_gen.py
  sdk/python/kubeflow/training/__init__.py
  sdk/python/kubeflow/training/api/xgboost_job_client.py
  sdk/python/kubeflow/training/api/xgboost_job_watch.py
  sdk/python/kubeflow/training/constants/constants.py
  sdk/python/kubeflow/training/utils/utils.py
  sdk/python/test/e2e/test_e2e_xgboostjob.py
Labels: size/XL, lgtm, approved

#1593 fix Pytorjob status inaccuracy when task replica scale down
  pkg/controller.v1/pytorch/pytorchjob_controller.go
Labels: size/XS, lgtm, approved, ok-to-test

#1608 Adding MPI python sdk
  hack/python-sdk/post_gen.py
  pkg/controller.v1/mpi/mpijob_controller.go
  sdk/python/kubeflow/training/__init__.py
  sdk/python/kubeflow/training/api/mpi_job_client.py
  sdk/python/kubeflow/training/api/mpi_job_watch.py
  sdk/python/kubeflow/training/constants/constants.py
  sdk/python/kubeflow/training/utils/utils.py
  sdk/python/test/e2e/test_e2e_mpijob.py
Labels: size/XL, lgtm, approved

#1609 Add all generation tools to Makefile
  .github/workflows/test-go.yaml
  Makefile
  docs/api/mpi_generated.asciidoc
  docs/api/mxnet_generated.asciidoc
  docs/api/pytorch_generated.asciidoc
  docs/api/tensorflow_generated.asciidoc
  docs/api/xgboost_generated.asciidoc
  go.mod
  go.sum
  hack/generate-apidoc.sh
Labels: size/L, lgtm, approved

#1537 mod: Upgrade ginkgo to v2
  go.mod
  go.sum
  pkg/apis/kubeflow.org/v1/pytorch_defaults_test.go
  pkg/controller.v1/mpi/mpijob_controller_test.go
  pkg/controller.v1/mpi/suite_test.go
  pkg/controller.v1/mxnet/suite_test.go
  pkg/controller.v1/pytorch/elastic_test.go
  pkg/controller.v1/pytorch/initcontainer_test.go
  pkg/controller.v1/pytorch/pytorchjob_controller_suite_test.go
  pkg/controller.v1/pytorch/pytorchjob_controller_test.go
  pkg/controller.v1/tensorflow/job_test.go
  pkg/controller.v1/tensorflow/pod_test.go
  pkg/controller.v1/tensorflow/status_test.go
  pkg/controller.v1/tensorflow/suite_test.go
  pkg/controller.v1/tensorflow/tfjob_controller_test.go
  pkg/controller.v1/xgboost/suite_test.go
Labels: size/M, lgtm, approved, ok-to-test

#1614 fix: requeue when expire time is not up yet
  pkg/common/util/util.go
  pkg/common/util/util_test.go
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/tensorflow/job_test.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: size/L, lgtm, approved

#1618 MXNet SDK with Status check fix
  hack/python-sdk/post_gen.py
  pkg/controller.v1/mxnet/mxjob_controller.go
  sdk/python/kubeflow/training/__init__.py
  sdk/python/kubeflow/training/api/mx_job_client.py
  sdk/python/kubeflow/training/api/mx_job_watch.py
  sdk/python/kubeflow/training/constants/constants.py
  sdk/python/kubeflow/training/utils/utils.py
  sdk/python/test/e2e/test_e2e_mxjob.py
Labels: size/XL, lgtm, approved

#1620 fix comments for pytorch-controller
  pkg/controller.v1/pytorch/pytorchjob_controller.go
Labels: size/S, lgtm, approved

#1623 Upgrade common to v0.4.3
  go.mod
  go.sum
Labels: size/XS, lgtm, approved

#1621 fix: MPIJob worker still running when NotEnoughResources
  pkg/controller.v1/mpi/mpijob_controller.go
Labels: size/S, lgtm, approved

#1625 Update training controller image to latest
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
Labels: size/XS, lgtm, approved
