Repository kubeflow/trainer, pull requests merged in 2022-11, with the labels that each got.

#1684 Support for k8s v1.25 in CI
  .github/workflows/integration-tests.yaml
  .github/workflows/unittests.yaml
  go.mod
  go.sum
  manifests/base/crds/kubeflow.org_mpijobs.yaml
  manifests/base/crds/kubeflow.org_mxjobs.yaml
  manifests/base/crds/kubeflow.org_pytorchjobs.yaml
  manifests/base/crds/kubeflow.org_tfjobs.yaml
  manifests/base/crds/kubeflow.org_xgboostjobs.yaml
Labels: size/XXL, lgtm, approved

#1686 [chore] Upgrade some actions version
  .github/workflows/integration-tests.yaml
  .github/workflows/publish-images.yaml
  .github/workflows/template-publish-image/action.yaml
  .github/workflows/test-go.yaml
  .github/workflows/unittests.yaml
Labels: size/S, lgtm, approved

#1687 Upgrade the envtest version
  Makefile
Labels: size/XS, lgtm, approved

#1685 Upgrade Golangci-lint
  Makefile
Labels: size/XS, lgtm, approved

#1680 Make a generic logger instead of the nil logger on dependent update
  pkg/common/util/reconciler.go
  pkg/common/util/reconciler_test.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: size/L, lgtm, approved

#1675 [PaddlePaddle] support paddlejob
  README.md
  cmd/training-operator.v1/main.go
  docs/api/kubeflow.org_v1_generated.asciidoc
  examples/paddlepaddle/simple-cpu.yaml
  examples/paddlepaddle/simple-gpu.yaml
  hack/python-sdk/post_gen.py
  hack/python-sdk/swagger.json
  hack/violation_exception.list
  manifests/base/cluster-role.yaml
  manifests/base/crds/kubeflow.org_paddlejobs.yaml
  manifests/base/crds/kustomization.yaml
  manifests/overlays/kubeflow/kubeflow-training-roles.yaml
  pkg/apis/kubeflow.org/v1/openapi_generated.go
  pkg/apis/kubeflow.org/v1/paddlepaddle_defautls.go
  pkg/apis/kubeflow.org/v1/paddlepaddle_types.go
  pkg/apis/kubeflow.org/v1/paddlepaddle_validation.go
  pkg/apis/kubeflow.org/v1/paddlepaddle_validation_test.go
  pkg/apis/kubeflow.org/v1/zz_generated.deepcopy.go
  pkg/apis/kubeflow.org/v1/zz_generated.defaults.go
  pkg/client/clientset/versioned/typed/kubeflow.org/v1/fake/fake_kubeflow.org_client.go
  pkg/client/clientset/versioned/typed/kubeflow.org/v1/fake/fake_paddlejob.go
  pkg/client/clientset/versioned/typed/kubeflow.org/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/kubeflow.org/v1/kubeflow.org_client.go
  pkg/client/clientset/versioned/typed/kubeflow.org/v1/paddlejob.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/kubeflow.org/v1/interface.go
  pkg/client/informers/externalversions/kubeflow.org/v1/paddlejob.go
  pkg/client/listers/kubeflow.org/v1/expansion_generated.go
  pkg/client/listers/kubeflow.org/v1/paddlejob.go
  pkg/controller.v1/paddlepaddle/envvar.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller_suite_test.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller_test.go
  pkg/controller.v1/register_controller.go
  sdk/python/docs/KubeflowOrgV1PaddleElasticPolicy.md
  sdk/python/docs/KubeflowOrgV1PaddleJob.md
  sdk/python/docs/KubeflowOrgV1PaddleJobList.md
  sdk/python/docs/KubeflowOrgV1PaddleJobSpec.md
  sdk/python/kubeflow/training/__init__.py
  sdk/python/kubeflow/training/api/paddle_job_client.py
  sdk/python/kubeflow/training/api/paddle_job_watch.py
  sdk/python/kubeflow/training/constants/constants.py
  sdk/python/kubeflow/training/models/__init__.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_paddle_elastic_policy.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_paddle_job.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_paddle_job_list.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_paddle_job_spec.py
  sdk/python/test/e2e/test_e2e_paddlejob.py
  sdk/python/test/test_kubeflow_org_v1_paddle_elastic_policy.py
  sdk/python/test/test_kubeflow_org_v1_paddle_job.py
  sdk/python/test/test_kubeflow_org_v1_paddle_job_list.py
  sdk/python/test/test_kubeflow_org_v1_paddle_job_spec.py
Labels: size/XXL, lgtm, approved

#1689 Add myself to reviewer.
  OWNERS
Labels: size/XS, lgtm, approved

#1692 Adding support for linux/ppc64le in github actions for training-operator
  .github/workflows/template-publish-image/action.yaml
Labels: size/XS, lgtm, approved
