Repository kubeflow/trainer, pull requests merged in 2022-09, with the labels that each got.

#1656 Update the cmd to support MPI operator in ReadME
  README.md
Labels: size/XS, lgtm, approved

#1660 style: Refine name and signature of 2 replicaName functions
  pkg/controller.v1/pytorch/envvar.go
  pkg/controller.v1/pytorch/initcontainer.go
  pkg/controller.v1/pytorch/master.go
  pkg/controller.v1/xgboost/xgboost.go
Labels: size/S, lgtm, approved

#1659 Create TFJob and PyTorchJob from Function APIs in the Training SDK
  .github/workflows/integration-tests.yaml
  sdk/python/examples/create-pytorchjob-from-func.ipynb
  sdk/python/kubeflow/training/api/mpi_job_client.py
  sdk/python/kubeflow/training/api/mpi_job_watch.py
  sdk/python/kubeflow/training/api/mx_job_client.py
  sdk/python/kubeflow/training/api/mx_job_watch.py
  sdk/python/kubeflow/training/api/py_torch_job_client.py
  sdk/python/kubeflow/training/api/py_torch_job_watch.py
  sdk/python/kubeflow/training/api/tf_job_client.py
  sdk/python/kubeflow/training/api/tf_job_watch.py
  sdk/python/kubeflow/training/api/xgboost_job_client.py
  sdk/python/kubeflow/training/api/xgboost_job_watch.py
  sdk/python/kubeflow/training/constants/constants.py
  sdk/python/kubeflow/training/utils/utils.py
  sdk/python/requirements.txt
  sdk/python/setup.py
Labels: size/XXL, lgtm, approved

#1663 Upgrade Go version to v1.19
  .github/workflows/test-go.yaml
  .github/workflows/unittests.yaml
  Makefile
  build/images/training-operator/Dockerfile
  go.mod
  go.sum
  hack/swagger/go.mod
  hack/swagger/go.sum
  pkg/apis/kubeflow.org/v1/groupversion_info.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/pytorch/initcontainer.go
  pkg/controller.v1/tensorflow/tensorflow.go
Labels: size/XL, lgtm, approved

#1667 Upgrade kubernetes versoin for test
  .github/workflows/integration-tests.yaml
  .github/workflows/unittests.yaml
  Makefile
Labels: size/XS, lgtm, approved

#1668 Update deployment.yaml
  manifests/base/deployment.yaml
Labels: size/XS, lgtm, approved
