Repository kubeflow/trainer, pull requests merged in 2022-03, with the labels that each got.

#1539 Cherry pick PR: extends path in __init__.py for SDK correctly (#1531)
  sdk/python/kubeflow/__init__.py
Labels: size/XS, lgtm, approved

#1541 Release Python SDK 1.4.0
  hack/python-sdk/gen-sdk.sh
  hack/python-sdk/post_gen.py
  hack/python-sdk/swagger.json
  sdk/python/kubeflow/__init__.py
  sdk/python/kubeflow/training/__init__.py
  sdk/python/kubeflow/training/api_client.py
  sdk/python/kubeflow/training/configuration.py
  sdk/python/kubeflow/training/exceptions.py
  sdk/python/kubeflow/training/models/__init__.py
  sdk/python/kubeflow/training/models/v1_elastic_policy.py
  sdk/python/kubeflow/training/models/v1_job_condition.py
  sdk/python/kubeflow/training/models/v1_job_status.py
  sdk/python/kubeflow/training/models/v1_mx_job.py
  sdk/python/kubeflow/training/models/v1_mx_job_list.py
  sdk/python/kubeflow/training/models/v1_mx_job_spec.py
  sdk/python/kubeflow/training/models/v1_py_torch_job.py
  sdk/python/kubeflow/training/models/v1_py_torch_job_list.py
  sdk/python/kubeflow/training/models/v1_py_torch_job_spec.py
  sdk/python/kubeflow/training/models/v1_rdzv_conf.py
  sdk/python/kubeflow/training/models/v1_replica_spec.py
  sdk/python/kubeflow/training/models/v1_replica_status.py
  sdk/python/kubeflow/training/models/v1_run_policy.py
  sdk/python/kubeflow/training/models/v1_scheduling_policy.py
  sdk/python/kubeflow/training/models/v1_tf_job.py
  sdk/python/kubeflow/training/models/v1_tf_job_list.py
  sdk/python/kubeflow/training/models/v1_tf_job_spec.py
  sdk/python/kubeflow/training/models/v1_xg_boost_job.py
  sdk/python/kubeflow/training/models/v1_xg_boost_job_list.py
  sdk/python/kubeflow/training/models/v1_xg_boost_job_spec.py
  sdk/python/kubeflow/training/rest.py
  sdk/python/setup.py
  sdk/python/test/test_v1_elastic_policy.py
  sdk/python/test/test_v1_job_condition.py
  sdk/python/test/test_v1_job_status.py
  sdk/python/test/test_v1_mx_job.py
  sdk/python/test/test_v1_mx_job_list.py
  sdk/python/test/test_v1_mx_job_spec.py
  sdk/python/test/test_v1_py_torch_job.py
  sdk/python/test/test_v1_py_torch_job_list.py
  sdk/python/test/test_v1_py_torch_job_spec.py
  sdk/python/test/test_v1_rdzv_conf.py
  sdk/python/test/test_v1_replica_spec.py
  sdk/python/test/test_v1_replica_status.py
  sdk/python/test/test_v1_run_policy.py
  sdk/python/test/test_v1_scheduling_policy.py
  sdk/python/test/test_v1_tf_job.py
  sdk/python/test/test_v1_tf_job_list.py
  sdk/python/test/test_v1_tf_job_spec.py
  sdk/python/test/test_v1_xg_boost_job.py
  sdk/python/test/test_v1_xg_boost_job_list.py
  sdk/python/test/test_v1_xg_boost_job_spec.py
Labels: size/L, lgtm, approved, ok-to-test

#1545 fix: add namespace filtering when getting pods/services for jobs
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: size/S, lgtm, approved, ok-to-test

#1549 fix UpdateJobStatusInApiServer when gang-scheduling is enabled
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: size/S, lgtm, approved

#1554 fix: set mpijob runPolicy.cleanPodPolicy to default none
  pkg/apis/mpi/v1/default.go
Labels: size/XS, lgtm, approved, ok-to-test

#1551 fix api reader issue
  pkg/common/util/client.go
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: size/L, lgtm, approved

#1557 fix: MPIJob cannot use gang-scheduling when --enable-gang-scheduling is set
  pkg/controller.v1/mpi/mpijob_controller.go
Labels: size/XS, lgtm, approved, ok-to-test

#1550 fix label and CleanPodPolicy for mpi-controller
  examples/mpi/tensorflow-mnist.yaml
  pkg/apis/mpi/v1/default.go
  pkg/common/util/util.go
  pkg/controller.v1/mpi/mpijob.go
  pkg/controller.v1/mpi/mpijob_controller.go
Labels: size/L, lgtm, approved

#1565 fix: add mpijobs to kubeflow training role
  manifests/overlays/kubeflow/kubeflow-training-roles.yaml
Labels: size/XS, lgtm, approved, ok-to-test

#1567 update status.startTime for pytorchjob and xgboostjob
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: size/M, lgtm, approved
