Repository kubeflow/trainer, pull requests merged in 2022-01, with the labels that each got.

#1513 remove ChanYiLin from approvers
  OWNERS
Labels: size/XS, lgtm, approved

#1511 add unit tests for tensorflow controller
  pkg/common/util/v1/testutil/pod.go
  pkg/common/util/v1/testutil/service.go
  pkg/common/util/v1/testutil/tfjob.go
  pkg/common/util/v1/testutil/util.go
  pkg/controller.v1/tensorflow/job_test.go
  pkg/controller.v1/tensorflow/pod_test.go
  pkg/controller.v1/tensorflow/status_test.go
  pkg/controller.v1/tensorflow/suite_test.go
  pkg/controller.v1/tensorflow/tfjob_controller_test.go
  pkg/controller.v1/tensorflow/util_test.go
Labels: size/XXL, lgtm, approved

#1521 remove unused scripts
  pkg/apis/mpi/v1/constants.go
  pkg/common/constants.go
  pkg/common/util/client.go
  pkg/common/util/scheduler.go
  pkg/common/util/util.go
  pkg/common/util/v1/testutil/service.go
  pkg/common/util/v1/unstructured/informer.go
  pkg/config/config.go
  pkg/controller.v1/register_controller.go
  pkg/controller.v1/register_controller_test.go
  pkg/controller.v1/tensorflow/job_test.go
  pkg/controller.v1/tensorflow/status_test.go
  pkg/controller.v1/tensorflow/tfjob_controller_test.go
  pkg/version/version.go
Labels: size/L, lgtm, approved

#1524 restore option namespace in launch arguments
  cmd/training-operator.v1/main.go
Labels: size/S, lgtm, approved

#1525 add option for mpi kubectl delivery
  cmd/training-operator.v1/main.go
  pkg/config/config.go
  pkg/controller.v1/mpi/mpijob.go
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/mpi/suite_test.go
Labels: size/L, lgtm, approved

#1527 Update manifests with latest image tag
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
Labels: size/XS, lgtm, approved

#1528 chore: Update changelog for v1.4.0-rc.0 release
  CHANGELOG.md
  hack/scripts/update-changelog.sh
Labels: size/XXL, lgtm, approved
