Repository kubeflow/trainer, pull requests merged in 2022-07, with the labels that each got.

#1583 fix: fix wrong parameter for resolveControllerRef
  pkg/common/util/reconciler.go
  pkg/common/util/reconciler_generic.go
Labels: size/XS, lgtm, approved, ok-to-test

#1562 fix: tfjob with restartPolicy=ExitCode not work
  pkg/controller.v1/tensorflow/tfjob_controller.go
Labels: size/S, lgtm, approved, ok-to-test

#1639 Fix the default LeaderElectionID and make it an argument
  cmd/training-operator.v1/main.go
Labels: size/XS, lgtm, approved
