Repository kubeflow/trainer, pull requests merged in 2022-12, with the labels that each got.

#1697 Fix status lost
  pkg/controller.v1/mpi/mpijob_controller.go
Labels: size/XS, lgtm, approved

#1700 fix: Mac M1 compatible Dockerfile and bump TF version
  examples/tensorflow/distribution_strategy/keras-API/Dockerfile
Labels: size/XS, lgtm, approved

#1701 HPA support for PyTorch Elastic
  Makefile
  docs/api/kubeflow.org_v1_generated.asciidoc
  examples/pytorch/elastic/imagenet/Dockerfile
  examples/pytorch/elastic/imagenet/imagenet.yaml
  go.mod
  go.sum
  hack/python-sdk/swagger.json
  manifests/base/cluster-role.yaml
  manifests/base/crds/kubeflow.org_mpijobs.yaml
  manifests/base/crds/kubeflow.org_mxjobs.yaml
  manifests/base/crds/kubeflow.org_paddlejobs.yaml
  manifests/base/crds/kubeflow.org_pytorchjobs.yaml
  manifests/base/crds/kubeflow.org_tfjobs.yaml
  manifests/base/crds/kubeflow.org_xgboostjobs.yaml
  pkg/apis/kubeflow.org/v1/openapi_generated.go
  pkg/apis/kubeflow.org/v1/paddlepaddle_types.go
  pkg/apis/kubeflow.org/v1/pytorch_types.go
  pkg/apis/kubeflow.org/v1/zz_generated.deepcopy.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
  pkg/controller.v1/pytorch/hpa.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
  sdk/python/docs/KubeflowOrgV1ElasticPolicy.md
  sdk/python/docs/KubeflowOrgV1PaddleElasticPolicy.md
  sdk/python/docs/V1ReplicaStatus.md
  sdk/python/kubeflow/training/models/kubeflow_org_v1_elastic_policy.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_paddle_elastic_policy.py
  sdk/python/kubeflow/training/models/v1_replica_status.py
  sdk/python/test/test_kubeflow_org_v1_mpi_job.py
  sdk/python/test/test_kubeflow_org_v1_mpi_job_list.py
  sdk/python/test/test_kubeflow_org_v1_mx_job.py
  sdk/python/test/test_kubeflow_org_v1_mx_job_list.py
  sdk/python/test/test_kubeflow_org_v1_paddle_job.py
  sdk/python/test/test_kubeflow_org_v1_paddle_job_list.py
  sdk/python/test/test_kubeflow_org_v1_py_torch_job.py
  sdk/python/test/test_kubeflow_org_v1_py_torch_job_list.py
  sdk/python/test/test_kubeflow_org_v1_tf_job.py
  sdk/python/test/test_kubeflow_org_v1_tf_job_list.py
  sdk/python/test/test_kubeflow_org_v1_xg_boost_job.py
  sdk/python/test/test_kubeflow_org_v1_xg_boost_job_list.py
  sdk/python/test/test_v1_job_status.py
  sdk/python/test/test_v1_replica_status.py
Labels: size/XXL, lgtm, approved

#1702 Removing deprecated Job Labels
  go.mod
  go.sum
  pkg/common/util/v1/testutil/pod.go
  pkg/common/util/v1/testutil/service.go
  pkg/common/util/v1/testutil/util.go
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/tensorflow/pod_test.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/tensorflow/util_test.go
  sdk/python/kubeflow/training/utils/utils.py
Labels: size/M, lgtm, approved

#1707 fix https://github.com/kubeflow/training-operator/issues/1706
  cmd/training-operator.v1/main.go
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/mpi/suite_test.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller_suite_test.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller_suite_test.go
  pkg/controller.v1/register_controller.go
  pkg/controller.v1/tensorflow/suite_test.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: size/M, lgtm, approved

#1649 handle all restart policies
  pkg/controller.v1/tensorflow/tfjob_controller.go
Labels: size/M, lgtm, approved

#1715 chore: Update the use of MultiWorkerMirroredStrategy in TF
  examples/tensorflow/distribution_strategy/keras-API/multi_worker_strategy-with-keras.py
Labels: size/XS, lgtm, approved
