Repository kubeflow/trainer, pull requests merged in 2022-05, with the labels that each got.

#1558 Remove uncalled mpi-controller DeletePodsAndServices()
  pkg/controller.v1/mpi/mpijob_controller.go
Labels: size/S, lgtm, approved, ok-to-test

#1591 update img url in design doc
  docs/design/tf_job_design_doc.md
Labels: size/XS, lgtm, approved

#1595 chore: stop action on first fail
  .github/workflows/test-go.yaml
Labels: size/S, lgtm, approved

#1600 Add mpi in update-codegen.sh
  hack/update-codegen.sh
Labels: size/S, lgtm, approved
