Repository kubeflow/trainer, pull requests merged in 2023-08, with the labels that each got.

#1873 Upgrade Go version to v1.20
  Makefile
  build/images/training-operator/Dockerfile
  docs/development/developer_guide.md
  go.mod
  hack/swagger/go.mod
Labels: size/S, lgtm, approved

#1874 Replace Pytorch with PyTorch
  pkg/apis/kubeflow.org/v1/pytorch_defaults.go
  pkg/apis/kubeflow.org/v1/pytorch_types.go
  pkg/apis/kubeflow.org/v1/pytorch_validation.go
  pkg/controller.v1/pytorch/envvar.go
  pkg/controller.v1/pytorch/hpa.go
  pkg/controller.v1/pytorch/initcontainer.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller_test.go
  pkg/controller.v1/register_controller.go
Labels: size/L, lgtm, approved

#1875 Implement integration test for MPIJob v1 related to suspend semantics
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/mpi/mpijob_controller_test.go
  pkg/controller.v1/xgboost/xgboostjob_controller_test.go
Labels: size/L, lgtm, approved

#1879 Removing reconciler code
  pkg/reconciler.v1/common/README.md
  pkg/reconciler.v1/common/gang.go
  pkg/reconciler.v1/common/gang_scheduler_framework.go
  pkg/reconciler.v1/common/gang_volcano.go
  pkg/reconciler.v1/common/interface.go
  pkg/reconciler.v1/common/job.go
  pkg/reconciler.v1/common/pod.go
  pkg/reconciler.v1/common/pod_test.go
  pkg/reconciler.v1/common/service.go
  pkg/reconciler.v1/common/service_test.go
  pkg/reconciler.v1/common/utils.go
  pkg/reconciler.v1/common/utils_test.go
  test_job/reconciler.v1/test_job/test_job_reconciler.go
Labels: size/XXL, lgtm, approved

#1880 Update Prometheus metrics in doc
  docs/monitoring/README.md
Labels: size/M, lgtm, approved

#1881 Update latest training operator images in v1.7 branch
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
Labels: size/XS, lgtm, approved

#1886 Remove klog v1
  go.mod
  go.sum
  hack/swagger/go.mod
  hack/swagger/go.sum
  hack/swagger/main.go
  pkg/controller.v1/mpi/mpijob_controller.go
Labels: size/L, lgtm, approved

#1890 Refactor core/pod tests
  pkg/controller.v1/common/pod_test.go
Labels: size/L, lgtm, approved

#1893 Add Stale GitHub Action
  .github/stale.yml
  .github/workflows/stale.yaml
Labels: size/M, lgtm, approved

#1892 Changelog updated for 1.7.0 rc0 release
  CHANGELOG.md
Labels: size/M, lgtm, approved
