Repository kubeflow/trainer, pull requests merged in 2023-06, with the labels that each got.

#1815 Auto-generate RBAC manifests by the controller-gen
  Makefile
  manifests/base/cluster-role.yaml
  manifests/base/kustomization.yaml
  manifests/base/rbac/cluster-role-binding.yaml
  manifests/base/rbac/role.yaml
  manifests/base/rbac/service-account.yaml
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: size/L, lgtm, approved

#1824 ⚠️ Breaking Changes: Upgrade Scheduler Plugins version to v0.25.7
  .github/workflows/integration-tests.yaml
  go.mod
  go.sum
  manifests/base/rbac/role.yaml
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
  scripts/gha/setup-training-operator.sh
Labels: size/M, lgtm, approved

#1829 support make test on darwin
  Makefile
Labels: size/XS, lgtm, approved

#1826 fix comment word spelling error
  pkg/controller.v1/pytorch/hpa.go
Labels: size/XS, lgtm, approved

#1828 update volcano apis to v1.7.0
  go.mod
  go.sum
Labels: size/L, lgtm, approved

#1831 e2e testing support volcano gang-scheduler
  .github/workflows/integration-tests.yaml
  scripts/gha/setup-training-operator.sh
Labels: size/S, lgtm, approved

#1835 Add check pods are not scheduled when testing gang-scheduler integrations in e2e
  sdk/python/test/e2e/utils.py
Labels: size/S, lgtm, approved

#1804 Add default Intel MPI env variables to MPIJob
  pkg/controller.v1/mpi/mpijob.go
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/mpi/mpijob_controller_test.go
Labels: size/L, lgtm, approved

#1834 Upgrade the kubernetes dependencies to v1.27
  .github/workflows/integration-tests.yaml
  .github/workflows/unittests.yaml
  Makefile
  go.mod
  go.sum
  manifests/base/crds/kubeflow.org_mpijobs.yaml
  manifests/base/crds/kubeflow.org_mxjobs.yaml
  manifests/base/crds/kubeflow.org_paddlejobs.yaml
  manifests/base/crds/kubeflow.org_pytorchjobs.yaml
  manifests/base/crds/kubeflow.org_tfjobs.yaml
  manifests/base/crds/kubeflow.org_xgboostjobs.yaml
  pkg/client/clientset/versioned/typed/kubeflow.org/v1/fake/fake_mpijob.go
  pkg/client/clientset/versioned/typed/kubeflow.org/v1/fake/fake_mxjob.go
  pkg/client/clientset/versioned/typed/kubeflow.org/v1/fake/fake_paddlejob.go
  pkg/client/clientset/versioned/typed/kubeflow.org/v1/fake/fake_pytorchjob.go
  pkg/client/clientset/versioned/typed/kubeflow.org/v1/fake/fake_tfjob.go
  pkg/client/clientset/versioned/typed/kubeflow.org/v1/fake/fake_xgboostjob.go
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: size/XXL, lgtm, approved

#1839 remove duplicate code of add task spec annotation
  pkg/controller.v1/mpi/mpijob.go
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
Labels: kind/cleanup, size/S, lgtm, approved

#1837 fetch volcano log when e2e failed
  .github/workflows/integration-tests.yaml
Labels: size/S, lgtm, approved
