Repository kubeflow/trainer, pull requests merged in 2023-12, with the labels that each got.

#1945 Train/Fine-tune API Proposal for LLMs
  docs/proposals/train_api_proposal.md
Labels: size/L, lgtm, approved

#1954 utils changes needed to add train api
  sdk/python/kubeflow/training/api/training_client.py
  sdk/python/kubeflow/training/utils/utils.py
Labels: size/M, lgtm, approved

#1958 Train api init container creation
  sdk/python/kubeflow/storage_init_container/Dockerfile
  sdk/python/kubeflow/storage_init_container/__init__.py
  sdk/python/kubeflow/storage_init_container/abstract_model_provider.py
  sdk/python/kubeflow/storage_init_container/hugging_face.py
  sdk/python/kubeflow/storage_init_container/requirements.txt
  sdk/python/kubeflow/storage_init_container/storage.py
Labels: size/L, lgtm, approved

#1959 Train api dataset download changes
  sdk/python/kubeflow/storage_init_container/abstract_dataset_provider.py
  sdk/python/kubeflow/storage_init_container/requirements.txt
  sdk/python/kubeflow/storage_init_container/s3.py
  sdk/python/kubeflow/storage_init_container/storage.py
Labels: size/M, lgtm, approved

#1965 torchrun example with cpu version pytorch
  examples/pytorch/cpu-demo/Dockerfile
  examples/pytorch/cpu-demo/README.MD
  examples/pytorch/cpu-demo/demo.py
  examples/pytorch/cpu-demo/demo.yaml
Labels: size/M, lgtm, approved

#1969 isMaster fix
  pkg/controller.v1/pytorch/pytorchjob_controller.go
Labels: size/S, lgtm, approved
