Repository kubeflow/trainer, pull requests merged in 2023-01, with the labels that each got.

#1721 docs: Update Kubernetes requirement and version matrix
  README.md
Labels: size/XS, lgtm, approved

#1726 Fix indents on examples for tensorflow
  examples/tensorflow/simple.yaml
Labels: size/S, lgtm, approved

#1730 Fix predicates of paddlepaddle-controller for scheduling.volcano.sh/v1beta1 PodGroup
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
Labels: size/XS, lgtm, approved

#1731 Add CI to build example images
  .github/workflows/build-and-publish-images.yaml
  .github/workflows/publish-core-images.yaml
  .github/workflows/publish-example-images.yaml
  .github/workflows/publish-images.yaml
  .github/workflows/template-publish-image/action.yaml
  examples/pytorch/elastic/echo/Dockerfile
  examples/pytorch/elastic/echo/echo.yaml
  examples/pytorch/elastic/imagenet/Dockerfile
  examples/pytorch/elastic/imagenet/imagenet.yaml
  examples/pytorch/smoke-dist/Dockerfile
  examples/pytorch/smoke-dist/pytorch_job_sendrecv.yaml
  examples/tensorflow/dist-mnist/Dockerfile
  examples/tensorflow/dist-mnist/tf_job_mnist.yaml
  examples/tensorflow/distribution_strategy/estimator-API/Dockerfile
  examples/tensorflow/distribution_strategy/estimator-API/distributed_tfjob.yaml
  examples/tensorflow/distribution_strategy/keras-API/Dockerfile
  examples/tensorflow/distribution_strategy/keras-API/multi_worker_tfjob.yaml
  examples/tensorflow/mnist_with_summaries/Dockerfile
  examples/tensorflow/mnist_with_summaries/Dockerfile.ppc64le
  examples/tensorflow/mnist_with_summaries/tf_job_mnist.yaml
  examples/tensorflow/simple.yaml
  examples/tensorflow/tf_sample/Dockerfile
Labels: size/L, lgtm, approved

#1733 To fix scaledown error, upgrade PyTorch version to v1.13.1 in echo example
  examples/pytorch/elastic/echo/Dockerfile
Labels: size/XS, lgtm, approved

#1735 Trim down CRD descriptions
  Makefile
  manifests/base/crds/kubeflow.org_mpijobs.yaml
  manifests/base/crds/kubeflow.org_mxjobs.yaml
  manifests/base/crds/kubeflow.org_paddlejobs.yaml
  manifests/base/crds/kubeflow.org_pytorchjobs.yaml
  manifests/base/crds/kubeflow.org_tfjobs.yaml
  manifests/base/crds/kubeflow.org_xgboostjobs.yaml
Labels: size/XXL, lgtm, approved

#1724 Adopting coschduling plugin
  cmd/training-operator.v1/main.go
  go.mod
  go.sum
  hack/python-sdk/swagger.json
  manifests/base/cluster-role.yaml
  manifests/base/crds/kubeflow.org_mpijobs.yaml
  manifests/base/crds/kubeflow.org_mxjobs.yaml
  manifests/base/crds/kubeflow.org_paddlejobs.yaml
  manifests/base/crds/kubeflow.org_pytorchjobs.yaml
  manifests/base/crds/kubeflow.org_tfjobs.yaml
  manifests/base/crds/kubeflow.org_xgboostjobs.yaml
  pkg/apis/kubeflow.org/v1/openapi_generated.go
  pkg/apis/kubeflow.org/v1/paddlepaddle_types.go
  pkg/apis/kubeflow.org/v1/pytorch_types.go
  pkg/common/util/scheduler.go
  pkg/controller.v1/mpi/mpijob.go
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/mpi/suite_test.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/mxnet/mxnet.go
  pkg/controller.v1/mxnet/suite_test.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller_suite_test.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller_suite_test.go
  pkg/controller.v1/register_controller.go
  pkg/controller.v1/tensorflow/suite_test.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
  sdk/python/docs/V1ReplicaStatus.md
  sdk/python/docs/V1SchedulingPolicy.md
  sdk/python/kubeflow/training/models/v1_replica_status.py
  sdk/python/kubeflow/training/models/v1_scheduling_policy.py
  sdk/python/test/test_kubeflow_org_v1_mpi_job.py
  sdk/python/test/test_kubeflow_org_v1_mpi_job_list.py
  sdk/python/test/test_kubeflow_org_v1_mpi_job_spec.py
  sdk/python/test/test_kubeflow_org_v1_mx_job.py
  sdk/python/test/test_kubeflow_org_v1_mx_job_list.py
  sdk/python/test/test_kubeflow_org_v1_mx_job_spec.py
  sdk/python/test/test_kubeflow_org_v1_paddle_job.py
  sdk/python/test/test_kubeflow_org_v1_paddle_job_list.py
  sdk/python/test/test_kubeflow_org_v1_paddle_job_spec.py
  sdk/python/test/test_kubeflow_org_v1_py_torch_job.py
  sdk/python/test/test_kubeflow_org_v1_py_torch_job_list.py
  sdk/python/test/test_kubeflow_org_v1_py_torch_job_spec.py
  sdk/python/test/test_kubeflow_org_v1_tf_job.py
  sdk/python/test/test_kubeflow_org_v1_tf_job_list.py
  sdk/python/test/test_kubeflow_org_v1_tf_job_spec.py
  sdk/python/test/test_kubeflow_org_v1_xg_boost_job.py
  sdk/python/test/test_kubeflow_org_v1_xg_boost_job_list.py
  sdk/python/test/test_kubeflow_org_v1_xg_boost_job_spec.py
  sdk/python/test/test_v1_job_status.py
  sdk/python/test/test_v1_replica_status.py
  sdk/python/test/test_v1_run_policy.py
  sdk/python/test/test_v1_scheduling_policy.py
Labels: size/XXL, lgtm, approved

#1737 Fix XGBoost conditions bug
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: size/S, lgtm, approved

#1739 Add Yuki to reviewer group
  OWNERS
Labels: size/XS, lgtm, approved

#1736 Add E2E test for gang-scheduling
  .github/workflows/integration-tests.yaml
  pkg/controller.v1/mxnet/mxjob_controller.go
  scripts/gha/setup-training-operator.sh
  sdk/python/kubeflow/training/api/training_client.py
  sdk/python/kubeflow/training/constants/constants.py
  sdk/python/kubeflow/training/utils/utils.py
  sdk/python/test/e2e/constants.py
  sdk/python/test/e2e/test_e2e_mpijob.py
  sdk/python/test/e2e/test_e2e_mxjob.py
  sdk/python/test/e2e/test_e2e_paddlejob.py
  sdk/python/test/e2e/test_e2e_pytorchjob.py
  sdk/python/test/e2e/test_e2e_tfjob.py
  sdk/python/test/e2e/test_e2e_xgboostjob.py
  sdk/python/test/e2e/utils.py
Labels: size/XXL, lgtm, approved

#1740 [SDK] Use Training Client without Kube Config
  sdk/python/kubeflow/training/api/training_client.py
Labels: size/M, lgtm, approved

#1705 fix https://github.com/kubeflow/training-operator/issues/1704
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: size/S, lgtm, approved

#1742 Update latest operator image
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
Labels: size/XS, lgtm, approved
