Repository kubeflow/trainer, pull requests merged in 2023-07, with the labels that each got.

#1843 Refactoring tests in common/controller.v1
  pkg/controller.v1/common/job_test.go
  pkg/controller.v1/common/service.go
  pkg/controller.v1/common/service_test.go
  pkg/controller.v1/tensorflow/job_test.go
  pkg/controller.v1/tensorflow/tfjob_controller_test.go
  test_job/controller.v1/test_job/test_job_controller.go
Labels: size/XL, lgtm, approved

#1845 Clean up /pkg/common/util/v1
  pkg/common/util/v1/testutil/const.go
  pkg/common/util/v1/testutil/util.go
  pkg/controller.v1/tensorflow/job_test.go
  pkg/controller.v1/tensorflow/pod_test.go
  pkg/controller.v1/tensorflow/status_test.go
  pkg/controller.v1/tensorflow/testutil/pod.go
  pkg/controller.v1/tensorflow/testutil/service.go
  pkg/controller.v1/tensorflow/testutil/tfjob.go
  pkg/controller.v1/tensorflow/tfjob_controller_test.go
  pkg/controller.v1/tensorflow/util.go
  pkg/controller.v1/tensorflow/util_test.go
Labels: size/L, lgtm, approved

#1846 Set timeout and interval to all Eventually tests
  pkg/controller.v1/mpi/mpijob_controller_test.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller_test.go
  pkg/controller.v1/pytorch/pytorchjob_controller_test.go
  pkg/controller.v1/tensorflow/job_test.go
  pkg/controller.v1/tensorflow/pod_test.go
  pkg/controller.v1/tensorflow/status_test.go
  pkg/controller.v1/tensorflow/suite_test.go
  pkg/controller.v1/tensorflow/testutil/pod.go
  pkg/util/testutil/constants.go
Labels: size/L, lgtm, approved

#1847 Remove duplicated imports for pkg/apis/kubeflow.org/v1
  pkg/apis/kubeflow.org/v1/common_types.go
  pkg/common/util/reconciler.go
  pkg/common/util/reconciler_generic.go
  pkg/common/util/reconciler_test.go
  pkg/common/util/scheduler.go
  pkg/common/util/util.go
  pkg/common/util/util_test.go
  pkg/controller.v1/mpi/mpijob.go
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/mxnet/mxnet.go
  pkg/controller.v1/paddlepaddle/envvar.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller_test.go
  pkg/controller.v1/pytorch/elastic_test.go
  pkg/controller.v1/pytorch/envvar.go
  pkg/controller.v1/pytorch/initcontainer_test.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller_test.go
  pkg/controller.v1/tensorflow/job_test.go
  pkg/controller.v1/tensorflow/pod_test.go
  pkg/controller.v1/tensorflow/status_test.go
  pkg/controller.v1/tensorflow/testutil/pod.go
  pkg/controller.v1/tensorflow/testutil/service.go
  pkg/controller.v1/tensorflow/testutil/tfjob.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/tensorflow/tfjob_controller_test.go
  pkg/controller.v1/tensorflow/util.go
  pkg/controller.v1/tensorflow/util_test.go
  pkg/controller.v1/xgboost/status.go
  pkg/controller.v1/xgboost/status_test.go
  pkg/controller.v1/xgboost/xgboost.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
  pkg/reconciler.v1/common/gang_scheduler_framework.go
  pkg/reconciler.v1/common/gang_volcano.go
  pkg/reconciler.v1/common/interface.go
  pkg/reconciler.v1/common/job.go
  pkg/reconciler.v1/common/pod.go
  pkg/reconciler.v1/common/pod_test.go
  pkg/reconciler.v1/common/service.go
  pkg/reconciler.v1/common/service_test.go
  pkg/reconciler.v1/common/utils_test.go
  test_job/apis/test_job/v1/constants.go
  test_job/apis/test_job/v1/defaults.go
  test_job/apis/test_job/v1/types.go
  test_job/reconciler.v1/test_job/test_job_reconciler.go
Labels: size/XL, lgtm, approved

#1850 Fully consolidate tfjob-operator to training-operator
  pkg/common/interface.go
  pkg/controller.v1/common/pod.go
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: size/L, lgtm, approved

#1854 Use the same reasons for Condition and Event
  pkg/controller.v1/common/job.go
  pkg/controller.v1/common/pod.go
  pkg/controller.v1/mpi/mpijob.go
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/tensorflow/job_test.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/tensorflow/tfjob_controller_test.go
  pkg/controller.v1/xgboost/status.go
  pkg/controller.v1/xgboost/status_test.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
  pkg/reconciler.v1/common/job.go
  pkg/util/status.go
Labels: size/L, lgtm, approved

#1858 Make the cleanPodPolicyPointer function global
  pkg/apis/kubeflow.org/v1/defaulting_utils.go
  pkg/apis/kubeflow.org/v1/mpi_defaults.go
  pkg/apis/kubeflow.org/v1/mpi_defaults_test.go
  pkg/apis/kubeflow.org/v1/mxnet_defaults.go
  pkg/apis/kubeflow.org/v1/mxnet_defaults_test.go
  pkg/apis/kubeflow.org/v1/paddlepaddle_defautls.go
  pkg/apis/kubeflow.org/v1/pytorch_defaults.go
  pkg/apis/kubeflow.org/v1/tensorflow_defaults.go
  pkg/apis/kubeflow.org/v1/tensorflow_defaults_test.go
  pkg/apis/kubeflow.org/v1/xgboost_defaults.go
  pkg/apis/kubeflow.org/v1/xgboost_defaults_test.go
  pkg/controller.v1/mpi/mpijob_controller_test.go
  pkg/controller.v1/tensorflow/testutil/tfjob.go
  test_job/apis/test_job/v1/defaults.go
Labels: size/M, lgtm, approved

#1840 Set correct ENV for PytorchJob to support torchrun
  docs/api/kubeflow.org_v1_generated.asciidoc
  hack/python-sdk/swagger.json
  manifests/base/crds/kubeflow.org_pytorchjobs.yaml
  pkg/apis/kubeflow.org/v1/openapi_generated.go
  pkg/apis/kubeflow.org/v1/pytorch_defaults.go
  pkg/apis/kubeflow.org/v1/pytorch_defaults_test.go
  pkg/apis/kubeflow.org/v1/pytorch_types.go
  pkg/apis/kubeflow.org/v1/pytorch_validation.go
  pkg/apis/kubeflow.org/v1/pytorch_validation_test.go
  pkg/apis/kubeflow.org/v1/zz_generated.deepcopy.go
  pkg/controller.v1/pytorch/elastic.go
  pkg/controller.v1/pytorch/elastic_test.go
  pkg/controller.v1/pytorch/envvar.go
  pkg/controller.v1/pytorch/master.go
  pkg/controller.v1/pytorch/pytorchjob_controller_test.go
  sdk/python/docs/KubeflowOrgV1ElasticPolicy.md
  sdk/python/docs/KubeflowOrgV1PyTorchJobSpec.md
  sdk/python/kubeflow/training/models/kubeflow_org_v1_elastic_policy.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_py_torch_job_spec.py
  sdk/python/test/test_kubeflow_org_v1_py_torch_job.py
  sdk/python/test/test_kubeflow_org_v1_py_torch_job_list.py
  sdk/python/test/test_kubeflow_org_v1_py_torch_job_spec.py
Labels: size/L, lgtm, approved

#1860 set PYTHONUNBUFFERED to 1
  pkg/controller.v1/paddlepaddle/envvar.go
  pkg/controller.v1/pytorch/envvar.go
  pkg/controller.v1/xgboost/xgboost.go
Labels: size/XS, lgtm, approved

#1862 Make Condition and ReplicaStatus optional
  hack/python-sdk/swagger.json
  manifests/base/crds/kubeflow.org_mpijobs.yaml
  manifests/base/crds/kubeflow.org_mxjobs.yaml
  manifests/base/crds/kubeflow.org_paddlejobs.yaml
  manifests/base/crds/kubeflow.org_pytorchjobs.yaml
  manifests/base/crds/kubeflow.org_tfjobs.yaml
  manifests/base/crds/kubeflow.org_xgboostjobs.yaml
  pkg/apis/kubeflow.org/v1/common_types.go
  pkg/apis/kubeflow.org/v1/openapi_generated.go
  sdk/python/docs/KubeflowOrgV1JobStatus.md
  sdk/python/kubeflow/training/models/kubeflow_org_v1_job_status.py
  sdk/python/test/test_kubeflow_org_v1_job_status.py
Labels: size/M, lgtm, approved

#1859 Implement suspend semantics
  docs/api/kubeflow.org_v1_generated.asciidoc
  hack/python-sdk/swagger.json
  manifests/base/crds/kubeflow.org_mpijobs.yaml
  manifests/base/crds/kubeflow.org_mxjobs.yaml
  manifests/base/crds/kubeflow.org_paddlejobs.yaml
  manifests/base/crds/kubeflow.org_pytorchjobs.yaml
  manifests/base/crds/kubeflow.org_tfjobs.yaml
  manifests/base/crds/kubeflow.org_xgboostjobs.yaml
  pkg/apis/kubeflow.org/v1/common_types.go
  pkg/apis/kubeflow.org/v1/openapi_generated.go
  pkg/apis/kubeflow.org/v1/zz_generated.deepcopy.go
  pkg/controller.v1/common/job.go
  pkg/controller.v1/common/job_test.go
  pkg/controller.v1/common/pod.go
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
  pkg/controller.v1/pytorch/hpa.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller_test.go
  pkg/controller.v1/tensorflow/job_test.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/status.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
  pkg/reconciler.v1/common/job.go
  pkg/util/status.go
  pkg/util/status_test.go
  pkg/util/testutil/constants.go
  pkg/util/train/train_util.go
  pkg/util/train/train_util_test.go
  sdk/python/docs/KubeflowOrgV1RunPolicy.md
  sdk/python/kubeflow/training/models/kubeflow_org_v1_run_policy.py
  sdk/python/test/test_kubeflow_org_v1_mpi_job.py
  sdk/python/test/test_kubeflow_org_v1_mpi_job_list.py
  sdk/python/test/test_kubeflow_org_v1_mpi_job_spec.py
  sdk/python/test/test_kubeflow_org_v1_mx_job.py
  sdk/python/test/test_kubeflow_org_v1_mx_job_list.py
  sdk/python/test/test_kubeflow_org_v1_mx_job_spec.py
  sdk/python/test/test_kubeflow_org_v1_paddle_job.py
  sdk/python/test/test_kubeflow_org_v1_paddle_job_list.py
  sdk/python/test/test_kubeflow_org_v1_paddle_job_spec.py
  sdk/python/test/test_kubeflow_org_v1_py_torch_job.py
  sdk/python/test/test_kubeflow_org_v1_py_torch_job_list.py
  sdk/python/test/test_kubeflow_org_v1_py_torch_job_spec.py
  sdk/python/test/test_kubeflow_org_v1_run_policy.py
  sdk/python/test/test_kubeflow_org_v1_tf_job.py
  sdk/python/test/test_kubeflow_org_v1_tf_job_list.py
  sdk/python/test/test_kubeflow_org_v1_tf_job_spec.py
  sdk/python/test/test_kubeflow_org_v1_xg_boost_job.py
  sdk/python/test/test_kubeflow_org_v1_xg_boost_job_list.py
  sdk/python/test/test_kubeflow_org_v1_xg_boost_job_spec.py
Labels: size/XXL, lgtm, approved

#1864 Implement integration test for PaddleJob related to suspend semantics
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller_test.go
Labels: size/L, lgtm, approved

#1865 Implement integration test for MXJob related to suspend semantics
  pkg/controller.v1/mxnet/mxjob_controller_test.go
  pkg/controller.v1/mxnet/suite_test.go
Labels: size/L, lgtm, approved

#1866 Fix a bug that XGBoostJob's running condition isn't updated when the job is resumed
  pkg/controller.v1/xgboost/status.go
  pkg/controller.v1/xgboost/status_test.go
  pkg/controller.v1/xgboost/suite_test.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller_test.go
Labels: size/XL, lgtm, approved

#1867 Implement integration test for TFJob related to suspend semantics
  pkg/controller.v1/tensorflow/tfjob_controller_test.go
Labels: size/L, lgtm, approved

#1868 Fix error check that never occurs
  pkg/controller.v1/common/job.go
  pkg/controller.v1/common/pod.go
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/tensorflow/job_test.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
  pkg/reconciler.v1/common/job.go
  pkg/util/status.go
  pkg/util/status_test.go
Labels: size/L, lgtm, approved

#1869 Set up controllers using goroutines to start the manager quickly
  cmd/training-operator.v1/main.go
Labels: size/M, lgtm, approved

#1871 Upgrade scheduler-plugins version to v0.26.0
  go.mod
  go.sum
Labels: size/XS, lgtm, approved
