Repository kubeflow/trainer, pull requests merged in 2023-02, with the labels that each got.

#1748 Add validation for verifying that the CustomJob (e.g., TFJob) name meets DNS1035
  pkg/apis/kubeflow.org/v1/mxnet_validation.go
  pkg/apis/kubeflow.org/v1/mxnet_validation_test.go
  pkg/apis/kubeflow.org/v1/paddlepaddle_validation.go
  pkg/apis/kubeflow.org/v1/paddlepaddle_validation_test.go
  pkg/apis/kubeflow.org/v1/pytorch_validation.go
  pkg/apis/kubeflow.org/v1/pytorch_validation_test.go
  pkg/apis/kubeflow.org/v1/tensorflow_validation.go
  pkg/apis/kubeflow.org/v1/tensorflow_validation_test.go
  pkg/apis/kubeflow.org/v1/xgboost_validation.go
  pkg/apis/kubeflow.org/v1/xgboost_validation_test.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: size/XXL, lgtm, approved

#1752 Fix the success condition of the job in PyTorchJob's Elastic mode.
  pkg/controller.v1/pytorch/pytorchjob_controller.go
Labels: size/XS, lgtm, approved

#1754 Set the default value of CleanPodPolicy to None
  pkg/apis/kubeflow.org/v1/defaulting_utils.go
  pkg/apis/kubeflow.org/v1/mxnet_defaults.go
  pkg/apis/kubeflow.org/v1/mxnet_defaults_test.go
  pkg/apis/kubeflow.org/v1/tensorflow_defaults.go
  pkg/apis/kubeflow.org/v1/tensorflow_defaults_test.go
  pkg/apis/kubeflow.org/v1/xgboost_defaults.go
  pkg/apis/kubeflow.org/v1/xgboost_defaults_test.go
Labels: size/M, lgtm, approved

#1755 Update mpijob_controller.go
  pkg/controller.v1/mpi/mpijob_controller.go
Labels: size/XS, lgtm, approved

#1757 Cherry pick commits
  pkg/apis/kubeflow.org/v1/defaulting_utils.go
  pkg/apis/kubeflow.org/v1/mxnet_defaults.go
  pkg/apis/kubeflow.org/v1/mxnet_defaults_test.go
  pkg/apis/kubeflow.org/v1/mxnet_validation.go
  pkg/apis/kubeflow.org/v1/mxnet_validation_test.go
  pkg/apis/kubeflow.org/v1/paddlepaddle_validation.go
  pkg/apis/kubeflow.org/v1/paddlepaddle_validation_test.go
  pkg/apis/kubeflow.org/v1/pytorch_validation.go
  pkg/apis/kubeflow.org/v1/pytorch_validation_test.go
  pkg/apis/kubeflow.org/v1/tensorflow_defaults.go
  pkg/apis/kubeflow.org/v1/tensorflow_defaults_test.go
  pkg/apis/kubeflow.org/v1/tensorflow_validation.go
  pkg/apis/kubeflow.org/v1/tensorflow_validation_test.go
  pkg/apis/kubeflow.org/v1/xgboost_defaults.go
  pkg/apis/kubeflow.org/v1/xgboost_defaults_test.go
  pkg/apis/kubeflow.org/v1/xgboost_validation.go
  pkg/apis/kubeflow.org/v1/xgboost_validation_test.go
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: size/XXL, lgtm, approved

#1758 Update latest operator image in 1.6 release branch
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
Labels: size/XS, lgtm, approved

#1759 Fix Python installation in CI
  .github/workflows/integration-tests.yaml
Labels: size/XS, lgtm, approved

#1750 Update join Slack link
  README.md
Labels: size/XS, lgtm, approved

#1760 [Bugfix][SDK] pod has no metadata attr anymore in the get_job_logs() …
  sdk/python/kubeflow/training/api/training_client.py
Labels: size/XS, lgtm, approved

#1761 Cherrypick SDK fix #1707 to release branch
  sdk/python/kubeflow/training/api/training_client.py
Labels: size/XS, lgtm, approved

#1756 fix infinite loop in init-pytorch container
  cmd/training-operator.v1/main.go
  pkg/config/config.go
  pkg/controller.v1/pytorch/initcontainer.go
  pkg/controller.v1/pytorch/initcontainer_test.go
Labels: size/S, lgtm, approved
