Repository kubeflow/trainer, pull requests merged in 2023-10, with the labels that each got.

#1918 Fixing issues with providing existing service account
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/mpi/mpijob_controller_test.go
Labels: size/M, lgtm, approved

#1927 Build MXJob examples in CI
  .github/workflows/publish-example-images.yaml
  examples/mxnet/byteps/dist_gpu_v1.yaml
  examples/mxnet/mxjob_dist_v1.yaml
  examples/mxnet/train/Dockerfile
  examples/mxnet/train/mx_job_dist_gpu_v1.yaml
  examples/mxnet/tune/Dockerfile
  examples/mxnet/tune/mx_job_tune_gpu_v1.yaml
Labels: size/L, lgtm, approved

#1928 Use a community hosted image in MXJob E2E
  examples/mxnet/mxjob_dist_v1.yaml
  sdk/python/test/e2e/test_e2e_mxjob.py
Labels: size/S, lgtm, approved

#1925 ⚠️ Breaking Changes: Rename `monitoring-port` flag to `webook-server-port`
  cmd/training-operator.v1/main.go
Labels: size/XS, lgtm, approved

#1929 Check podGroup CRD for the volcano and the scheudler-plugins as default.
  cmd/training-operator.v1/main.go
Labels: size/S, lgtm, approved

#1931 Increase the root volume size on the github runner when building container images
  .github/workflows/template-publish-image/action.yaml
Labels: size/S, lgtm, approved
