Repository kubeflow/trainer, pull requests merged in 2023-05, with the labels that each got.

#1800 Set Default Replicas for MPIJob
  pkg/apis/kubeflow.org/v1/mpi_defaults.go
  pkg/apis/kubeflow.org/v1/mpi_defaults_test.go
Labels: size/L, lgtm, approved

#1798 Use Cluster instead of sparseCluster in TFJob DynamicWorker
  pkg/controller.v1/tensorflow/tensorflow.go
Labels: size/S, lgtm, approved

#1794 xgb yaml container name should be consistent with xgb job default container name
  examples/xgboost/lightgbm-dist/xgboostjob_v1_lightgbm_dist_training.yaml
  examples/xgboost/smoke-dist/xgboostjob_v1_rabit_test.yaml
  examples/xgboost/smoke-dist/xgboostjob_v1alpha1_rabit_test.yaml
  examples/xgboost/xgboost-dist/xgboostjob_v1_iris_predict.yaml
  examples/xgboost/xgboost-dist/xgboostjob_v1_iris_train.yaml
  examples/xgboost/xgboost-dist/xgboostjob_v1alpha1_iris_predict.yaml
  examples/xgboost/xgboost-dist/xgboostjob_v1alpha1_iris_predict_local.yaml
  examples/xgboost/xgboost-dist/xgboostjob_v1alpha1_iris_train.yaml
  examples/xgboost/xgboost-dist/xgboostjob_v1alpha1_iris_train_local.yaml
Labels: size/M, lgtm, approved

#1801 Improve E2E tests for the gang-scheduling
  sdk/python/test/e2e/utils.py
Labels: size/S, lgtm, approved

#1796 GetPodsForJob check the pod owner reference job uid
  pkg/common/util/util.go
  pkg/controller.v1/mpi/mpijob_controller.go
  pkg/controller.v1/mxnet/mxjob_controller.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
Labels: size/M, lgtm, approved

#1808 Fix flaky test: [It] should delete job when expired time is up
  pkg/controller.v1/tensorflow/job_test.go
Labels: size/S, lgtm, approved

#1810 Avoid to depend on local env when installing the code-generators
  hack/update-codegen.sh
Labels: size/S, lgtm, approved

#1747 Make scheduler-plugins the default gang scheduler.
  cmd/training-operator.v1/main.go
  go.mod
  go.sum
  hack/python-sdk/swagger.json
  manifests/base/crds/kubeflow.org_mpijobs.yaml
  manifests/base/crds/kubeflow.org_mxjobs.yaml
  manifests/base/crds/kubeflow.org_paddlejobs.yaml
  manifests/base/crds/kubeflow.org_pytorchjobs.yaml
  manifests/base/crds/kubeflow.org_tfjobs.yaml
  manifests/base/crds/kubeflow.org_xgboostjobs.yaml
  pkg/apis/kubeflow.org/v1/openapi_generated.go
  sdk/python/docs/V1RunPolicy.md
  sdk/python/kubeflow/training/models/v1_run_policy.py
Labels: size/M, lgtm, approved

#1817 Upgrade kubernetes dependencies to v1.26
  .github/workflows/integration-tests.yaml
  .github/workflows/unittests.yaml
  Makefile
  go.mod
  go.sum
  manifests/base/crds/kubeflow.org_mpijobs.yaml
  manifests/base/crds/kubeflow.org_mxjobs.yaml
  manifests/base/crds/kubeflow.org_paddlejobs.yaml
  manifests/base/crds/kubeflow.org_pytorchjobs.yaml
  manifests/base/crds/kubeflow.org_tfjobs.yaml
  manifests/base/crds/kubeflow.org_xgboostjobs.yaml
  pkg/client/clientset/versioned/clientset.go
  pkg/client/informers/externalversions/factory.go
  scripts/gha/setup-training-operator.sh
Labels: size/XXL, lgtm, approved
