Repository kubeflow/trainer, pull requests merged in 2023-03, with the labels that each got.

#1773 Pin the scheduler-plugins version
  scripts/gha/setup-training-operator.sh
Labels: size/XS, lgtm, approved

#1774 E2e test in k8s cluster and Namespace option
  .github/workflows/integration-tests.yaml
  hack/python-sdk/gen-sdk.sh
  sdk/python/test/conftest.py
  sdk/python/test/e2e/test_e2e_mpijob.py
  sdk/python/test/e2e/test_e2e_mxjob.py
  sdk/python/test/e2e/test_e2e_paddlejob.py
  sdk/python/test/e2e/test_e2e_pytorchjob.py
  sdk/python/test/e2e/test_e2e_tfjob.py
  sdk/python/test/e2e/test_e2e_xgboostjob.py
Labels: size/L, lgtm, approved

#1778 Disable istio-sidecar injection
  sdk/python/kubeflow/training/constants/constants.py
  sdk/python/kubeflow/training/utils/utils.py
  sdk/python/test/e2e/test_e2e_mpijob.py
  sdk/python/test/e2e/test_e2e_mxjob.py
  sdk/python/test/e2e/test_e2e_paddlejob.py
  sdk/python/test/e2e/test_e2e_pytorchjob.py
  sdk/python/test/e2e/test_e2e_tfjob.py
  sdk/python/test/e2e/test_e2e_xgboostjob.py
Labels: size/L, lgtm, approved

#1780 Containerize e2e tests for training operator conformance
  .github/workflows/publish-conformance-images.yaml
  sdk/python/Dockerfile.conformance
  sdk/python/README.md
  sdk/python/conformance/run.sh
  sdk/python/test/e2e/test_e2e_mpijob.py
  sdk/python/test/e2e/test_e2e_mxjob.py
  sdk/python/test/e2e/test_e2e_paddlejob.py
  sdk/python/test/e2e/test_e2e_pytorchjob.py
  sdk/python/test/e2e/test_e2e_tfjob.py
  sdk/python/test/e2e/test_e2e_xgboostjob.py
Labels: size/M, lgtm, approved

#1784 Find defaulter-gen in $(go env GOPATH) instead of ${GOPATH}
  hack/update-codegen.sh
Labels: size/XS, lgtm, approved

#1786 Automated cherry pick of #1773: Pin the scheduler-plugins version
  scripts/gha/setup-training-operator.sh
Labels: size/XS, lgtm, approved

#1787 make timeout configurable from e2e tests
  sdk/python/test/e2e/test_e2e_pytorchjob.py
  sdk/python/test/e2e/utils.py
Labels: size/XS, lgtm, approved

#1788 Update Changelog for 1.6 release
  CHANGELOG.md
Labels: size/L, lgtm, approved
