Repository kubeflow/trainer, pull requests merged in 2023-11, with the labels that each got.

#1941 Add @andreyvelich to Approvers
  OWNERS
Labels: size/XS, lgtm, approved

#1944 Avoid modifying log level globally
  sdk/python/kubeflow/training/api/training_client.py
  sdk/python/kubeflow/training/utils/utils.py
Labels: size/S, lgtm, approved

#1948 fix nproc env in elastic mode for pytorchjob
  pkg/controller.v1/pytorch/envvar.go
Labels: size/S, lgtm, approved

#1938 Training operator SDK unit test
  .github/workflows/test-python.yaml
  hack/python-sdk/gen-sdk.sh
  sdk/python/kubeflow/training/api/training_client_test.py
Labels: size/L, lgtm, approved

#1950 chore: pkg import only once
  pkg/controller.v1/common/job.go
  pkg/controller.v1/common/service_test.go
Labels: size/S, lgtm, approved

#1952 [fix] replace ${go env GOPATH} with $(go env GOPATH) to get the prope…
  docs/development/developer_guide.md
Labels: size/XS, lgtm, approved
