Repository kubeflow/trainer, pull requests merged in 2024-01, with the labels that each got.

#1974 Fix Master Label for PyTorchJob
  pkg/controller.v1/pytorch/pytorchjob_controller.go
Labels: size/XS, lgtm, approved

#1973 [SDK] Add information about TrainingClient logging
  sdk/python/kubeflow/training/api/training_client.py
  sdk/python/kubeflow/training/utils/utils.py
Labels: size/S, lgtm, approved

#1977 fix: volcano podgroup should has a non-empty queue name
  pkg/controller.v1/common/job.go
Labels: size/XS, lgtm, approved

#1980 Corrected Some Spelling And Grammatical Errors
  cmd/training-operator.v1/main.go
  pkg/controller.v1/common/job.go
  pkg/controller.v1/common/pod.go
  pkg/controller.v1/common/service.go
  pkg/controller.v1/pytorch/elastic.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
Labels: size/S, lgtm, approved

#1975 [SDK] Get Kubernetes Events for Job
  .flake8
  manifests/overlays/kubeflow/kubeflow-training-roles.yaml
  sdk/python/kubeflow/training/api/training_client.py
  sdk/python/kubeflow/training/constants/constants.py
  sdk/python/kubeflow/training/utils/utils.py
  sdk/python/setup.py
Labels: size/L, lgtm, approved

#1979 Add test to create PyTorchJob from func
  .github/workflows/integration-tests.yaml
  sdk/python/kubeflow/training/api/training_client_test.py
  sdk/python/test/e2e/test_e2e_mpijob.py
  sdk/python/test/e2e/test_e2e_mxjob.py
  sdk/python/test/e2e/test_e2e_paddlejob.py
  sdk/python/test/e2e/test_e2e_pytorchjob.py
  sdk/python/test/e2e/test_e2e_tfjob.py
  sdk/python/test/e2e/test_e2e_xgboostjob.py
Labels: size/M, lgtm, approved

#1963 Adding Training image needed for train api
  .github/workflows/publish-core-images.yaml
  .github/workflows/publish-example-images.yaml
  examples/sdk/train_api.ipynb
  sdk/python/kubeflow/trainer/hf_dockerfile
  sdk/python/kubeflow/trainer/hf_llm_training.py
  sdk/python/kubeflow/trainer/requirements.txt
  sdk/python/kubeflow/training/api/training_client.py
  sdk/python/kubeflow/training/utils/utils.py
Labels: size/L, lgtm, approved

#1984 train api jupyternotebook fix
  examples/sdk/train_api.ipynb
Labels: size/XS, lgtm, approved

#1985 publish trainer hugging face image
  .github/workflows/publish-core-images.yaml
  sdk/python/kubeflow/trainer/Dockerfile
  sdk/python/kubeflow/training/constants/constants.py
Labels: size/XS, lgtm, approved

#1987 Fix for Github CI to publish HF trainer image
  .github/workflows/publish-core-images.yaml
Labels: size/XS, lgtm, approved

#1988 [SDK] Fix Worker and Master templates for PyTorchJob
  .github/workflows/test-python.yaml
  docs/proposals/train_api_proposal.md
  examples/sdk/create-pytorchjob-from-func.ipynb
  sdk/python/kubeflow/training/api/training_client.py
  sdk/python/kubeflow/training/api/training_client_test.py
  sdk/python/kubeflow/training/utils/utils.py
  sdk/python/test/e2e/test_e2e_pytorchjob.py
Labels: size/L, lgtm, approved

#1990 [SDK] Add resources per worker for Create Job API
  sdk/python/kubeflow/training/api/training_client.py
  sdk/python/kubeflow/training/api/training_client_test.py
  sdk/python/kubeflow/training/constants/constants.py
  sdk/python/kubeflow/training/utils/utils.py
  sdk/python/test/e2e/test_e2e_pytorchjob.py
  sdk/python/test/e2e/utils.py
Labels: size/L, lgtm, approved

#1995 [docs] development guide update
  docs/development/developer_guide.md
Labels: size/XS, lgtm, approved
