Repository kubeflow/trainer, pull requests merged in 2024-04, with the labels that each got.

#2042 Remove Dockerfile.ppc64le of pytorch example
  examples/pytorch/mnist/Dockerfile.ppc64le
  examples/pytorch/mnist/README.md
Labels: size/S, lgtm, approved

#2043 Fix: upgrade version of crd-ref-docs, which caused panic with go v1.22
  docs/api/kubeflow.org_v1_generated.asciidoc
  hack/generate-apidoc.sh
Labels: size/L, lgtm, approved

#2046 Upgrade Go version to v1.22
  Makefile
  build/images/training-operator/Dockerfile
  docs/development/developer_guide.md
  go.mod
  go.sum
  hack/swagger/go.mod
  hack/swagger/go.sum
Labels: size/M, lgtm, approved

#2035 Implement webhook validations for the PyTorchJob
  Makefile
  cmd/training-operator.v1/main.go
  go.mod
  go.sum
  manifests/base/deployment.yaml
  manifests/base/kustomization.yaml
  manifests/base/rbac/role.yaml
  manifests/base/service.yaml
  manifests/base/webhook/kustomization.yaml
  manifests/base/webhook/kustomizeconfig.yaml
  manifests/base/webhook/manifests.yaml
  manifests/base/webhook/patch.yaml
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
  pkg/apis/kubeflow.org/v1/pytorch_validation.go
  pkg/apis/kubeflow.org/v1/pytorch_validation_test.go
  pkg/cert/cert.go
  pkg/controller.v1/pytorch/pytorchjob_controller.go
  pkg/controller.v1/pytorch/pytorchjob_controller_suite_test.go
  pkg/webhooks/pytorch/pytorchjob_webhook.go
  pkg/webhooks/pytorch/pytorchjob_webhook_test.go
  pkg/webhooks/webhooks.go
Labels: size/XXL, lgtm, approved

#2053 CI: Use a mode=min in the builder cache
  .github/workflows/template-publish-image/action.yaml
Labels: size/XS, lgtm, approved

#2051 Implement webhook validation for the TFJob
  manifests/base/webhook/manifests.yaml
  manifests/base/webhook/patch.yaml
  pkg/apis/kubeflow.org/v1/tensorflow_types.go
  pkg/apis/kubeflow.org/v1/tensorflow_types_test.go
  pkg/apis/kubeflow.org/v1/tensorflow_validation.go
  pkg/apis/kubeflow.org/v1/tensorflow_validation_test.go
  pkg/cert/cert.go
  pkg/controller.v1/tensorflow/suite_test.go
  pkg/controller.v1/tensorflow/tfjob_controller.go
  pkg/webhooks/tensorflow/tfjob_webhook.go
  pkg/webhooks/tensorflow/tfjob_webhook_test.go
  pkg/webhooks/webhooks.go
Labels: size/XL, lgtm, approved

#2052 Implement webhook validations for the XGBoostJob
  manifests/base/webhook/manifests.yaml
  manifests/base/webhook/patch.yaml
  pkg/apis/kubeflow.org/v1/xgboost_validation.go
  pkg/apis/kubeflow.org/v1/xgboost_validation_test.go
  pkg/controller.v1/xgboost/suite_test.go
  pkg/controller.v1/xgboost/xgboostjob_controller.go
  pkg/webhooks/webhooks.go
  pkg/webhooks/xgboost/xgboostjob_webhook.go
  pkg/webhooks/xgboost/xgboostjob_webhook_test.go
Labels: size/XL, lgtm, approved

#2057 Implement webhook validations for the PaddleJob
  manifests/base/webhook/manifests.yaml
  manifests/base/webhook/patch.yaml
  pkg/apis/kubeflow.org/v1/paddlepaddle_validation.go
  pkg/apis/kubeflow.org/v1/paddlepaddle_validation_test.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller.go
  pkg/controller.v1/paddlepaddle/paddlepaddle_controller_suite_test.go
  pkg/webhooks/paddlepaddle/paddlepaddle_webhook.go
  pkg/webhooks/paddlepaddle/paddlepaddle_webhook_test.go
  pkg/webhooks/webhooks.go
Labels: size/XL, lgtm, approved

#2058 Implement webhook warnings for the MXJob
  manifests/base/webhook/manifests.yaml
  manifests/base/webhook/patch.yaml
  pkg/controller.v1/mxnet/suite_test.go
  pkg/webhooks/mxnet/mxnet_webhook.go
  pkg/webhooks/webhooks.go
Labels: size/L, lgtm, approved

#2006 adding fine tune example with s3 as the dataset store
  examples/pytorch/language-modeling/train_api_hf_dataset.ipynb
  examples/pytorch/language-modeling/train_api_s3_dataset.ipynb
  sdk/python/kubeflow/storage_initializer/s3.py
Labels: size/L, lgtm, approved

#2064 fix(example): add installation of python-etcd in Pytorch example
  examples/pytorch/elastic/imagenet/Dockerfile
Labels: size/XS, lgtm, approved

#2061 Updated developer docs to include Kind
  docs/development/developer_guide.md
Labels: size/XS, lgtm, approved

#2062 fix wrong filepath in the simple example command
  examples/pytorch/simple.yaml
Labels: size/XS, lgtm, approved

#2067 PyTorchJob: Always show warnings when using elasticPolicy.nProcPerNode
  pkg/webhooks/pytorch/pytorchjob_webhook.go
  pkg/webhooks/pytorch/pytorchjob_webhook_test.go
Labels: size/M, lgtm, approved

#2065 Upgrade scheduler-plugins to v0.28.9
  go.mod
  go.sum
  hack/swagger/go.mod
  hack/swagger/go.sum
Labels: size/M, lgtm, approved

#2075 [SDK] Add docstring for Train API
  sdk/python/kubeflow/storage_initializer/hugging_face.py
  sdk/python/kubeflow/training/api/training_client.py
Labels: size/M, lgtm, approved

#2083 E2E: Replace outdated images with latest ones
  .github/workflows/build-and-publish-images.yaml
  .github/workflows/free-up-disk-space/action.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/template-publish-image/action.yaml
  examples/mpi/tensorflow-mnist.yaml
  examples/pytorch/mnist/v1/pytorch_job_mnist_gloo.yaml
  examples/pytorch/mnist/v1/pytorch_job_mnist_mpi.yaml
  examples/pytorch/mnist/v1/pytorch_job_mnist_nccl.yaml
  sdk/python/test/e2e/test_e2e_mpijob.py
  sdk/python/test/e2e/test_e2e_mxjob.py
  sdk/python/test/e2e/test_e2e_paddlejob.py
  sdk/python/test/e2e/test_e2e_pytorchjob.py
  sdk/python/test/e2e/test_e2e_tfjob.py
  sdk/python/test/e2e/test_e2e_xgboostjob.py
Labels: size/L, lgtm, approved

#2074 docs: updating docs for local development
  docs/development/developer_guide.md
Labels: size/L, lgtm, approved

#2071 Fail job for non-retryable exit codes
  pkg/controller.v1/common/pod.go
  pkg/controller.v1/tensorflow/pod_test.go
Labels: size/M, lgtm, approved

#2073 Remove deadcode related to PodDisruptionBudget
  pkg/controller.v1/common/job_controller.go
  pkg/controller.v1/common/scheduling.go
Labels: size/M, lgtm, approved

#2084 Test: Simplify and Identify pod-controller envtest
  pkg/controller.v1/tensorflow/pod_test.go
Labels: size/S, lgtm, approved

#2077 updated examples for train API
  examples/pytorch/language-modeling/train_api_hf_dataset.ipynb
  examples/pytorch/language-modeling/train_api_s3_dataset.ipynb
  examples/pytorch/text-classification/Fine-Tune-BERT-LLM.ipynb
Labels: size/S, lgtm, approved

#2085 Fix import for HuggingFace Dataset Provider
  examples/pytorch/language-modeling/train_api_hf_dataset.ipynb
  examples/pytorch/language-modeling/train_api_s3_dataset.ipynb
  examples/pytorch/text-classification/Fine-Tune-BERT-LLM.ipynb
Labels: size/S, lgtm, approved

#2089 Update training operator image to latest
  .github/workflows/unittests.yaml
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
Labels: size/XS, lgtm, approved
