Repository kubeflow/trainer, pull requests merged in 2024-03, with the labels that each got.

#2011 Fix URL in python SDK setup.py
  sdk/python/setup.py
Labels: size/XS, lgtm, approved

#2012 Fix Distributed Data Samplers in PyTorch Examples
  examples/pytorch/mnist/mnist.py
  examples/sdk/create-pytorchjob-from-func.ipynb
Labels: size/XL, lgtm, approved

#2018 publish torchrun example via Dockerfile
  .github/workflows/publish-example-images.yaml
Labels: size/XS, lgtm, approved, do-not-merge/hold

#2020 Fix build workflow config for pytorch-torchrun-example
  .github/workflows/publish-example-images.yaml
Labels: size/XS, lgtm, approved

#2021 Add Fine-Tune BERT LLM Example
  examples/pytorch/image-classification/Train CNN with FashionMNIST.ipynb
  examples/pytorch/image-classification/create-pytorchjob.ipynb
  examples/pytorch/language-modeling/train_api.ipynb
  examples/pytorch/text-classification/Fine Tune BERT LLM.ipynb
  examples/tensorflow/image-classification/create-tfjob.ipynb
  sdk/python/README.md
Labels: size/XL, lgtm, approved

#2028 Support arm64 for Hugging Face trainer
  .github/workflows/publish-core-images.yaml
  .github/workflows/template-publish-image/action.yaml
Labels: size/M, lgtm, approved

#2031 Modify LLM Trainer to support BERT and Tiny LLaMA
  .github/workflows/test-python.yaml
  examples/pytorch/image-classification/Train-CNN-with-FashionMNIST.ipynb
  examples/pytorch/text-classification/Fine Tune BERT LLM.ipynb
  examples/pytorch/text-classification/Fine-Tune-BERT-LLM.ipynb
  sdk/python/kubeflow/storage_initializer/Dockerfile
  sdk/python/kubeflow/storage_initializer/hugging_face.py
  sdk/python/kubeflow/storage_initializer/requirements.txt
  sdk/python/kubeflow/storage_initializer/s3.py
  sdk/python/kubeflow/storage_initializer/storage.py
  sdk/python/kubeflow/trainer/Dockerfile
  sdk/python/kubeflow/trainer/hf_llm_training.py
  sdk/python/kubeflow/trainer/requirements.txt
  sdk/python/kubeflow/training/api/training_client.py
  sdk/python/kubeflow/training/constants/constants.py
  sdk/python/kubeflow/training/utils/utils.py
  sdk/python/setup.py
Labels: size/XXL, lgtm, approved

#2026 fix: Upgrade controller-gen to v0.14.0
  Makefile
  manifests/base/crds/kubeflow.org_mpijobs.yaml
  manifests/base/crds/kubeflow.org_mxjobs.yaml
  manifests/base/crds/kubeflow.org_paddlejobs.yaml
  manifests/base/crds/kubeflow.org_pytorchjobs.yaml
  manifests/base/crds/kubeflow.org_tfjobs.yaml
  manifests/base/crds/kubeflow.org_xgboostjobs.yaml
Labels: size/XXL, lgtm, approved

#2038 Support K8s v1.28 and Drop K8s v1.25
  .github/workflows/integration-tests.yaml
  .github/workflows/unittests.yaml
  Makefile
  build/images/kubectl-delivery/Dockerfile
  go.mod
  go.sum
  hack/swagger/go.mod
  hack/swagger/go.sum
Labels: size/L, lgtm, approved

#2024 Upgrade PyTorchJob examples to PyTorch v2
  .github/workflows/publish-example-images.yaml
  examples/pytorch/elastic/imagenet/Dockerfile
  examples/pytorch/elastic/imagenet/imagenet.py
  examples/pytorch/mnist/Dockerfile
  examples/pytorch/mnist/Dockerfile-mpi
  examples/pytorch/mnist/mnist.py
  examples/pytorch/pytorch_cuda_docker/Dockerfile
  examples/pytorch/simple.yaml
  examples/pytorch/smoke-dist/Dockerfile
  examples/pytorch/smoke-dist/dist_sendrecv.py
Labels: size/L, lgtm, approved
