Repository kubeflow/trainer, pull requests merged in 2024-10, with the labels that each got.

#2267 [SDK] test: add unit test for list_jobs method of the training_client
  sdk/python/kubeflow/training/api/training_client_test.py
Labels: size/L, lgtm, approved

#2276 [SDK] Use torchrun to create PyTorchJob from function
  examples/pytorch/image-classification/Train-CNN-with-FashionMNIST.ipynb
  sdk/python/kubeflow/training/api/training_client.py
  sdk/python/kubeflow/training/api/training_client_test.py
  sdk/python/kubeflow/training/constants/constants.py
  sdk/python/kubeflow/training/utils/utils.py
Labels: size/XL, lgtm, approved

#2275 [SDK] test: add unit test for get_job_logs method of the training_client
  sdk/python/kubeflow/training/api/training_client_test.py
Labels: size/L, lgtm, approved

#2281 [v2alpha] Move GV related codebase
  pkg/apis/kubeflow.org/v1/groupversion_info.go
  pkg/apis/kubeflow.org/v1/register.go
  pkg/apis/kubeflow.org/v2alpha1/groupversion_info.go
  pkg/apis/kubeflow.org/v2alpha1/register.go
Labels: size/M, lgtm, approved

#2235 Add DeepSpeed Example with Pytorch Operator
  .github/workflows/publish-example-images.yaml
  examples/pytorch/deepspeed-demo/Dockerfile
  examples/pytorch/deepspeed-demo/README.md
  examples/pytorch/deepspeed-demo/pytorch_deepspeed_demo.yaml
  examples/pytorch/deepspeed-demo/requirements.txt
  examples/pytorch/deepspeed-demo/train_bert_ds.py
Labels: size/XL, lgtm, approved

#2283 KEP-2170: Rename TrainingRuntimeRef to RuntimeRef API
  docs/proposals/2170-kubeflow-training-v2/README.md
  manifests/v2/base/crds/kubeflow.org_clustertrainingruntimes.yaml
  manifests/v2/base/crds/kubeflow.org_trainingruntimes.yaml
  manifests/v2/base/crds/kubeflow.org_trainjobs.yaml
  pkg/apis/kubeflow.org/v2alpha1/openapi_generated.go
  pkg/apis/kubeflow.org/v2alpha1/trainingruntime_types.go
  pkg/apis/kubeflow.org/v2alpha1/trainjob_types.go
  pkg/apis/kubeflow.org/v2alpha1/zz_generated.deepcopy.go
  pkg/runtime.v2/core/clustertrainingruntime.go
  pkg/runtime.v2/core/clustertrainingruntime_test.go
  pkg/runtime.v2/core/trainingruntime.go
  pkg/runtime.v2/core/trainingruntime_test.go
  pkg/runtime.v2/framework/plugins/coscheduling/coscheduling.go
  pkg/runtime.v2/indexer/indexer.go
  pkg/util.v2/testing/wrapper.go
Labels: size/L, lgtm, approved

#2260 KEP-2170: Adding CEL validations on v2 TrainJob CRD
  manifests/v2/base/crds/kubeflow.org_trainjobs.yaml
  pkg/apis/kubeflow.org/v2alpha1/openapi_generated.go
  pkg/apis/kubeflow.org/v2alpha1/trainjob_types.go
  test/integration/controller.v2/trainjob_controller_test.go
Labels: size/L, lgtm, approved, ok-to-test

#2294 Upgrade Deepspeed demo dependencies
  examples/pytorch/deepspeed-demo/requirements.txt
Labels: size/XS, lgtm, approved

#2286 FSDP Example for T5 Fine-Tuning and PyTorchJob
  examples/pytorch/fsdp/fine-tune-t5-with-fsdp.ipynb
Labels: size/XL, lgtm, approved

#2296 KEP-2170: Decouple JobSet from TrainJob
  docs/proposals/2170-kubeflow-training-v2/README.md
  hack/violation_exception_v2alpha1.list
  manifests/v2/base/crds/kubeflow.org_trainjobs.yaml
  pkg/apis/kubeflow.org/v2alpha1/openapi_generated.go
  pkg/apis/kubeflow.org/v2alpha1/trainjob_types.go
  pkg/apis/kubeflow.org/v2alpha1/zz_generated.deepcopy.go
Labels: size/L, lgtm, approved

#2304 KEP-2170: Strictly verify the CRD marker validation and defaulting in the integration testings
  docs/proposals/2170-kubeflow-training-v2/README.md
  manifests/v2/base/crds/kubeflow.org_trainjobs.yaml
  pkg/apis/kubeflow.org/v2alpha1/openapi_generated.go
  pkg/apis/kubeflow.org/v2alpha1/trainjob_types.go
  pkg/util.v2/testing/errormatcher.go
  pkg/util.v2/testing/wrapper.go
  test/integration/controller.v2/trainjob_controller_test.go
Labels: size/L, lgtm, approved

#2306 KEP-2170: Initialize runtimes before the manager starts
  cmd/training-operator.v2alpha1/main.go
Labels: size/S, lgtm, approved

#2303 KEP-2170: Create model and dataset initializers
  .github/workflows/publish-core-images.yaml
  .gitignore
  cmd/initializer_v2/dataset/Dockerfile
  cmd/initializer_v2/dataset/requirements.txt
  cmd/initializer_v2/model/Dockerfile
  cmd/initializer_v2/model/requirements.txt
  pkg/initializer_v2/dataset/__main__.py
  pkg/initializer_v2/dataset/config.py
  pkg/initializer_v2/dataset/huggingface.py
  pkg/initializer_v2/model/__main__.py
  pkg/initializer_v2/model/config.py
  pkg/initializer_v2/model/huggingface.py
  pkg/initializer_v2/utils/__init__.py
  pkg/initializer_v2/utils/utils.py
Labels: size/L, lgtm, approved

#2308 KEP-2170: Implement JobSet, PlainML, and Torch Plugins
  pkg/apis/kubeflow.org/v2alpha1/trainingruntime_types.go
  pkg/apis/kubeflow.org/v2alpha1/trainjob_types.go
  pkg/constants/constants.go
  pkg/runtime.v2/core/clustertrainingruntime_test.go
  pkg/runtime.v2/core/trainingruntime.go
  pkg/runtime.v2/core/trainingruntime_test.go
  pkg/runtime.v2/framework/core/framework.go
  pkg/runtime.v2/framework/core/framework_test.go
  pkg/runtime.v2/framework/interface.go
  pkg/runtime.v2/framework/plugins/coscheduling/coscheduling.go
  pkg/runtime.v2/framework/plugins/jobset/builder.go
  pkg/runtime.v2/framework/plugins/jobset/jobset.go
  pkg/runtime.v2/framework/plugins/mpi/mpi.go
  pkg/runtime.v2/framework/plugins/plainml/plainml.go
  pkg/runtime.v2/framework/plugins/torch/torch.go
  pkg/runtime.v2/runtime.go
  pkg/runtime.v2/runtime_test.go
  pkg/util.v2/testing/wrapper.go
  test/integration/controller.v2/trainjob_controller_test.go
  test/integration/webhook.v2/clustertrainingruntime_test.go
  test/integration/webhook.v2/trainingruntime_test.go
Labels: size/XXL, lgtm, approved
