Repository kubeflow/trainer, pull requests merged in 2024-06, with the labels that each got.

#2138 Automated cherry pick of #2105: Support Python 3.11 and Drop Python 3.7 #2122: Fix Incorrect Events in get_job_logs API
  .github/workflows/integration-tests.yaml
  .github/workflows/test-python.yaml
  sdk/python/kubeflow/training/utils/utils.py
  sdk/python/setup.py
Labels: size/M, lgtm, approved

#2140 Automated cherry pick of #2109: changed package name to flake8 to fix pip install
  sdk/python/setup.py
Labels: size/XS, lgtm, approved

#2142 Update Slack Invitation
  .github/ISSUE_TEMPLATE/config.yml
  README.md
  sdk/python/kubeflow/training/api/training_client.py
Labels: size/S, lgtm, approved

#2144 [SDK] Explain Python version support cycle
  sdk/python/README.md
Labels: size/M, lgtm, approved

#2146 [SDK] Sync Transformers version for train API
  sdk/python/setup.py
Labels: size/XS, lgtm, approved

#2147 Cherry pick: [SDK] Sync Transformers version for train API (#2146)
  sdk/python/setup.py
Labels: size/XS, lgtm, approved

#2148 update volcano to v1.9.0
  go.mod
  go.sum
Labels: kind/feature, size/XS, lgtm, approved

#2152 Release Training Operator Image for v1.8.0-rc.1
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
Labels: size/XS, lgtm, approved

#2154 Add Changelog for Training Operator v1.8.0-rc.1
  CHANGELOG.md
Labels: size/S, lgtm, approved

#2153 Update release document
  docs/release/README.md
Labels: size/L, lgtm, approved
