Repository kubeflow/trainer, pull requests merged in 2024-05, with the labels that each got.

#2094 Fix isort on examples/pytorch
  examples/pytorch/cpu-demo/demo.py
  examples/pytorch/elastic/echo/echo.py
Labels: size/XS, lgtm, approved

#2098 chore(fix): isort xgboost
  examples/xgboost/lightgbm-dist/main.py
  examples/xgboost/lightgbm-dist/utils.py
  examples/xgboost/smoke-dist/tracker.py
  examples/xgboost/smoke-dist/xgboost_smoke_test.py
  examples/xgboost/xgboost-dist/local_test.py
  examples/xgboost/xgboost-dist/main.py
  examples/xgboost/xgboost-dist/predict.py
  examples/xgboost/xgboost-dist/tracker.py
  examples/xgboost/xgboost-dist/train.py
  examples/xgboost/xgboost-dist/utils.py
Labels: size/M, lgtm, approved

#2105 Support Python 3.11 and Drop Python 3.7
  .github/workflows/integration-tests.yaml
  .github/workflows/test-python.yaml
  sdk/python/setup.py
Labels: size/S, lgtm, approved

#2109 changed package name to flake8 to fix pytests pip install
  sdk/python/setup.py
Labels: size/XS, lgtm, approved

#2116 ARM64 supported in PyTorch examples
  .github/workflows/publish-example-images.yaml
Labels: size/XS, lgtm, approved

#2114 Feat: Support ARM64 platform in XGBoost examples
  .github/workflows/publish-example-images.yaml
Labels: size/XS, lgtm, approved

#2119 Support ARM64 platform in TensorFlow examples
  .github/workflows/publish-example-images.yaml
  examples/tensorflow/distribution_strategy/keras-API/Dockerfile
Labels: size/S, lgtm, approved

#2122 [SDK] Fix Incorrect Events in get_job_logs API
  sdk/python/kubeflow/training/utils/utils.py
Labels: size/S, lgtm, approved

#2123 Updated Github Action Workflows as per issue #2117
  .github/workflows/build-and-publish-images.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/template-publish-image/action.yaml
  .github/workflows/test-go.yaml
  .github/workflows/unittests.yaml
Labels: size/S, lgtm, approved

#2128 Update the images to the latest tag in master branch
  .github/workflows/unittests.yaml
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
Labels: size/XS, lgtm, approved

#2129 Add GitHub Issue Template
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: size/M, lgtm, approved

#2079 fix volcano podgroup update issue
  manifests/base/crds/kubeflow.org_mpijobs.yaml
  manifests/base/crds/kubeflow.org_mxjobs.yaml
  manifests/base/crds/kubeflow.org_paddlejobs.yaml
  manifests/base/crds/kubeflow.org_pytorchjobs.yaml
  manifests/base/crds/kubeflow.org_tfjobs.yaml
  manifests/base/crds/kubeflow.org_xgboostjobs.yaml
  pkg/apis/kubeflow.org/v1/common_types.go
  pkg/controller.v1/common/job.go
  pkg/controller.v1/pytorch/pytorchjob_controller_test.go
Labels: size/M, lgtm, approved

#2130 Refine the integration tests for the immutable PyTorchJob queueName
  pkg/controller.v1/pytorch/pytorchjob_controller_test.go
Labels: size/S, lgtm, approved

#2104 Add Changelog for Training Operator v1.8.0-rc.0
  CHANGELOG.md
  docs/release/README.md
  docs/release/changelog.py
  docs/release/release.py
  docs/release/releasing.md
Labels: size/XL, lgtm, approved
