Repository kubeflow/trainer, pull requests merged in 2025-02, with the labels that each got.

#2387 KEP-2170: Add PyTorch DDP MNIST training example
  examples/pytorch/image-classification/mnist.ipynb
Labels: size/XL, lgtm, approved

#2414 ControlPlane: Fix flaky integraion testings due to missing the latest version of object
  test/integration/controller.v2/trainjob_controller_test.go
Labels: size/XS, lgtm, approved

#2424 Fix API Group for Torch Runtime
  manifests/base/runtimes/pretraining/torch_distributed.yaml
Labels: size/XS, lgtm, approved

#2427 Nominate @Electronic-Waste as a reviewer
  OWNERS
Labels: size/XS, lgtm, approved

#2425 IntegraionTests: Waiting for expected conditions before emulate JobSet controller manager
  test/integration/controller/trainjob_controller_test.go
Labels: size/S, lgtm, approved

#2436 update migration url on readme file
  README.md
Labels: size/XS, lgtm, approved

#2394 KEP-2170: Implement MPI Plugin for Kubeflow Trainer
  api/openapi-spec/swagger.json
  go.mod
  go.sum
  manifests/base/crds/trainer.kubeflow.org_clustertrainingruntimes.yaml
  manifests/base/crds/trainer.kubeflow.org_trainingruntimes.yaml
  manifests/base/rbac/role.yaml
  manifests/base/runtimes/pretraining/kustomization.yaml
  manifests/base/runtimes/pretraining/mpi_distributed.yaml
  pkg/apis/trainer/v1alpha1/trainingruntime_types.go
  pkg/apis/trainer/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/trainer/v1alpha1/zz_generated.openapi.go
  pkg/constants/constants.go
  pkg/runtime/framework/core/framework.go
  pkg/runtime/framework/core/framework_test.go
  pkg/runtime/framework/interface.go
  pkg/runtime/framework/plugins/coscheduling/coscheduling.go
  pkg/runtime/framework/plugins/jobset/builder.go
  pkg/runtime/framework/plugins/jobset/jobset.go
  pkg/runtime/framework/plugins/mpi/mpi.go
  pkg/runtime/framework/plugins/torch/torch.go
  pkg/runtime/runtime.go
  sdk/docs/TrainerV1alpha1MPIMLPolicySource.md
  sdk/kubeflow/trainer/models/trainer_v1alpha1_mpiml_policy_source.py
Labels: size/XL, lgtm, approved

#2313 KEP: 2170: Adding cel validations on TrainingRuntime/ClusterTrainingRuntime CRDs
  manifests/base/crds/trainer.kubeflow.org_clustertrainingruntimes.yaml
  manifests/base/crds/trainer.kubeflow.org_trainingruntimes.yaml
  pkg/apis/trainer/v1alpha1/trainingruntime_types.go
  pkg/runtime/core/trainingruntime_test.go
  pkg/runtime/framework/plugins/torch/torch.go
  pkg/util/testing/wrapper.go
  test/integration/controller/trainjob_controller_test.go
  test/integration/webhooks/clustertrainingruntime_webhook_test.go
  test/integration/webhooks/trainingruntime_test.go
  test/integration/webhooks/trainingruntime_webhook_test.go
Labels: size/L, lgtm, approved

#2409 KEP-2170: Add validation to Torch `numProcPerNode` field
  api/openapi-spec/swagger.json
  manifests/base/crds/trainer.kubeflow.org_clustertrainingruntimes.yaml
  manifests/base/crds/trainer.kubeflow.org_trainingruntimes.yaml
  manifests/base/crds/trainer.kubeflow.org_trainjobs.yaml
  pkg/apis/trainer/v1alpha1/trainingruntime_types.go
  pkg/apis/trainer/v1alpha1/trainjob_types.go
  pkg/apis/trainer/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/trainer/v1alpha1/zz_generated.openapi.go
  pkg/client/applyconfiguration/trainer/v1alpha1/torchmlpolicysource.go
  pkg/client/applyconfiguration/trainer/v1alpha1/trainer.go
  pkg/runtime/core/trainingruntime_test.go
  pkg/runtime/framework/plugins/mpi/mpi.go
  pkg/runtime/framework/plugins/torch/torch.go
  pkg/util/testing/wrapper.go
  sdk/docs/TrainerV1alpha1TorchMLPolicySource.md
  sdk/docs/TrainerV1alpha1Trainer.md
  sdk/kubeflow/trainer/models/trainer_v1alpha1_torch_ml_policy_source.py
  sdk/kubeflow/trainer/models/trainer_v1alpha1_trainer.py
  test/integration/controller/trainjob_controller_test.go
  test/integration/webhooks/trainingruntime_webhook_test.go
Labels: size/L, lgtm, approved

#2423 Add 'KEP Usage' KEP and template link
  docs/proposals/README.md
Labels: size/XS, lgtm, approved

#2444 Use the correct apiVersion name
  manifests/base/runtimes/pretraining/mpi_distributed.yaml
Labels: size/XS, lgtm, approved

#2445 Upgrade jobset SDK version to v0.7.3
  sdk/pyproject.toml
Labels: size/XS, lgtm, approved

#2450 Upgrade kubernetes Go module version to 1.32
  Makefile
  go.mod
  go.sum
  manifests/base/crds/trainer.kubeflow.org_clustertrainingruntimes.yaml
  manifests/base/crds/trainer.kubeflow.org_trainingruntimes.yaml
  manifests/base/crds/trainer.kubeflow.org_trainjobs.yaml
  pkg/client/applyconfiguration/internal/internal.go
  pkg/client/applyconfiguration/trainer/v1alpha1/clustertrainingruntime.go
  pkg/client/applyconfiguration/trainer/v1alpha1/jobsettemplatespec.go
  pkg/client/applyconfiguration/trainer/v1alpha1/mlpolicy.go
  pkg/client/applyconfiguration/trainer/v1alpha1/mpimlpolicysource.go
  pkg/client/applyconfiguration/trainer/v1alpha1/podgrouppolicy.go
  pkg/client/applyconfiguration/trainer/v1alpha1/trainingruntime.go
  pkg/client/applyconfiguration/trainer/v1alpha1/trainjob.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/typed/trainer/v1alpha1/clustertrainingruntime.go
  pkg/client/clientset/versioned/typed/trainer/v1alpha1/fake/fake_clustertrainingruntime.go
  pkg/client/clientset/versioned/typed/trainer/v1alpha1/fake/fake_trainer_client.go
  pkg/client/clientset/versioned/typed/trainer/v1alpha1/fake/fake_trainingruntime.go
  pkg/client/clientset/versioned/typed/trainer/v1alpha1/fake/fake_trainjob.go
  pkg/client/clientset/versioned/typed/trainer/v1alpha1/trainer_client.go
  pkg/client/clientset/versioned/typed/trainer/v1alpha1/trainingruntime.go
  pkg/client/clientset/versioned/typed/trainer/v1alpha1/trainjob.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/trainer/v1alpha1/clustertrainingruntime.go
  pkg/client/informers/externalversions/trainer/v1alpha1/trainingruntime.go
  pkg/client/informers/externalversions/trainer/v1alpha1/trainjob.go
  pkg/client/listers/trainer/v1alpha1/clustertrainingruntime.go
  pkg/client/listers/trainer/v1alpha1/trainingruntime.go
  pkg/client/listers/trainer/v1alpha1/trainjob.go
Labels: size/XXL, lgtm, approved

#2431 KEP-2170: Use SSA to reconcile TrainJob components
  cmd/trainer-controller-manager/main.go
  go.mod
  go.sum
  manifests/base/crds/trainer.kubeflow.org_clustertrainingruntimes.yaml
  manifests/base/crds/trainer.kubeflow.org_trainingruntimes.yaml
  pkg/apply/apply.go
  pkg/controller/trainjob_controller.go
  pkg/runtime/core/clustertrainingruntime.go
  pkg/runtime/core/clustertrainingruntime_test.go
  pkg/runtime/core/trainingruntime.go
  pkg/runtime/core/trainingruntime_test.go
  pkg/runtime/framework/core/framework.go
  pkg/runtime/framework/core/framework_test.go
  pkg/runtime/framework/interface.go
  pkg/runtime/framework/plugins/coscheduling/coscheduling.go
  pkg/runtime/framework/plugins/jobset/builder.go
  pkg/runtime/framework/plugins/jobset/jobset.go
  pkg/runtime/framework/plugins/mpi/mpi.go
  pkg/runtime/framework/plugins/plainml/plainml.go
  pkg/runtime/framework/plugins/torch/torch.go
  pkg/runtime/interface.go
  pkg/runtime/runtime.go
  pkg/util/testing/runtime.go
  pkg/util/testing/wrapper.go
Labels: size/XXL, lgtm, approved

#2461 Replace Kueue PodRequests helper with core k/k one
  go.mod
  go.sum
  pkg/runtime/runtime.go
Labels: size/S, lgtm, approved
