Repository kubeflow/trainer, pull requests merged in 2025-08, with the labels that each got.

#2766 fix(examples): Update the argument for Runtime framework
  examples/deepspeed/text-summarization/T5-Fine-Tuning.ipynb
  examples/mlx/image-classification/MLX-Distributed-Mnist.ipynb
  examples/pytorch/image-classification/mnist.ipynb
  examples/pytorch/question-answering/fine-tune-distilbert.ipynb
  examples/torchtune/llama3_2/alpaca-trainjob-yaml.ipynb
Labels: size/L, lgtm, approved

#2771 fix(api): Fix license path for Kubeflow Trainer Python API
  .gitignore
  api/python_api/pyproject.toml
Labels: size/S, lgtm, approved

#2769 feat(docs): Introduce latest news to the README
  README.md
Labels: size/S, lgtm, approved

#2765 fix(docs): update KEP-2401 according to current implementation.
  docs/proposals/2401-llm-trainer-v2/README.md
Labels: size/M, lgtm, approved

#2759 feat: Add security contexts to controller managers
  charts/kubeflow-trainer/values.yaml
  manifests/base/manager/manager.yaml
Labels: size/S, lgtm, approved

#2639 feat: run workflows on `/ok-to-test` label
  .github/workflows/gh-workflow-approve.yaml
Labels: size/M, lgtm, approved

#2780 fix: update kubeflow sdk reference
  .github/workflows/test-e2e.yaml
  CONTRIBUTING.md
  examples/deepspeed/text-summarization/T5-Fine-Tuning.ipynb
  examples/mlx/image-classification/MLX-Distributed-Mnist.ipynb
  examples/pytorch/image-classification/mnist.ipynb
  examples/pytorch/question-answering/fine-tune-distilbert.ipynb
  examples/torchtune/llama3_2/alpaca-trainjob-yaml.ipynb
Labels: size/M, lgtm, approved

#2781 chore(runtimes): Update packages in DeepSpeed runtime and fix T5 example
  cmd/runtimes/deepspeed/requirements.txt
  examples/deepspeed/text-summarization/T5-Fine-Tuning.ipynb
Labels: size/XL, lgtm, approved

#2786 feat(docs): How to release Python API modules
  docs/release/README.md
Labels: size/M, lgtm, approved

#2787 fix(manifests): Add missing permissions for the RuntimeClass and LimitRange
  charts/kubeflow-trainer/templates/rbac/clusterrole.yaml
  manifests/base/rbac/role.yaml
  pkg/runtime/framework/plugins/coscheduling/coscheduling.go
Labels: size/M, lgtm, approved

#2746 fix(ci): disable `Unit and Integration Test - Go` gh action in forked repos
  .github/workflows/test-go.yaml
Labels: size/XS, lgtm, approved

#2803 chore: Remove tool.hatch.build.targets.wheel from pyproject
  api/python_api/pyproject.toml
Labels: size/XS, lgtm, approved

#2796 feat: support affinity in TrainJob pod spec overrides
  api/openapi-spec/swagger.json
  api/python_api/kubeflow_trainer_api/models/trainer_v1alpha1_pod_spec_override.py
  charts/kubeflow-trainer/crds/trainer.kubeflow.org_trainjobs.yaml
  docs/proposals/2170-kubeflow-trainer-v2/README.md
  manifests/base/crds/trainer.kubeflow.org_trainjobs.yaml
  pkg/apis/trainer/v1alpha1/trainjob_types.go
  pkg/apis/trainer/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/trainer/v1alpha1/zz_generated.openapi.go
  pkg/client/applyconfiguration/trainer/v1alpha1/podspecoverride.go
  pkg/runtime/core/trainingruntime_test.go
  pkg/util/testing/wrapper.go
Labels: size/XXL, lgtm, approved, ok-to-test

#2805 fix(api): Regenerate TrainJob CRD
  charts/kubeflow-trainer/crds/trainer.kubeflow.org_trainjobs.yaml
  manifests/base/crds/trainer.kubeflow.org_trainjobs.yaml
Labels: size/XS, lgtm, approved

#2689 feat: KEP-2432: GPU Testing for LLM Blueprints
  docs/proposals/2432-gpu-testing-on-llm-blueprints/OCI VM/bootstrap.sh
  docs/proposals/2432-gpu-testing-on-llm-blueprints/OCI VM/main.tf
  docs/proposals/2432-gpu-testing-on-llm-blueprints/OCI VM/terraform.tfvars
  docs/proposals/2432-gpu-testing-on-llm-blueprints/README.md
Labels: size/L, lgtm, approved, ok-to-test, area/gsoc

#2807 chore: deflake test to ensure runtime is created before creating trainjob
  test/integration/controller/clustertrainingruntime_controller_test.go
  test/integration/controller/trainingruntime_controller_test.go
Labels: size/XS, lgtm, approved

#2808 chore: Nominate @astefanutti as Kubeflow Trainer approver
  OWNERS
Labels: size/XS, lgtm, approved
