Repository kubeflow/trainer, pull requests merged in 2025-10, with the labels that each got.

#2875 chore(operator): Upgrade JobSet to v0.10.1
  api/openapi-spec/swagger.json
  api/python_api/kubeflow_trainer_api/models/jobset_v1alpha2_failure_policy_rule.py
  charts/kubeflow-trainer/Chart.yaml
  charts/kubeflow-trainer/crds/trainer.kubeflow.org_clustertrainingruntimes.yaml
  charts/kubeflow-trainer/crds/trainer.kubeflow.org_trainingruntimes.yaml
  go.mod
  go.sum
  hack/violation_exception_v1alpha1.list
  manifests/base/crds/trainer.kubeflow.org_clustertrainingruntimes.yaml
  manifests/base/crds/trainer.kubeflow.org_trainingruntimes.yaml
  manifests/third-party/jobset/kustomization.yaml
  pkg/apis/trainer/v1alpha1/zz_generated.openapi.go
Labels: size/L, lgtm, approved

#2876 chore(runtimes): Upgrade torchtune version to v0.6.1
  cmd/trainers/torchtune/requirements.txt
Labels: size/XS, lgtm, approved

#2643 feat(docs): KEP-2442-Support JAX Training Runtime
  docs/proposals/2442-jax-runtime-trainer-v2/README.md
  docs/proposals/2442-jax-runtime-trainer-v2/drawing.drawio.svg
Labels: size/L, lgtm, approved, area/gsoc

#2880 fix: Allow multiple podSpec overrides to target the same TargetJob
  api/openapi-spec/swagger.json
  api/python_api/kubeflow_trainer_api/models/trainer_v1alpha1_train_job_spec.py
  charts/kubeflow-trainer/crds/trainer.kubeflow.org_trainjobs.yaml
  manifests/base/crds/trainer.kubeflow.org_trainjobs.yaml
  pkg/apis/trainer/v1alpha1/trainjob_types.go
  pkg/apis/trainer/v1alpha1/zz_generated.openapi.go
  pkg/runtime/core/trainingruntime_test.go
  pkg/runtime/framework/plugins/jobset/jobset.go
  test/integration/webhooks/trainjob_test.go
Labels: size/M, lgtm, approved

#2802 feat(api): Sync TrainJob JobsStatus from JobSet ReplicatedJobsStatus
  pkg/controller/trainjob_controller.go
  pkg/runtime/core/clustertrainingruntime.go
  pkg/runtime/core/trainingruntime.go
  pkg/runtime/framework/core/framework.go
  pkg/runtime/framework/core/framework_test.go
  pkg/runtime/framework/interface.go
  pkg/runtime/framework/plugins/jobset/jobset.go
  pkg/runtime/interface.go
  pkg/util/testing/wrapper.go
  test/e2e/e2e_test.go
  test/integration/controller/trainjob_controller_test.go
  test/util/constants.go
Labels: size/XL, lgtm, approved
