Repository kubeflow/trainer, pull requests merged in 2025-03, with the labels that each got.

#2463 Bump JobSet to v0.8.0
  Makefile
  go.mod
  go.sum
  manifests/base/rbac/role.yaml
  manifests/third-party/jobset/jobset_manager_config.yaml
  manifests/third-party/jobset/kustomization.yaml
  manifests/third-party/jobset/patches/jobset_config_patch.yaml
  pkg/controller/trainjob_controller.go
  pkg/runtime/framework/plugins/coscheduling/coscheduling.go
  pkg/runtime/framework/plugins/jobset/jobset.go
  pkg/runtime/framework/plugins/mpi/mpi.go
  sdk/pyproject.toml
Labels: size/M, lgtm, approved

#2457 fix(sdk): resolve errors in deserialization
  hack/python-sdk/gen-sdk.sh
  hack/python-sdk/swagger_config.json
  sdk/docs/TrainerV1alpha1TorchElasticPolicy.md
  sdk/docs/TrainerV1alpha1TorchMLPolicySource.md
  sdk/docs/TrainerV1alpha1Trainer.md
  sdk/kubeflow/trainer/models/__init__.py
  sdk/kubeflow/trainer/models/trainer_v1alpha1_torch_elastic_policy.py
  sdk/kubeflow/trainer/models/trainer_v1alpha1_torch_ml_policy_source.py
  sdk/kubeflow/trainer/models/trainer_v1alpha1_trainer.py
Labels: size/M, lgtm, approved

#2465 fix: fix typos in script comments.
  examples/pytorch/deepspeed-demo/train_bert_ds.py
  pkg/runtime.v2/framework/core/framework_test.go
Labels: size/XS, lgtm, approved, ok-to-test

#2470 chore(test): Add E2E tests for Kubeflow Trainer
  .github/workflows/template-e2e-test/action.yaml
  .github/workflows/test-e2e.yaml
  .github/workflows/test-go.yaml
  .gitignore
  Makefile
  examples/pytorch/image-classification/mnist.ipynb
  go.mod
  go.sum
  hack/e2e-run-notebook.sh
  hack/e2e-setup-cluster.sh
  hack/tools.go
  hack/update-codegen.sh
  sdk/kubeflow/trainer/api/trainer_client.py
  sdk/kubeflow/trainer/utils/utils.py
  sdk/pyproject.toml
  test/e2e/e2e_test.go
  test/e2e/suite_test.go
  test/util/constants.go
Labels: size/XXL, lgtm, approved

#2469 Implement UTs for PlainML plugin
  pkg/runtime/core/clustertrainingruntime_test.go
  pkg/runtime/core/trainingruntime_test.go
  pkg/runtime/framework/plugins/plainml/plainml_test.go
  pkg/util/testing/wrapper.go
  test/integration/controller/trainjob_controller_test.go
Labels: size/L, lgtm, approved

#2473 chore(test): Upload artifacts from dir
  .github/workflows/test-e2e.yaml
  .gitignore
  Makefile
Labels: size/S, lgtm, approved

#2474 Add MPIMLPolicySource CRD defaulters
  manifests/base/crds/trainer.kubeflow.org_clustertrainingruntimes.yaml
  manifests/base/crds/trainer.kubeflow.org_trainingruntimes.yaml
  pkg/apis/trainer/v1alpha1/trainingruntime_types.go
  pkg/runtime/framework/plugins/plainml/plainml_test.go
  pkg/util/testing/wrapper.go
  test/integration/webhooks/trainingruntime_webhook_test.go
Labels: size/L, lgtm, approved

#2475 Use large runner for building container image
  .github/workflows/build-and-push-images.yaml
Labels: size/XS, lgtm, approved

#2476 Add dependencies to RuntimeRegistrar
  pkg/runtime/core/core.go
  pkg/runtime/core/registry.go
Labels: size/M, lgtm, approved

#2478 Store E2E manifests to artifacts directory
  .github/workflows/test-e2e.yaml
  Makefile
  hack/e2e-setup-cluster.sh
Labels: size/M, lgtm, approved

#2483 Implement MPI numProcPerNode defaulter
  api/openapi-spec/swagger.json
  manifests/base/crds/trainer.kubeflow.org_clustertrainingruntimes.yaml
  manifests/base/crds/trainer.kubeflow.org_trainingruntimes.yaml
  pkg/apis/trainer/v1alpha1/trainingruntime_types.go
  pkg/apis/trainer/v1alpha1/zz_generated.openapi.go
  sdk/kubeflow/trainer/models/trainer_v1alpha1_mpiml_policy_source.py
  test/integration/webhooks/trainingruntime_webhook_test.go
Labels: size/M, lgtm, approved

#2484 feat(controller): Integrate DependsOn API
  .github/workflows/test-e2e.yaml
  .github/workflows/test-go.yaml
  .github/workflows/test-python.yaml
  Makefile
  docs/proposals/2170-kubeflow-training-v2/README.md
  manifests/base/runtimes/pretraining/mpi_distributed.yaml
  pkg/runtime/core/clustertrainingruntime_test.go
  pkg/runtime/core/trainingruntime_test.go
  pkg/runtime/framework/plugins/jobset/builder.go
  pkg/runtime/framework/plugins/jobset/constants.go
  pkg/util/testing/wrapper.go
  sdk/kubeflow/trainer/api/trainer_client.py
  sdk/kubeflow/trainer/constants/constants.py
  sdk/kubeflow/trainer/utils/utils.py
  test/e2e/e2e_test.go
  test/integration/controller/trainjob_controller_test.go
Labels: size/L, lgtm, approved

#2481 Implement MPI plugin UTs
  pkg/runtime/framework/plugins/mpi/mpi.go
  pkg/runtime/framework/plugins/mpi/mpi_test.go
  pkg/util/testing/wrapper.go
Labels: size/L, lgtm, approved

#2487 fix(runtime): fix error label name.
  manifests/base/runtimes/pretraining/mpi_distributed.yaml
Labels: size/XS, lgtm, approved

#2486 Move TrainJob marker defaulting and validation integration tests to test/integration/webhooks pkg
  test/integration/controller/trainjob_controller_test.go
  test/integration/webhooks/trainjob_test.go
Labels: size/L, lgtm, approved

#2489 fix type in model initializer entrypoint
  cmd/initializer/model/Dockerfile
Labels: size/XS, lgtm, approved

#2410 KEP-2401: Kubeflow LLM Trainer V2
  docs/proposals/2401-llm-trainer-v2/README.md
  docs/proposals/2401-llm-trainer-v2/llm-fine-tuning-lifecycle.png
  docs/proposals/2401-llm-trainer-v2/llm-lifcycle-torchtune.png
  docs/proposals/2401-llm-trainer-v2/llm-trainer-v2-workflow.png
Labels: size/XL, lgtm, approved

#2513 KEP-2401: Refactor current `train()` API
  examples/pytorch/image-classification/mnist.ipynb
  sdk/kubeflow/trainer/__init__.py
  sdk/kubeflow/trainer/api/trainer_client.py
  sdk/kubeflow/trainer/constants/constants.py
  sdk/kubeflow/trainer/types/types.py
  sdk/kubeflow/trainer/utils/utils.py
Labels: size/L, lgtm, approved

#2493 Implemenet MPI Plugin for OpenMPI
  manifests/base/runtimes/pretraining/mpi_distributed.yaml
  pkg/apply/apply.go
  pkg/constants/constants.go
  pkg/runtime/core/clustertrainingruntime_test.go
  pkg/runtime/core/trainingruntime.go
  pkg/runtime/core/trainingruntime_test.go
  pkg/runtime/framework/core/framework.go
  pkg/runtime/framework/core/framework_test.go
  pkg/runtime/framework/interface.go
  pkg/runtime/framework/plugins/jobset/builder.go
  pkg/runtime/framework/plugins/jobset/constants.go
  pkg/runtime/framework/plugins/jobset/constants/constants.go
  pkg/runtime/framework/plugins/jobset/jobset.go
  pkg/runtime/framework/plugins/jobset/jobset_test.go
  pkg/runtime/framework/plugins/mpi/mpi.go
  pkg/runtime/framework/plugins/mpi/mpi_test.go
  pkg/runtime/framework/plugins/plainml/plainml.go
  pkg/runtime/framework/plugins/plainml/plainml_test.go
  pkg/runtime/framework/plugins/torch/torch.go
  pkg/runtime/runtime.go
  pkg/runtime/runtime_test.go
  pkg/util/testing/compare.go
  pkg/util/testing/wrapper.go
  pkg/webhooks/trainingruntime_webhook_test.go
  test/integration/controller/trainjob_controller_test.go
  test/integration/webhooks/trainingruntime_webhook_test.go
Labels: size/XXL, lgtm, approved

#2492 Fix #2407: Cap nproc_per_node based on CPU resources for PyTorch TrainJob
  pkg/runtime/core/trainingruntime_test.go
  pkg/runtime/framework/plugins/torch/torch.go
  pkg/runtime/framework/plugins/torch/torch_test.go
  sdk/kubeflow/trainer/api/trainer_client.py
  sdk/kubeflow/trainer/utils/utils.py
  test/integration/controller/trainjob_controller_test.go
Labels: size/XXL, lgtm, approved, ok-to-test

#2500 Implement E2E for OpenMPI workload
  test/e2e/e2e_test.go
Labels: size/M, lgtm, approved

#2516 KEP-2401: Create `torchtune` trainer image
  .github/workflows/build-and-push-images.yaml
  cmd/trainers/torchtune/Dockerfile
  cmd/trainers/torchtune/requirements.txt
Labels: size/S, lgtm, approved

#2521 fix: remove unused parameter name in default case of shouldUseCPU function
  pkg/runtime/framework/plugins/torch/torch.go
Labels: size/XS, lgtm, approved

#2520 Migrate Info.Trainer to Info.TemplateSpec.PodSet
  pkg/runtime/framework/core/framework_test.go
  pkg/runtime/framework/plugins/jobset/builder.go
  pkg/runtime/framework/plugins/jobset/jobset.go
  pkg/runtime/framework/plugins/plainml/plainml.go
  pkg/runtime/framework/plugins/plainml/plainml_test.go
  pkg/runtime/framework/plugins/torch/torch.go
  pkg/runtime/framework/plugins/torch/torch_test.go
  pkg/runtime/runtime.go
  pkg/runtime/runtime_test.go
Labels: size/XXL, lgtm, approved

#2307 KEP-2170: Adding validation webhook for v2 trainjob
  pkg/constants/constants.go
  pkg/controller/trainjob_controller.go
  pkg/runtime/core/clustertrainingruntime.go
  pkg/runtime/core/trainingruntime.go
  pkg/runtime/framework/core/framework.go
  pkg/runtime/framework/core/framework_test.go
  pkg/runtime/framework/interface.go
  pkg/runtime/framework/plugins/jobset/jobset.go
  pkg/runtime/framework/plugins/mpi/mpi.go
  pkg/runtime/framework/plugins/torch/torch.go
  pkg/runtime/runtime.go
  pkg/webhooks/clustertrainingruntime_webhook.go
  pkg/webhooks/setup.go
  pkg/webhooks/trainjob_webhook.go
  test/integration/controller/trainjob_controller_test.go
  test/integration/framework/framework.go
  test/integration/webhooks/clustertrainingruntime_webhook_test.go
  test/integration/webhooks/trainingruntime_webhook_test.go
  test/integration/webhooks/trainjob_test.go
Labels: size/L, lgtm, approved

#2455 [feature] migrate images to ghcr
  .github/workflows/build-and-push-images.yaml
Labels: size/M, lgtm, approved

#2529 [feature] pull images in manifest from ghcr
  manifests/base/manager/manager.yaml
  manifests/overlays/manager/kustomization.yaml
Labels: size/XS, lgtm, approved

#2530 [hotfix] fix docker cred
  .github/workflows/build-and-push-images.yaml
Labels: size/XS, lgtm, approved

#2524 Migrate InfoOptions.podSpecReplias and info.Scheduler.TotalRequests to info.TemplateSpec.PodSet
  pkg/runtime/core/trainingruntime.go
  pkg/runtime/framework/core/framework_test.go
  pkg/runtime/framework/plugins/coscheduling/coscheduling.go
  pkg/runtime/framework/plugins/jobset/jobset.go
  pkg/runtime/framework/plugins/mpi/mpi.go
  pkg/runtime/framework/plugins/mpi/mpi_test.go
  pkg/runtime/framework/plugins/plainml/plainml.go
  pkg/runtime/framework/plugins/plainml/plainml_test.go
  pkg/runtime/framework/plugins/torch/torch.go
  pkg/runtime/framework/plugins/torch/torch_test.go
  pkg/runtime/runtime.go
  pkg/runtime/runtime_test.go
Labels: size/XL, lgtm, approved

#2531 [hotfix] fix checkout on workflow
  .github/workflows/build-and-push-images.yaml
Labels: size/XS, lgtm, approved

#2535 fix(test): Update images for DockerHub publish
  .github/workflows/build-and-push-images.yaml
Labels: size/XS, lgtm, approved

#2536 fix(doc): Update `train()` API in KEP-2401
  docs/proposals/2401-llm-trainer-v2/README.md
Labels: size/M, lgtm, approved

#2537 [feature] merge GHCR and DockerHub CI jobs
  .github/workflows/build-and-push-images.yaml
Labels: size/M, lgtm, approved

#2540 chore: Enable GCI for golangci-lint
  .golangci.yaml
  pkg/controller/trainjob_controller.go
  pkg/runtime/framework/plugins/mpi/mpi.go
  pkg/runtime/framework/plugins/mpi/mpi_test.go
  pkg/runtime/framework/plugins/torch/torch.go
  pkg/runtime/runtime_test.go
  pkg/util/testing/compare.go
  pkg/util/testing/wrapper.go
Labels: size/M, lgtm, approved

#2539 Store the TrainingRuntime numNodes as runtime.Info.PodSet.Count
  pkg/runtime/core/clustertrainingruntime.go
  pkg/runtime/core/trainingruntime.go
  pkg/runtime/core/trainingruntime_test.go
  pkg/runtime/framework/core/framework_test.go
  pkg/runtime/framework/plugins/coscheduling/coscheduling.go
  pkg/runtime/framework/plugins/jobset/builder.go
  pkg/runtime/framework/plugins/jobset/jobset.go
  pkg/runtime/framework/plugins/jobset/jobset_test.go
  pkg/runtime/framework/plugins/mpi/mpi.go
  pkg/runtime/framework/plugins/mpi/mpi_test.go
  pkg/runtime/framework/plugins/plainml/plainml.go
  pkg/runtime/framework/plugins/plainml/plainml_test.go
  pkg/runtime/framework/plugins/torch/torch.go
  pkg/runtime/framework/plugins/torch/torch_test.go
  pkg/runtime/runtime.go
  pkg/runtime/runtime_test.go
  pkg/util/testing/wrapper.go
  test/integration/controller/trainjob_controller_test.go
  test/integration/webhooks/trainingruntime_webhook_test.go
Labels: size/XL, lgtm, approved

#2541 fix(sdk): add missing import type Initializer.
  sdk/kubeflow/trainer/__init__.py
Labels: size/XS, lgtm, approved

#2491 Push images to GHCR for release-1.9
  .github/workflows/build-and-publish-images.yaml
  .github/workflows/publish-core-images.yaml
Labels: size/M, lgtm, approved, ok-to-test

#2546 fix(ci): Change publish dir from `training` to `trainer`
  .github/workflows/build-and-publish-images.yaml
Labels: size/XS, lgtm, approved

#2548 Construct Trainer based on trainer.kubeflow.org/trainjob-ancestor-step label
  hack/e2e-setup-cluster.sh
  manifests/base/runtimes/pretraining/mpi_distributed.yaml
  manifests/base/runtimes/pretraining/torch_distributed.yaml
  pkg/constants/constants.go
  pkg/runtime/core/clustertrainingruntime_test.go
  pkg/runtime/core/trainingruntime.go
  pkg/runtime/core/trainingruntime_test.go
  pkg/runtime/framework/core/framework_test.go
  pkg/runtime/framework/plugins/jobset/builder.go
  pkg/runtime/framework/plugins/jobset/jobset.go
  pkg/runtime/framework/plugins/jobset/jobset_test.go
  pkg/runtime/framework/plugins/mpi/mpi.go
  pkg/runtime/framework/plugins/mpi/mpi_test.go
  pkg/runtime/framework/plugins/plainml/plainml.go
  pkg/runtime/framework/plugins/plainml/plainml_test.go
  pkg/runtime/framework/plugins/torch/torch.go
  pkg/runtime/framework/plugins/torch/torch_test.go
  pkg/runtime/runtime.go
  pkg/runtime/runtime_test.go
  pkg/util/testing/wrapper.go
  pkg/webhooks/trainingruntime_webhook_test.go
  test/integration/controller/trainjob_controller_test.go
  test/integration/webhooks/trainingruntime_webhook_test.go
Labels: size/XL, lgtm, approved

#2545 feat(sdk): Support MPI-based TrainJobs
  docs/proposals/2401-llm-trainer-v2/README.md
  examples/pytorch/image-classification/mnist.ipynb
  manifests/base/runtimes/kustomization.yaml
  manifests/base/runtimes/mpi_distributed.yaml
  manifests/base/runtimes/torch_distributed.yaml
  manifests/overlays/runtimes/kustomization.yaml
  pkg/constants/constants.go
  pkg/runtime/core/clustertrainingruntime_test.go
  pkg/runtime/core/trainingruntime_test.go
  pkg/runtime/framework/plugins/jobset/builder.go
  pkg/runtime/framework/plugins/jobset/jobset_test.go
  pkg/runtime/framework/plugins/mpi/mpi.go
  pkg/runtime/framework/plugins/mpi/mpi_test.go
  pkg/util/testing/wrapper.go
  sdk/kubeflow/trainer/api/trainer_client.py
  sdk/kubeflow/trainer/constants/constants.py
  sdk/kubeflow/trainer/types/types.py
  sdk/kubeflow/trainer/utils/utils.py
  test/integration/controller/trainjob_controller_test.go
  test/integration/webhooks/trainingruntime_webhook_test.go
Labels: size/XXL, lgtm, approved

#2533 feat: add replicatedJobs.replicas validations in validateReplicatedJobs function.
  pkg/util/testing/wrapper.go
  pkg/webhooks/trainingruntime_webhook.go
  pkg/webhooks/trainingruntime_webhook_test.go
Labels: size/M, lgtm, approved

#2552 fix(sdk): Using correct entrypoint for mpirun
  sdk/kubeflow/trainer/api/trainer_client.py
  sdk/kubeflow/trainer/constants/constants.py
  sdk/kubeflow/trainer/types/types.py
  sdk/kubeflow/trainer/utils/utils.py
Labels: size/M, lgtm, approved

#2557 Retrieve JobSetSpec from runtime.Info in CustomValidations
  pkg/runtime/core/clustertrainingruntime.go
  pkg/runtime/core/trainingruntime.go
  pkg/runtime/framework/core/framework.go
  pkg/runtime/framework/core/framework_test.go
  pkg/runtime/framework/interface.go
  pkg/runtime/framework/plugins/jobset/jobset.go
  pkg/runtime/framework/plugins/mpi/mpi.go
  pkg/runtime/framework/plugins/torch/torch.go
Labels: size/M, lgtm, approved

#2566 fix(sdk): Add missing import types.
  sdk/kubeflow/trainer/__init__.py
Labels: size/XS, lgtm, approved

#2558 feat(runtime): remove needless Launcher chainer.
  pkg/runtime/core/trainingruntime_test.go
  pkg/runtime/framework/plugins/jobset/builder.go
  pkg/runtime/framework/plugins/jobset/jobset.go
  pkg/util/testing/wrapper.go
  test/integration/controller/trainjob_controller_test.go
Labels: size/S, lgtm, approved

#2512 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/L, lgtm, approved

#2544 Update Manifest Images to GHCR
  .github/workflows/build-and-publish-images.yaml
  Makefile
  examples/jax/cpu-demo/demo.yaml
  examples/jax/jax-dist-spmd-mnist/jaxjob_dist_spmd_mnist_gloo.yaml
  examples/pytorch/deepspeed-demo/pytorch_deepspeed_demo.yaml
  examples/pytorch/elastic/echo/echo.yaml
  examples/pytorch/elastic/imagenet/imagenet.yaml
  examples/pytorch/image-classification/create-pytorchjob.ipynb
  examples/pytorch/mnist/v1/pytorch_job_mnist_gloo.yaml
  examples/pytorch/mnist/v1/pytorch_job_mnist_mpi.yaml
  examples/pytorch/mnist/v1/pytorch_job_mnist_nccl.yaml
  examples/pytorch/smoke-dist/pytorch_job_sendrecv.yaml
  examples/tensorflow/dist-mnist/tf_job_mnist.yaml
  examples/tensorflow/distribution_strategy/multi_worker_tfjob.yaml
  examples/tensorflow/mnist_with_summaries/tf_job_mnist.yaml
  examples/tensorflow/simple.yaml
  examples/xgboost/lightgbm-dist/xgboostjob_v1_lightgbm_dist_training.yaml
  examples/xgboost/smoke-dist/xgboostjob_v1_rabit_test.yaml
  examples/xgboost/smoke-dist/xgboostjob_v1alpha1_rabit_test.yaml
  examples/xgboost/xgboost-dist/xgboostjob_v1_iris_predict.yaml
  examples/xgboost/xgboost-dist/xgboostjob_v1_iris_predict_local.yaml
  examples/xgboost/xgboost-dist/xgboostjob_v1_iris_train.yaml
  examples/xgboost/xgboost-dist/xgboostjob_v1_iris_train_local.yaml
  examples/xgboost/xgboostjob.yaml
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
  pkg/config/config.go
  scripts/setup-training-operator.sh
  sdk/python/kubeflow/training/constants/constants.py
Labels: size/M

#2567 Release Training SDK 1.9.1
  hack/python-sdk/gen-sdk.sh
  hack/python-sdk/swagger.json
  hack/python-sdk/swagger_config.json
  sdk/python/kubeflow/training/__init__.py
  sdk/python/kubeflow/training/api_client.py
  sdk/python/kubeflow/training/configuration.py
  sdk/python/kubeflow/training/exceptions.py
  sdk/python/kubeflow/training/models/__init__.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_elastic_policy.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_jax_job.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_jax_job_list.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_jax_job_spec.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_job_condition.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_job_status.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_mpi_job.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_mpi_job_list.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_mpi_job_spec.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_paddle_elastic_policy.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_paddle_job.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_paddle_job_list.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_paddle_job_spec.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_py_torch_job.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_py_torch_job_list.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_py_torch_job_spec.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_rdzv_conf.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_replica_spec.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_replica_status.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_run_policy.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_scheduling_policy.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_tf_job.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_tf_job_list.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_tf_job_spec.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_xg_boost_job.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_xg_boost_job_list.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_xg_boost_job_spec.py
  sdk/python/kubeflow/training/rest.py
  sdk/python/setup.py
Labels: size/M, lgtm, approved

#2559 feat(runtimes): Support DeepSpeed Runtime with OpenMPI
  .github/workflows/build-and-push-images.yaml
  cmd/runtimes/deepspeed/Dockerfile
  cmd/runtimes/deepspeed/requirements.txt
  examples/deepspeed/text-summarization/T5-Fine-Tuning.ipynb
  manifests/base/runtimes/deepspeed_distributed.yaml
  manifests/base/runtimes/kustomization.yaml
  sdk/kubeflow/trainer/api/trainer_client.py
  sdk/kubeflow/trainer/constants/constants.py
  sdk/kubeflow/trainer/types/types.py
  sdk/kubeflow/trainer/utils/utils.py
Labels: size/XXL, lgtm, approved

#2568 Release Training Operator Image for v1.9.1
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
Labels: size/XS, lgtm, approved

#2501 feat(doc): add Runtime API design in KEP-2401.
  docs/proposals/2401-llm-trainer-v2/README.md
Labels: size/M, lgtm, approved

#2560 test(runtime): add UT for torch runtime valid function.
  pkg/runtime/core/trainingruntime_test.go
  pkg/runtime/framework/plugins/plainml/plainml_test.go
  pkg/runtime/framework/plugins/torch/torch.go
  pkg/runtime/framework/plugins/torch/torch_test.go
  pkg/util/testing/wrapper.go
  test/integration/controller/trainjob_controller_test.go
Labels: size/L, lgtm, approved

#2561 docs: update CONTRIBUTING.md for Kubeflow Trainer V2
  CONTRIBUTING.md
Labels: size/S, lgtm, approved

#2569 chore(docs): Update Slack channel
  README.md
Labels: size/XS, lgtm, approved

#2565 feat(runtimes): Support MLX Distributed Runtime with OpenMPI
  .github/workflows/build-and-push-images.yaml
  cmd/runtimes/deepspeed/Dockerfile
  cmd/runtimes/mlx/Dockerfile
  examples/deepspeed/text-summarization/T5-Fine-Tuning.ipynb
  examples/mlx/image-classification/MLX-Distributed-Mnist.ipynb
  manifests/base/runtimes/kustomization.yaml
  manifests/base/runtimes/mlx_distributed.yaml
  sdk/kubeflow/trainer/types/types.py
  sdk/kubeflow/trainer/utils/utils.py
Labels: size/XL, lgtm, approved

#2555 Implement CustomValidation UT for MPI plugin
  pkg/runtime/framework/plugins/mpi/mpi.go
  pkg/runtime/framework/plugins/mpi/mpi_test.go
Labels: size/L, lgtm, approved

#2570 Fix MPI Test runnable errors
  pkg/runtime/framework/plugins/mpi/mpi_test.go
Labels: size/XS, lgtm, approved

#2573 chore(docs): Add Training Operator 1.9.1 Changelog
  CHANGELOG.md
Labels: size/S, lgtm, approved

#2578 Add PodNetwork plugin to KEP-2170 Job Pipeline Framework description
  docs/proposals/2170-kubeflow-trainer-v2/README.md
  docs/proposals/2170-kubeflow-trainer-v2/TrainerPipelineFramework.drawio.svg
Labels: size/XS, lgtm, approved
