Repository kubeflow/trainer, pull requests merged in 2025-07, with the labels that each got.

#2670 feat(example): Add alpaca-trianjob-yaml.ipynb.
  examples/torchtune/llama3_2/alpaca-trainjob-yaml.ipynb
Labels: size/L, lgtm, approved

#2702 [cherry-pick] feat(example): Add alpaca-trianjob-yaml.ipynb. (#2670)
  examples/torchtune/llama3_2/alpaca-trainjob-yaml.ipynb
Labels: size/L, lgtm, approved

#2703 chore: Copy generated CRDs into Helm charts
  Makefile
  charts/kubeflow-trainer/crds/trainer.kubeflow.org_trainjobs.yaml
Labels: size/L, lgtm, approved

#2700 feat: Add schedulingGates to PodSpecOverrides
  api/openapi-spec/swagger.json
  api/python_api/kubeflow_trainer_api/models/trainer_v1alpha1_pod_spec_override.py
  charts/kubeflow-trainer/crds/trainer.kubeflow.org_trainjobs.yaml
  manifests/base/crds/trainer.kubeflow.org_trainjobs.yaml
  pkg/apis/trainer/v1alpha1/trainjob_types.go
  pkg/apis/trainer/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/trainer/v1alpha1/zz_generated.openapi.go
  pkg/client/applyconfiguration/trainer/v1alpha1/podspecoverride.go
  pkg/runtime/core/trainingruntime_test.go
  pkg/util/testing/wrapper.go
Labels: size/XL, lgtm, approved

#2710 chore(docs): Update Release Guide
  docs/release/README.md
Labels: size/L, lgtm, approved

#2709 chore(docs): Add Changelog for v2.0.0-rc.1
  CHANGELOG.md
Labels: size/M, lgtm, approved

#2718 feat(docs): Guide to report security vulnerability
  SECURITY.md
Labels: size/M, lgtm, approved

#2731 fix(manifests): add rbac config of events for event recorders
  charts/kubeflow-trainer/templates/rbac/clusterrole.yaml
  manifests/base/rbac/role.yaml
  pkg/controller/trainjob_controller.go
Labels: size/S, lgtm, approved

#2724 chore(ci): Add GitHub action to verify PR titles
  .github/workflows/check-pr-title.yaml
  CONTRIBUTING.md
Labels: size/L, lgtm, approved

#2734 feat(operator): force trainjob name to be compliant with RFC 1035 for jobset
  pkg/webhooks/trainjob_webhook.go
  pkg/webhooks/trainjob_webhook_test.go
Labels: size/L, lgtm, approved

#2738 Release Training SDK 1.9.3
  hack/python-sdk/gen-sdk.sh
  hack/python-sdk/swagger.json
  hack/python-sdk/swagger_config.json
  sdk/python/kubeflow/training/__init__.py
  sdk/python/kubeflow/training/api_client.py
  sdk/python/kubeflow/training/configuration.py
  sdk/python/kubeflow/training/exceptions.py
  sdk/python/kubeflow/training/models/__init__.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_elastic_policy.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_jax_job.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_jax_job_list.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_jax_job_spec.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_job_condition.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_job_status.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_mpi_job.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_mpi_job_list.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_mpi_job_spec.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_paddle_elastic_policy.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_paddle_job.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_paddle_job_list.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_paddle_job_spec.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_py_torch_job.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_py_torch_job_list.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_py_torch_job_spec.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_rdzv_conf.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_replica_spec.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_replica_status.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_run_policy.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_scheduling_policy.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_tf_job.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_tf_job_list.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_tf_job_spec.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_xg_boost_job.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_xg_boost_job_list.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_xg_boost_job_spec.py
  sdk/python/kubeflow/training/rest.py
  sdk/python/setup.py
Labels: size/M, lgtm, approved

#2739 chore: update github runners to oci gh arc runners
  .github/workflows/build-and-push-images.yaml
  .github/workflows/test-e2e.yaml
Labels: size/XS, lgtm, approved

#2740 Release Training Operator Image for v1.9.3
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
Labels: size/XS, lgtm, approved

#2743 chore(docs): Add Changelog for Kubeflow Trainer v2.0.0
  CHANGELOG.md
Labels: size/L, lgtm, approved

#2748 feat(docs): Kubeflow Trainer ROADMAP 2025
  ROADMAP.md
Labels: size/M, lgtm, approved
