Repository kubeflow/trainer, pull requests merged in 2025-05, with the labels that each got.

#2608 Implement trainer.kubeflow.org/resource-in-use finalizer mechanism to TrainingRuntime
  manifests/base/rbac/role.yaml
  pkg/constants/constants.go
  pkg/controller/setup.go
  pkg/controller/trainingruntime_controller.go
  pkg/controller/trainingruntime_controller_test.go
  pkg/controller/trainjob_controller.go
  pkg/runtime/framework/plugins/coscheduling/coscheduling.go
  pkg/runtime/framework/plugins/jobset/jobset.go
  pkg/runtime/framework/plugins/mpi/mpi.go
  pkg/runtime/indexer/indexer.go
  pkg/util/testing/compare.go
  pkg/util/testing/wrapper.go
  pkg/util/trainjob/trainjob.go
  pkg/util/trainjob/trainjob_test.go
  test/integration/controller/trainingruntime_controller_test.go
Labels: size/XL, lgtm, approved

#2625 Implement trainer.kubeflow.org/resource-in-use finalizer mechanism to ClusterTrainingRuntime
  manifests/base/rbac/role.yaml
  pkg/controller/clustertrainingruntime_controller.go
  pkg/controller/clustertrainingruntime_controller_test.go
  pkg/controller/setup.go
  pkg/util/testing/wrapper.go
  pkg/util/trainjob/trainjob.go
  pkg/util/trainjob/trainjob_test.go
  test/integration/controller/clustertrainingruntime_controller_test.go
Labels: size/XL, lgtm, approved

#2612 Add provision to provide labels and annotations for the pytorchjob an…
  sdk/python/kubeflow/training/api/training_client.py
  sdk/python/kubeflow/training/api/training_client_test.py
  sdk/python/kubeflow/training/utils/utils.py
Labels: size/M, lgtm, approved

#2621 Remove TrainJobCreated condition
  docs/proposals/2170-kubeflow-trainer-v2/README.md
  pkg/apis/trainer/v1alpha1/trainjob_types.go
  pkg/constants/constants.go
  pkg/controller/trainjob_controller.go
  sdk/kubeflow/trainer/api/trainer_client.py
  sdk/kubeflow/trainer/constants/constants.py
  test/e2e/e2e_test.go
  test/integration/controller/trainjob_controller_test.go
Labels: size/L, lgtm, approved

#2633 Release Training SDK 1.9.2
  hack/python-sdk/gen-sdk.sh
  hack/python-sdk/swagger.json
  hack/python-sdk/swagger_config.json
  sdk/python/kubeflow/training/__init__.py
  sdk/python/kubeflow/training/api_client.py
  sdk/python/kubeflow/training/configuration.py
  sdk/python/kubeflow/training/exceptions.py
  sdk/python/kubeflow/training/models/__init__.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_elastic_policy.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_jax_job.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_jax_job_list.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_jax_job_spec.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_job_condition.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_job_status.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_mpi_job.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_mpi_job_list.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_mpi_job_spec.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_paddle_elastic_policy.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_paddle_job.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_paddle_job_list.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_paddle_job_spec.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_py_torch_job.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_py_torch_job_list.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_py_torch_job_spec.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_rdzv_conf.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_replica_spec.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_replica_status.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_run_policy.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_scheduling_policy.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_tf_job.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_tf_job_list.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_tf_job_spec.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_xg_boost_job.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_xg_boost_job_list.py
  sdk/python/kubeflow/training/models/kubeflow_org_v1_xg_boost_job_spec.py
  sdk/python/kubeflow/training/rest.py
  sdk/python/setup.py
Labels: size/M, lgtm, approved

#2634 Release Training Operator Image for v1.9.2
  manifests/overlays/kubeflow/kustomization.yaml
  manifests/overlays/standalone/kustomization.yaml
Labels: size/XS, lgtm, approved

#2635 chore(docs): Add Training Operator v1.9.2 Changelog
  CHANGELOG.md
Labels: size/S, lgtm, approved

#2580 Add question-answer example for v2 trainer
  .github/workflows/test-e2e.yaml
  examples/pytorch/question-answering/fine-tune-distilbert.ipynb
Labels: size/XL, lgtm, approved, ok-to-test

#2590 KEP-2401: Create LLM Training Runtimes for Llama 3.2 model family
  manifests/base/runtimes/torchtune/kustomization.yaml
  manifests/base/runtimes/torchtune/llama3_2/llama3_2_1B.yaml
  manifests/base/runtimes/torchtune/llama3_2/llama3_2_3B.yaml
  manifests/overlays/runtimes/kustomization.yaml
Labels: size/L, lgtm, approved

#2642 [chore] update stale action version to latest
  .github/workflows/github-stale.yaml
Labels: size/XS, lgtm, approved

#2646 fix(sdk): Fix type annotation for `train` method's `trainer` parameter
  sdk/kubeflow/trainer/api/trainer_client.py
Labels: size/XS, lgtm, approved

#2647 fix(sdk): Fix bad arg passed to `get_args_using_torchtune_config`
  sdk/kubeflow/trainer/utils/utils.py
Labels: size/XS, lgtm, approved

#2651 Revert "fix(sdk): Fix type annotation for `train` method's `trainer` parameter"
  sdk/kubeflow/trainer/api/trainer_client.py
Labels: size/XS, lgtm, approved
