Repository kubeflow/trainer, pull requests merged in 2025-09, with the labels that each got.

#2813 fix(examples): Update get_job_logs() API in examples
  examples/deepspeed/text-summarization/T5-Fine-Tuning.ipynb
  examples/mlx/image-classification/mnist.ipynb
  examples/mlx/language-modeling/fine-tune-llama.ipynb
  examples/pytorch/image-classification/mnist.ipynb
  examples/pytorch/question-answering/fine-tune-distilbert.ipynb
Labels: size/XXL, lgtm, approved

#2815 fix: update examples to reflect func_args now being unpacked
  examples/deepspeed/text-summarization/T5-Fine-Tuning.ipynb
  examples/mlx/image-classification/mnist.ipynb
  examples/mlx/language-modeling/fine-tune-llama.ipynb
  examples/pytorch/question-answering/fine-tune-distilbert.ipynb
Labels: size/M, lgtm, approved, ok-to-test-gpu-runner

#2806 feat: support imagePullSecrets in TrainJob pod spec overrides
  api/openapi-spec/swagger.json
  api/python_api/kubeflow_trainer_api/models/trainer_v1alpha1_pod_spec_override.py
  charts/kubeflow-trainer/crds/trainer.kubeflow.org_trainjobs.yaml
  docs/proposals/2170-kubeflow-trainer-v2/README.md
  manifests/base/crds/trainer.kubeflow.org_trainjobs.yaml
  pkg/apis/trainer/v1alpha1/trainjob_types.go
  pkg/apis/trainer/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/trainer/v1alpha1/zz_generated.openapi.go
  pkg/client/applyconfiguration/trainer/v1alpha1/podspecoverride.go
  pkg/runtime/core/trainingruntime_test.go
  pkg/util/testing/wrapper.go
Labels: size/L, lgtm, approved

#2818 feat: add HF token and allow gpu workflow to run from pull request target
  .github/workflows/test-e2e-gpu.yaml
Labels: size/XS, lgtm, approved

#2823 chore(runtimes): update torchtune CTRs with multiple dependson feature in jobset v0.9.0
  manifests/base/runtimes/torchtune/llama3_2/llama3_2_1B.yaml
  manifests/base/runtimes/torchtune/llama3_2/llama3_2_3B.yaml
Labels: size/S, lgtm, approved, ok-to-test-gpu-runner

#2835 feat: qwen 2.5 1.5b runtime, example and fix gpu e2e test
  .github/workflows/test-e2e-gpu.yaml
  examples/torchtune/qwen2_5/qwen2.5-1.5B-with-alpaca.ipynb
  hack/e2e-setup-gpu-cluster.sh
  manifests/base/runtimes/torchtune/kustomization.yaml
  manifests/base/runtimes/torchtune/qwen2_5/qwen2_5_1.5B.yaml
  pkg/constants/constants.go
  pkg/initializers/model/huggingface.py
  pkg/initializers/model/huggingface_test.py
Labels: size/L, lgtm, approved, ok-to-test-gpu-runner

#2755 feat: KEP-2655: Add data cache system
  .github/workflows/check-pr-title.yaml
  .gitignore
  .pre-commit-config.yaml
  cmd/data_cache/Dockerfile
  hack/data_cache/run_with_remote_table.sh
  pkg/data_cache/Cargo.lock
  pkg/data_cache/Cargo.toml
  pkg/data_cache/OWNERS
  pkg/data_cache/README.md
  pkg/data_cache/cmd/head/main.rs
  pkg/data_cache/cmd/worker/main.rs
  pkg/data_cache/src/config/config.rs
  pkg/data_cache/src/config/mod.rs
  pkg/data_cache/src/head/head.rs
  pkg/data_cache/src/head/head_service.rs
  pkg/data_cache/src/head/mod.rs
  pkg/data_cache/src/head/provider.rs
  pkg/data_cache/src/head/writer.rs
  pkg/data_cache/src/lib.rs
  pkg/data_cache/src/worker/indexable_mem_table.rs
  pkg/data_cache/src/worker/mod.rs
  pkg/data_cache/src/worker/worker.rs
  pkg/data_cache/src/worker/worker_datasource.rs
  pkg/data_cache/src/worker/worker_service.rs
  pkg/data_cache/test/Cargo.lock
  pkg/data_cache/test/Cargo.toml
  pkg/data_cache/test/src/main.rs
Labels: size/XXL, lgtm, approved

#2853 [release-2.0] fix: update examples to reflect func_args now being unpacked (#2815)
  examples/deepspeed/text-summarization/T5-Fine-Tuning.ipynb
  examples/mlx/image-classification/mnist.ipynb
  examples/mlx/language-modeling/fine-tune-llama.ipynb
  examples/pytorch/question-answering/fine-tune-distilbert.ipynb
Labels: size/L, lgtm, approved

#2864 feat(docs): Add changelog for Kubeflow Trainer v2.0.1
  CHANGELOG.md
Labels: size/S, lgtm, approved, ok-to-test

#2867 feat(docs): Update Trainer diagram and SDK release
  README.md
  docs/images/trainer-tech-stack.drawio.svg
Labels: size/XS, lgtm, approved
